// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspace.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acceptInvitation = `-- name: AcceptInvitation :one
UPDATE invitations
SET accepted_at = now(), accepted_by = $2
WHERE id = $1 AND accepted_at IS NULL
RETURNING id, workspace_id, email, role, token_hash, invited_by, expires_at, accepted_at, accepted_by, created_at
`

type AcceptInvitationParams struct {
	ID         uuid.UUID
	AcceptedBy *uuid.UUID
}

func (q *Queries) AcceptInvitation(ctx context.Context, arg AcceptInvitationParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, acceptInvitation, arg.ID, arg.AcceptedBy)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedBy,
		&i.CreatedAt,
	)
	return i, err
}

const countMembers = `-- name: CountMembers :one
SELECT count(*)::bigint FROM members WHERE workspace_id = $1
`

func (q *Queries) CountMembers(ctx context.Context, workspaceID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMembers, workspaceID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countOwners = `-- name: CountOwners :one
SELECT count(*)::bigint FROM members WHERE workspace_id = $1 AND role = 'owner'
`

func (q *Queries) CountOwners(ctx context.Context, workspaceID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOwners, workspaceID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO invitations (workspace_id, email, role, token_hash, invited_by, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, workspace_id, email, role, token_hash, invited_by, expires_at, accepted_at, accepted_by, created_at
`

type CreateInvitationParams struct {
	WorkspaceID uuid.UUID
	Email       string
	Role        string
	TokenHash   string
	InvitedBy   *uuid.UUID
	ExpiresAt   time.Time
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.WorkspaceID,
		arg.Email,
		arg.Role,
		arg.TokenHash,
		arg.InvitedBy,
		arg.ExpiresAt,
	)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createMember = `-- name: CreateMember :one
INSERT INTO members (workspace_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING id, workspace_id, user_id, role, created_at, updated_at
`

type CreateMemberParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	Role        string
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, createMember, arg.WorkspaceID, arg.UserID, arg.Role)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (workspace_id, name, kind)
VALUES ($1, $2, $3)
RETURNING id, workspace_id, name, kind, created_at, updated_at
`

type CreateTeamParams struct {
	WorkspaceID uuid.UUID
	Name        string
	Kind        string
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam, arg.WorkspaceID, arg.Name, arg.Kind)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (name, business_field, timezone, owner_user_id)
VALUES ($1, $2, $3, $4)
RETURNING id, name, business_field, timezone, language, work_hours_start, work_hours_end, created_at, updated_at, owner_user_id
`

type CreateWorkspaceParams struct {
	Name          string
	BusinessField string
	Timezone      string
	OwnerUserID   *uuid.UUID
}

// Runs with app.user_id set; the RLS insert policy requires the owner to be the
// authenticated user, so a workspace can never be created for someone else.
func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace,
		arg.Name,
		arg.BusinessField,
		arg.Timezone,
		arg.OwnerUserID,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BusinessField,
		&i.Timezone,
		&i.Language,
		&i.WorkHoursStart,
		&i.WorkHoursEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerUserID,
	)
	return i, err
}

const deleteInvitation = `-- name: DeleteInvitation :execrows
DELETE FROM invitations WHERE workspace_id = $1 AND id = $2
`

type DeleteInvitationParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) DeleteInvitation(ctx context.Context, arg DeleteInvitationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteInvitation, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteMember = `-- name: DeleteMember :execrows
DELETE FROM members WHERE workspace_id = $1 AND user_id = $2
`

type DeleteMemberParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) DeleteMember(ctx context.Context, arg DeleteMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMember, arg.WorkspaceID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getInvitationByTokenHash = `-- name: GetInvitationByTokenHash :one
SELECT i.id, i.workspace_id, i.email, i.role, i.token_hash, i.invited_by, i.expires_at, i.accepted_at, i.accepted_by, i.created_at, coalesce(w.name, '')::text AS workspace_name
FROM invitations i
LEFT JOIN workspaces w ON w.id = i.workspace_id
WHERE i.token_hash = $1
`

type GetInvitationByTokenHashRow struct {
	ID            uuid.UUID
	WorkspaceID   uuid.UUID
	Email         string
	Role          string
	TokenHash     string
	InvitedBy     *uuid.UUID
	ExpiresAt     time.Time
	AcceptedAt    *time.Time
	AcceptedBy    *uuid.UUID
	CreatedAt     time.Time
	WorkspaceName string
}

// Readable by the invitee (policy matches their email) so they can accept
// before they are a member. The LEFT JOIN keeps the row even if the workspace
// is not readable, in which case the name is empty.
func (q *Queries) GetInvitationByTokenHash(ctx context.Context, tokenHash string) (GetInvitationByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getInvitationByTokenHash, tokenHash)
	var i GetInvitationByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedBy,
		&i.CreatedAt,
		&i.WorkspaceName,
	)
	return i, err
}

const getMemberDetail = `-- name: GetMemberDetail :one
SELECT m.id, m.workspace_id, m.user_id, m.role, m.created_at, m.updated_at,
       u.email, u.email_verified_at
FROM members m
JOIN users u ON u.id = m.user_id
WHERE m.workspace_id = $1 AND m.user_id = $2
`

type GetMemberDetailParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
}

type GetMemberDetailRow struct {
	ID              uuid.UUID
	WorkspaceID     uuid.UUID
	UserID          uuid.UUID
	Role            string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Email           string
	EmailVerifiedAt *time.Time
}

// A single membership with the account's address, used when a role change has
// to be reported back with the member's email.
func (q *Queries) GetMemberDetail(ctx context.Context, arg GetMemberDetailParams) (GetMemberDetailRow, error) {
	row := q.db.QueryRow(ctx, getMemberDetail, arg.WorkspaceID, arg.UserID)
	var i GetMemberDetailRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.EmailVerifiedAt,
	)
	return i, err
}

const getMembership = `-- name: GetMembership :one
SELECT id, workspace_id, user_id, role, created_at, updated_at FROM members WHERE workspace_id = $1 AND user_id = $2
`

type GetMembershipParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
}

// The tenant middleware uses this to turn a requested workspace id into a role.
func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (Member, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.WorkspaceID, arg.UserID)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOwnedWorkspaceForUser = `-- name: GetOwnedWorkspaceForUser :one
SELECT id, name, business_field, timezone, language, work_hours_start, work_hours_end, created_at, updated_at, owner_user_id FROM workspaces
WHERE owner_user_id = $1
ORDER BY created_at
LIMIT 1
`

// Onboarding idempotency: the workspace this user already created.
func (q *Queries) GetOwnedWorkspaceForUser(ctx context.Context, ownerUserID *uuid.UUID) (Workspace, error) {
	row := q.db.QueryRow(ctx, getOwnedWorkspaceForUser, ownerUserID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BusinessField,
		&i.Timezone,
		&i.Language,
		&i.WorkHoursStart,
		&i.WorkHoursEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerUserID,
	)
	return i, err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, name, business_field, timezone, language, work_hours_start, work_hours_end, created_at, updated_at, owner_user_id FROM workspaces WHERE id = $1
`

func (q *Queries) GetWorkspace(ctx context.Context, id uuid.UUID) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspace, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BusinessField,
		&i.Timezone,
		&i.Language,
		&i.WorkHoursStart,
		&i.WorkHoursEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerUserID,
	)
	return i, err
}

const listInvitations = `-- name: ListInvitations :many
SELECT id, workspace_id, email, role, token_hash, invited_by, expires_at, accepted_at, accepted_by, created_at FROM invitations
WHERE workspace_id = $1 AND accepted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListInvitations(ctx context.Context, workspaceID uuid.UUID) ([]Invitation, error) {
	rows, err := q.db.Query(ctx, listInvitations, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invitation{}
	for rows.Next() {
		var i Invitation
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Email,
			&i.Role,
			&i.TokenHash,
			&i.InvitedBy,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.AcceptedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembers = `-- name: ListMembers :many
SELECT m.id, m.workspace_id, m.user_id, m.role, m.created_at, m.updated_at, u.email, u.email_verified_at
FROM members m
JOIN users u ON u.id = m.user_id
WHERE m.workspace_id = $1
ORDER BY m.created_at
`

type ListMembersRow struct {
	ID              uuid.UUID
	WorkspaceID     uuid.UUID
	UserID          uuid.UUID
	Role            string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Email           string
	EmailVerifiedAt *time.Time
}

func (q *Queries) ListMembers(ctx context.Context, workspaceID uuid.UUID) ([]ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembersRow{}
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
			&i.EmailVerifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeams = `-- name: ListTeams :many
SELECT id, workspace_id, name, kind, created_at, updated_at FROM teams WHERE workspace_id = $1 ORDER BY name
`

func (q *Queries) ListTeams(ctx context.Context, workspaceID uuid.UUID) ([]Team, error) {
	rows, err := q.db.Query(ctx, listTeams, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Team{}
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Kind,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacesForUser = `-- name: ListWorkspacesForUser :many
SELECT w.id, w.name, w.business_field, w.timezone, w.language, w.work_hours_start, w.work_hours_end, w.created_at, w.updated_at, w.owner_user_id, m.role
FROM workspaces w
JOIN members m ON m.workspace_id = w.id
WHERE m.user_id = $1
ORDER BY w.created_at
`

type ListWorkspacesForUserRow struct {
	ID             uuid.UUID
	Name           string
	BusinessField  string
	Timezone       string
	Language       string
	WorkHoursStart pgtype.Time
	WorkHoursEnd   pgtype.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
	OwnerUserID    *uuid.UUID
	Role           string
}

// Powers the workspace switcher. The members read policy lets a user see their
// own membership rows without an active workspace.
func (q *Queries) ListWorkspacesForUser(ctx context.Context, userID uuid.UUID) ([]ListWorkspacesForUserRow, error) {
	rows, err := q.db.Query(ctx, listWorkspacesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspacesForUserRow{}
	for rows.Next() {
		var i ListWorkspacesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BusinessField,
			&i.Timezone,
			&i.Language,
			&i.WorkHoursStart,
			&i.WorkHoursEnd,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerUserID,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMemberRole = `-- name: UpdateMemberRole :one
UPDATE members
SET role = $3, updated_at = now()
WHERE workspace_id = $1 AND user_id = $2
RETURNING id, workspace_id, user_id, role, created_at, updated_at
`

type UpdateMemberRoleParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	Role        string
}

func (q *Queries) UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) (Member, error) {
	row := q.db.QueryRow(ctx, updateMemberRole, arg.WorkspaceID, arg.UserID, arg.Role)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWorkspace = `-- name: UpdateWorkspace :one
UPDATE workspaces
SET name = $2, business_field = $3, timezone = $4, updated_at = now()
WHERE id = $1
RETURNING id, name, business_field, timezone, language, work_hours_start, work_hours_end, created_at, updated_at, owner_user_id
`

type UpdateWorkspaceParams struct {
	ID            uuid.UUID
	Name          string
	BusinessField string
	Timezone      string
}

func (q *Queries) UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, updateWorkspace,
		arg.ID,
		arg.Name,
		arg.BusinessField,
		arg.Timezone,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BusinessField,
		&i.Timezone,
		&i.Language,
		&i.WorkHoursStart,
		&i.WorkHoursEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerUserID,
	)
	return i, err
}
