// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const appendTaskStep = `-- name: AppendTaskStep :one

INSERT INTO task_steps (
    workspace_id, task_id, seq, kind, tool_name, tool_label,
    input, output, input_tokens, output_tokens
)
VALUES (
    $1, $2,
    COALESCE((SELECT max(seq) FROM task_steps WHERE task_id = $2), 0) + 1,
    $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, workspace_id, task_id, seq, kind, tool_name, tool_label, input, output, input_tokens, output_tokens, pruned_at, created_at
`

type AppendTaskStepParams struct {
	WorkspaceID  uuid.UUID
	TaskID       uuid.UUID
	Kind         string
	ToolName     string
	ToolLabel    string
	Input        []byte
	Output       []byte
	InputTokens  int32
	OutputTokens int32
}

// ------------------------------------------------------------------- steps
// The sequence number is assigned in the statement rather than by the caller:
// two activities writing at once would otherwise pick the same number and lose
// a step to the unique index.
func (q *Queries) AppendTaskStep(ctx context.Context, arg AppendTaskStepParams) (TaskStep, error) {
	row := q.db.QueryRow(ctx, appendTaskStep,
		arg.WorkspaceID,
		arg.TaskID,
		arg.Kind,
		arg.ToolName,
		arg.ToolLabel,
		arg.Input,
		arg.Output,
		arg.InputTokens,
		arg.OutputTokens,
	)
	var i TaskStep
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TaskID,
		&i.Seq,
		&i.Kind,
		&i.ToolName,
		&i.ToolLabel,
		&i.Input,
		&i.Output,
		&i.InputTokens,
		&i.OutputTokens,
		&i.PrunedAt,
		&i.CreatedAt,
	)
	return i, err
}

const cancelTask = `-- name: CancelTask :one
UPDATE tasks
SET status = 'canceled',
    stopped_reason = $3,
    finished_at = now(),
    updated_at = now()
WHERE id = $1 AND workspace_id = $2
  AND status IN ('queued', 'running', 'waiting_approval')
RETURNING id, workspace_id, agent_id, parent_task_id, conversation_id, trigger, title, status, workflow_id, temporal_run_id, stopped_reason, summary, step_count, input_tokens, output_tokens, cost_micros, started_at, finished_at, created_at, updated_at, depth, heartbeat_at, waiting_reason, waiting_draft_id, reply_message_id
`

type CancelTaskParams struct {
	ID            uuid.UUID
	WorkspaceID   uuid.UUID
	StoppedReason string
}

func (q *Queries) CancelTask(ctx context.Context, arg CancelTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, cancelTask, arg.ID, arg.WorkspaceID, arg.StoppedReason)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AgentID,
		&i.ParentTaskID,
		&i.ConversationID,
		&i.Trigger,
		&i.Title,
		&i.Status,
		&i.WorkflowID,
		&i.TemporalRunID,
		&i.StoppedReason,
		&i.Summary,
		&i.StepCount,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CostMicros,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Depth,
		&i.HeartbeatAt,
		&i.WaitingReason,
		&i.WaitingDraftID,
		&i.ReplyMessageID,
	)
	return i, err
}

const countLiveTasksForAgent = `-- name: CountLiveTasksForAgent :one
SELECT count(*)::bigint FROM tasks
WHERE workspace_id = $1 AND agent_id = $2
  AND status IN ('queued', 'running', 'waiting_approval')
`

type CountLiveTasksForAgentParams struct {
	WorkspaceID uuid.UUID
	AgentID     uuid.UUID
}

func (q *Queries) CountLiveTasksForAgent(ctx context.Context, arg CountLiveTasksForAgentParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLiveTasksForAgent, arg.WorkspaceID, arg.AgentID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createTask = `-- name: CreateTask :one

INSERT INTO tasks (
    workspace_id, agent_id, parent_task_id, conversation_id, reply_message_id,
    trigger, title, status, depth
)
SELECT
    $1,
    a.id,
    $2::uuid,
    $3::uuid,
    $4::uuid,
    $5,
    $6,
    'queued',
    $7
FROM agents a
WHERE a.id = $8
  AND a.workspace_id = $1
  AND a.deleted_at IS NULL
  AND (
      $3::uuid IS NULL
      OR EXISTS (
          SELECT 1 FROM conversations c
          WHERE c.id = $3::uuid
            AND c.workspace_id = $1
      )
  )
  AND (
      $4::uuid IS NULL
      OR EXISTS (
          SELECT 1 FROM messages m
          WHERE m.id = $4::uuid
            AND m.workspace_id = $1
      )
  )
  AND (
      $2::uuid IS NULL
      OR EXISTS (
          SELECT 1 FROM tasks p
          WHERE p.id = $2::uuid
            AND p.workspace_id = $1
      )
  )
RETURNING id, workspace_id, agent_id, parent_task_id, conversation_id, trigger, title, status, workflow_id, temporal_run_id, stopped_reason, summary, step_count, input_tokens, output_tokens, cost_micros, started_at, finished_at, created_at, updated_at, depth, heartbeat_at, waiting_reason, waiting_draft_id, reply_message_id
`

type CreateTaskParams struct {
	WorkspaceID    uuid.UUID
	ParentTaskID   *uuid.UUID
	ConversationID *uuid.UUID
	ReplyMessageID *uuid.UUID
	Trigger        string
	Title          string
	Depth          int32
	AgentID        uuid.UUID
}

// Task runtime queries. Every statement carries workspace_id as well as the Row
// Level Security policy, so a wrong id in application code still cannot reach
// another tenant's task.
// The insert is a SELECT rather than a VALUES list so the statement itself
// refuses an agent, a conversation, or a parent task from another workspace.
// A foreign key cannot catch that: a key check runs with the table owner's
// rights and bypasses Row Level Security, so a cross-tenant reference would be
// accepted while every read of it stays invisible.
func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.WorkspaceID,
		arg.ParentTaskID,
		arg.ConversationID,
		arg.ReplyMessageID,
		arg.Trigger,
		arg.Title,
		arg.Depth,
		arg.AgentID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AgentID,
		&i.ParentTaskID,
		&i.ConversationID,
		&i.Trigger,
		&i.Title,
		&i.Status,
		&i.WorkflowID,
		&i.TemporalRunID,
		&i.StoppedReason,
		&i.Summary,
		&i.StepCount,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CostMicros,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Depth,
		&i.HeartbeatAt,
		&i.WaitingReason,
		&i.WaitingDraftID,
		&i.ReplyMessageID,
	)
	return i, err
}

const finishTask = `-- name: FinishTask :one
UPDATE tasks
SET status = $3,
    summary = $4,
    stopped_reason = $5,
    input_tokens = $6,
    output_tokens = $7,
    cost_micros = $8,
    step_count = $9,
    waiting_reason = '',
    waiting_draft_id = NULL,
    finished_at = now(),
    heartbeat_at = now(),
    updated_at = now()
WHERE id = $1 AND workspace_id = $2
  AND status IN ('queued', 'running', 'waiting_approval')
RETURNING id, workspace_id, agent_id, parent_task_id, conversation_id, trigger, title, status, workflow_id, temporal_run_id, stopped_reason, summary, step_count, input_tokens, output_tokens, cost_micros, started_at, finished_at, created_at, updated_at, depth, heartbeat_at, waiting_reason, waiting_draft_id, reply_message_id
`

type FinishTaskParams struct {
	ID            uuid.UUID
	WorkspaceID   uuid.UUID
	Status        string
	Summary       string
	StoppedReason string
	InputTokens   int64
	OutputTokens  int64
	CostMicros    int64
	StepCount     int32
}

// The terminal write. Only a task that is still live can be finished, so a
// retried activity cannot overwrite a result the user has already seen.
func (q *Queries) FinishTask(ctx context.Context, arg FinishTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, finishTask,
		arg.ID,
		arg.WorkspaceID,
		arg.Status,
		arg.Summary,
		arg.StoppedReason,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CostMicros,
		arg.StepCount,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AgentID,
		&i.ParentTaskID,
		&i.ConversationID,
		&i.Trigger,
		&i.Title,
		&i.Status,
		&i.WorkflowID,
		&i.TemporalRunID,
		&i.StoppedReason,
		&i.Summary,
		&i.StepCount,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CostMicros,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Depth,
		&i.HeartbeatAt,
		&i.WaitingReason,
		&i.WaitingDraftID,
		&i.ReplyMessageID,
	)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT id, workspace_id, agent_id, parent_task_id, conversation_id, trigger, title, status, workflow_id, temporal_run_id, stopped_reason, summary, step_count, input_tokens, output_tokens, cost_micros, started_at, finished_at, created_at, updated_at, depth, heartbeat_at, waiting_reason, waiting_draft_id, reply_message_id FROM tasks WHERE id = $1 AND workspace_id = $2
`

type GetTaskParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) GetTask(ctx context.Context, arg GetTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, arg.ID, arg.WorkspaceID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AgentID,
		&i.ParentTaskID,
		&i.ConversationID,
		&i.Trigger,
		&i.Title,
		&i.Status,
		&i.WorkflowID,
		&i.TemporalRunID,
		&i.StoppedReason,
		&i.Summary,
		&i.StepCount,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CostMicros,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Depth,
		&i.HeartbeatAt,
		&i.WaitingReason,
		&i.WaitingDraftID,
		&i.ReplyMessageID,
	)
	return i, err
}

const lastTaskStep = `-- name: LastTaskStep :one
SELECT id, workspace_id, task_id, seq, kind, tool_name, tool_label, input, output, input_tokens, output_tokens, pruned_at, created_at FROM task_steps
WHERE workspace_id = $1 AND task_id = $2
ORDER BY seq DESC
LIMIT 1
`

type LastTaskStepParams struct {
	WorkspaceID uuid.UUID
	TaskID      uuid.UUID
}

// The final answer, which the summary is built from.
func (q *Queries) LastTaskStep(ctx context.Context, arg LastTaskStepParams) (TaskStep, error) {
	row := q.db.QueryRow(ctx, lastTaskStep, arg.WorkspaceID, arg.TaskID)
	var i TaskStep
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TaskID,
		&i.Seq,
		&i.Kind,
		&i.ToolName,
		&i.ToolLabel,
		&i.Input,
		&i.Output,
		&i.InputTokens,
		&i.OutputTokens,
		&i.PrunedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listChildTasks = `-- name: ListChildTasks :many
SELECT id, workspace_id, agent_id, parent_task_id, conversation_id, trigger, title, status, workflow_id, temporal_run_id, stopped_reason, summary, step_count, input_tokens, output_tokens, cost_micros, started_at, finished_at, created_at, updated_at, depth, heartbeat_at, waiting_reason, waiting_draft_id, reply_message_id FROM tasks
WHERE workspace_id = $1 AND parent_task_id = $2
ORDER BY created_at
`

type ListChildTasksParams struct {
	WorkspaceID  uuid.UUID
	ParentTaskID *uuid.UUID
}

func (q *Queries) ListChildTasks(ctx context.Context, arg ListChildTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listChildTasks, arg.WorkspaceID, arg.ParentTaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.AgentID,
			&i.ParentTaskID,
			&i.ConversationID,
			&i.Trigger,
			&i.Title,
			&i.Status,
			&i.WorkflowID,
			&i.TemporalRunID,
			&i.StoppedReason,
			&i.Summary,
			&i.StepCount,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CostMicros,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Depth,
			&i.HeartbeatAt,
			&i.WaitingReason,
			&i.WaitingDraftID,
			&i.ReplyMessageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskSteps = `-- name: ListTaskSteps :many
SELECT id, workspace_id, task_id, seq, kind, tool_name, tool_label, input, output, input_tokens, output_tokens, pruned_at, created_at FROM task_steps
WHERE workspace_id = $1 AND task_id = $2
ORDER BY seq
`

type ListTaskStepsParams struct {
	WorkspaceID uuid.UUID
	TaskID      uuid.UUID
}

func (q *Queries) ListTaskSteps(ctx context.Context, arg ListTaskStepsParams) ([]TaskStep, error) {
	rows, err := q.db.Query(ctx, listTaskSteps, arg.WorkspaceID, arg.TaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskStep{}
	for rows.Next() {
		var i TaskStep
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.TaskID,
			&i.Seq,
			&i.Kind,
			&i.ToolName,
			&i.ToolLabel,
			&i.Input,
			&i.Output,
			&i.InputTokens,
			&i.OutputTokens,
			&i.PrunedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT id, workspace_id, agent_id, parent_task_id, conversation_id, trigger, title, status, workflow_id, temporal_run_id, stopped_reason, summary, step_count, input_tokens, output_tokens, cost_micros, started_at, finished_at, created_at, updated_at, depth, heartbeat_at, waiting_reason, waiting_draft_id, reply_message_id FROM tasks
WHERE workspace_id = $1
  AND ($3::uuid IS NULL OR agent_id = $3::uuid)
  AND ($4::uuid IS NULL OR parent_task_id = $4::uuid)
  AND ($5::text IS NULL OR status = $5::text)
  AND (
      $6::boolean = false
      OR status IN ('queued', 'running', 'waiting_approval')
  )
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListTasksParams struct {
	WorkspaceID  uuid.UUID
	Limit        int32
	AgentID      *uuid.UUID
	ParentTaskID *uuid.UUID
	Status       *string
	Live         bool
}

// The history. Every filter is optional and the ordering is fixed, so the
// endpoint has one shape rather than one per combination.
func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasks,
		arg.WorkspaceID,
		arg.Limit,
		arg.AgentID,
		arg.ParentTaskID,
		arg.Status,
		arg.Live,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.AgentID,
			&i.ParentTaskID,
			&i.ConversationID,
			&i.Trigger,
			&i.Title,
			&i.Status,
			&i.WorkflowID,
			&i.TemporalRunID,
			&i.StoppedReason,
			&i.Summary,
			&i.StepCount,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CostMicros,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Depth,
			&i.HeartbeatAt,
			&i.WaitingReason,
			&i.WaitingDraftID,
			&i.ReplyMessageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const parkTask = `-- name: ParkTask :one
UPDATE tasks
SET status = 'waiting_approval',
    waiting_reason = $3,
    waiting_draft_id = $4,
    heartbeat_at = now(),
    updated_at = now()
WHERE id = $1 AND workspace_id = $2 AND status IN ('queued', 'running')
RETURNING id, workspace_id, agent_id, parent_task_id, conversation_id, trigger, title, status, workflow_id, temporal_run_id, stopped_reason, summary, step_count, input_tokens, output_tokens, cost_micros, started_at, finished_at, created_at, updated_at, depth, heartbeat_at, waiting_reason, waiting_draft_id, reply_message_id
`

type ParkTaskParams struct {
	ID             uuid.UUID
	WorkspaceID    uuid.UUID
	WaitingReason  string
	WaitingDraftID *uuid.UUID
}

// A task waiting for a human has not stopped; it is parked, and the reason is
// what the office and the task endpoint show.
func (q *Queries) ParkTask(ctx context.Context, arg ParkTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, parkTask,
		arg.ID,
		arg.WorkspaceID,
		arg.WaitingReason,
		arg.WaitingDraftID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AgentID,
		&i.ParentTaskID,
		&i.ConversationID,
		&i.Trigger,
		&i.Title,
		&i.Status,
		&i.WorkflowID,
		&i.TemporalRunID,
		&i.StoppedReason,
		&i.Summary,
		&i.StepCount,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CostMicros,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Depth,
		&i.HeartbeatAt,
		&i.WaitingReason,
		&i.WaitingDraftID,
		&i.ReplyMessageID,
	)
	return i, err
}

const progressTask = `-- name: ProgressTask :one
UPDATE tasks
SET heartbeat_at = now(),
    input_tokens = $3,
    output_tokens = $4,
    cost_micros = $5,
    step_count = $6,
    updated_at = now()
WHERE id = $1 AND workspace_id = $2 AND status IN ('queued', 'running')
RETURNING id, workspace_id, agent_id, parent_task_id, conversation_id, trigger, title, status, workflow_id, temporal_run_id, stopped_reason, summary, step_count, input_tokens, output_tokens, cost_micros, started_at, finished_at, created_at, updated_at, depth, heartbeat_at, waiting_reason, waiting_draft_id, reply_message_id
`

type ProgressTaskParams struct {
	ID           uuid.UUID
	WorkspaceID  uuid.UUID
	InputTokens  int64
	OutputTokens int64
	CostMicros   int64
	StepCount    int32
}

// The heartbeat. A task that stops touching this is the one a worker died on,
// which is why it is written with the running totals rather than alone.
func (q *Queries) ProgressTask(ctx context.Context, arg ProgressTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, progressTask,
		arg.ID,
		arg.WorkspaceID,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CostMicros,
		arg.StepCount,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AgentID,
		&i.ParentTaskID,
		&i.ConversationID,
		&i.Trigger,
		&i.Title,
		&i.Status,
		&i.WorkflowID,
		&i.TemporalRunID,
		&i.StoppedReason,
		&i.Summary,
		&i.StepCount,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CostMicros,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Depth,
		&i.HeartbeatAt,
		&i.WaitingReason,
		&i.WaitingDraftID,
		&i.ReplyMessageID,
	)
	return i, err
}

const resumeTask = `-- name: ResumeTask :one
UPDATE tasks
SET status = 'running',
    waiting_reason = '',
    waiting_draft_id = NULL,
    heartbeat_at = now(),
    updated_at = now()
WHERE id = $1 AND workspace_id = $2 AND status = 'waiting_approval'
RETURNING id, workspace_id, agent_id, parent_task_id, conversation_id, trigger, title, status, workflow_id, temporal_run_id, stopped_reason, summary, step_count, input_tokens, output_tokens, cost_micros, started_at, finished_at, created_at, updated_at, depth, heartbeat_at, waiting_reason, waiting_draft_id, reply_message_id
`

type ResumeTaskParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) ResumeTask(ctx context.Context, arg ResumeTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, resumeTask, arg.ID, arg.WorkspaceID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AgentID,
		&i.ParentTaskID,
		&i.ConversationID,
		&i.Trigger,
		&i.Title,
		&i.Status,
		&i.WorkflowID,
		&i.TemporalRunID,
		&i.StoppedReason,
		&i.Summary,
		&i.StepCount,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CostMicros,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Depth,
		&i.HeartbeatAt,
		&i.WaitingReason,
		&i.WaitingDraftID,
		&i.ReplyMessageID,
	)
	return i, err
}

const startTask = `-- name: StartTask :one
UPDATE tasks
SET status = 'running',
    workflow_id = $3,
    temporal_run_id = $4,
    started_at = COALESCE(started_at, now()),
    heartbeat_at = now(),
    updated_at = now()
WHERE id = $1 AND workspace_id = $2 AND status IN ('queued', 'running')
RETURNING id, workspace_id, agent_id, parent_task_id, conversation_id, trigger, title, status, workflow_id, temporal_run_id, stopped_reason, summary, step_count, input_tokens, output_tokens, cost_micros, started_at, finished_at, created_at, updated_at, depth, heartbeat_at, waiting_reason, waiting_draft_id, reply_message_id
`

type StartTaskParams struct {
	ID            uuid.UUID
	WorkspaceID   uuid.UUID
	WorkflowID    string
	TemporalRunID string
}

// Recording the workflow is what makes a restart resume the task instead of
// opening a second one, so it is written in the same statement as the status.
func (q *Queries) StartTask(ctx context.Context, arg StartTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, startTask,
		arg.ID,
		arg.WorkspaceID,
		arg.WorkflowID,
		arg.TemporalRunID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AgentID,
		&i.ParentTaskID,
		&i.ConversationID,
		&i.Trigger,
		&i.Title,
		&i.Status,
		&i.WorkflowID,
		&i.TemporalRunID,
		&i.StoppedReason,
		&i.Summary,
		&i.StepCount,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CostMicros,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Depth,
		&i.HeartbeatAt,
		&i.WaitingReason,
		&i.WaitingDraftID,
		&i.ReplyMessageID,
	)
	return i, err
}
