// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/robzlabz/employeebot/apps/backend/internal/modules/health/domain"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// Liveness provides a mock function with no fields
func (_m *Service) Liveness() domain.Report {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Liveness")
	}

	var r0 domain.Report
	if rf, ok := ret.Get(0).(func() domain.Report); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(domain.Report)
	}

	return r0
}

// Service_Liveness_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Liveness'
type Service_Liveness_Call struct {
	*mock.Call
}

// Liveness is a helper method to define mock.On call
func (_e *Service_Expecter) Liveness() *Service_Liveness_Call {
	return &Service_Liveness_Call{Call: _e.mock.On("Liveness")}
}

func (_c *Service_Liveness_Call) Run(run func()) *Service_Liveness_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Service_Liveness_Call) Return(_a0 domain.Report) *Service_Liveness_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_Liveness_Call) RunAndReturn(run func() domain.Report) *Service_Liveness_Call {
	_c.Call.Return(run)
	return _c
}

// Readiness provides a mock function with given fields: ctx
func (_m *Service) Readiness(ctx context.Context) domain.Report {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Readiness")
	}

	var r0 domain.Report
	if rf, ok := ret.Get(0).(func(context.Context) domain.Report); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(domain.Report)
	}

	return r0
}

// Service_Readiness_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Readiness'
type Service_Readiness_Call struct {
	*mock.Call
}

// Readiness is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Service_Expecter) Readiness(ctx interface{}) *Service_Readiness_Call {
	return &Service_Readiness_Call{Call: _e.mock.On("Readiness", ctx)}
}

func (_c *Service_Readiness_Call) Run(run func(ctx context.Context)) *Service_Readiness_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Service_Readiness_Call) Return(_a0 domain.Report) *Service_Readiness_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_Readiness_Call) RunAndReturn(run func(context.Context) domain.Report) *Service_Readiness_Call {
	_c.Call.Return(run)
	return _c
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
