// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Checker is an autogenerated mock type for the Checker type
type Checker struct {
	mock.Mock
}

type Checker_Expecter struct {
	mock *mock.Mock
}

func (_m *Checker) EXPECT() *Checker_Expecter {
	return &Checker_Expecter{mock: &_m.Mock}
}

// Ping provides a mock function with given fields: ctx
func (_m *Checker) Ping(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Checker_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type Checker_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Checker_Expecter) Ping(ctx interface{}) *Checker_Ping_Call {
	return &Checker_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *Checker_Ping_Call) Run(run func(ctx context.Context)) *Checker_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Checker_Ping_Call) Return(_a0 error) *Checker_Ping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Checker_Ping_Call) RunAndReturn(run func(context.Context) error) *Checker_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// NewChecker creates a new instance of Checker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *Checker {
	mock := &Checker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
