// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type ActivityEvent struct {
	ID             int64
	WorkspaceID    uuid.UUID
	Type           string
	ActorAgentID   *uuid.UUID
	ActorUserID    *uuid.UUID
	ConversationID *uuid.UUID
	TaskID         *uuid.UUID
	DraftID        *uuid.UUID
	Payload        []byte
	CreatedAt      time.Time
}

type Agent struct {
	ID           uuid.UUID
	WorkspaceID  uuid.UUID
	TeamID       uuid.UUID
	Name         string
	Role         string
	Persona      string
	Tone         string
	Shape        string
	Color        string
	Status       string
	TemplateKey  string
	DefaultModel []byte
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    *time.Time
	Tools        []byte
}

type AgentGrant struct {
	ID            uuid.UUID
	WorkspaceID   uuid.UUID
	AgentID       uuid.UUID
	IntegrationID uuid.UUID
	Permission    string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type AgentTemplate struct {
	ID           uuid.UUID
	Key          string
	Name         string
	Role         string
	Persona      string
	Tone         string
	Shape        string
	Color        string
	Tools        []byte
	Integrations []byte
	DefaultModel []byte
	SortOrder    int32
	CreatedAt    time.Time
}

type ApprovalPolicy struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	ActionKind  string
	Mode        string
	MaxAmount   *int64
	UpdatedBy   *uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type AuditLog struct {
	ID           int64
	WorkspaceID  uuid.UUID
	ActorUserID  *uuid.UUID
	ActorAgentID *uuid.UUID
	Action       string
	ObjectType   string
	ObjectID     string
	Metadata     []byte
	CreatedAt    time.Time
}

type BillingInvoice struct {
	ID                uuid.UUID
	WorkspaceID       uuid.UUID
	SubscriptionID    *uuid.UUID
	Provider          string
	ProviderReference string
	AmountIdr         int64
	Status            string
	PeriodStart       time.Time
	PeriodEnd         time.Time
	PaidAt            *time.Time
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type Conversation struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Kind        string
	Title       string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type ConversationParticipant struct {
	ID             uuid.UUID
	WorkspaceID    uuid.UUID
	ConversationID uuid.UUID
	AgentID        *uuid.UUID
	UserID         *uuid.UUID
	CreatedAt      time.Time
}

type Draft struct {
	ID             uuid.UUID
	WorkspaceID    uuid.UUID
	TaskID         uuid.UUID
	AgentID        uuid.UUID
	ActionKind     string
	Payload        []byte
	Status         string
	Revision       int32
	DecidedBy      *uuid.UUID
	DecidedAt      *time.Time
	DecisionNote   string
	SentAt         *time.Time
	IdempotencyKey string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type EmailVerificationToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt time.Time
	UsedAt    *time.Time
	CreatedAt time.Time
}

type Integration struct {
	ID                    uuid.UUID
	WorkspaceID           uuid.UUID
	App                   string
	AccountLabel          string
	Status                string
	Scopes                []string
	AccessTokenEncrypted  []byte
	RefreshTokenEncrypted []byte
	TokenExpiresAt        *time.Time
	DataKeyWrapped        []byte
	DataKeyKmsKeyID       string
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

type Invitation struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Email       string
	Role        string
	TokenHash   string
	InvitedBy   *uuid.UUID
	ExpiresAt   time.Time
	AcceptedAt  *time.Time
	AcceptedBy  *uuid.UUID
	CreatedAt   time.Time
}

type KnowledgeItem struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	AgentID     *uuid.UUID
	Source      string
	ChunkIndex  int32
	Content     string
	Embedding   *pgvector.Vector
	Status      string
	CreatedAt   time.Time
}

type LlmProvider struct {
	ID              uuid.UUID
	WorkspaceID     uuid.UUID
	Name            string
	Adapter         string
	BaseUrl         string
	Model           string
	ApiKeyEncrypted []byte
	Priority        int32
	MaxTokens       int32
	ContextTokens   int32
	IsDefault       bool
	Enabled         bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Member struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	Role        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Memory struct {
	ID              uuid.UUID
	WorkspaceID     uuid.UUID
	AgentID         *uuid.UUID
	Content         string
	Kind            string
	SourceMessageID *uuid.UUID
	Embedding       *pgvector.Vector
	Pinned          bool
	CreatedBy       string
	SupersededBy    *uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Message struct {
	ID             uuid.UUID
	WorkspaceID    uuid.UUID
	ConversationID uuid.UUID
	AuthorAgentID  *uuid.UUID
	AuthorUserID   *uuid.UUID
	Blocks         []byte
	Attachments    []byte
	TaskID         *uuid.UUID
	CreatedAt      time.Time
	Status         string
	FinishReason   string
	UpdatedAt      time.Time
}

type MessageAttachment struct {
	ID             uuid.UUID
	WorkspaceID    uuid.UUID
	MessageID      uuid.UUID
	StorageKey     string
	Filename       string
	ContentType    string
	ByteSize       int64
	ChecksumSha256 string
	CreatedAt      time.Time
}

type PasswordResetToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt time.Time
	UsedAt    *time.Time
	CreatedAt time.Time
}

type Plan struct {
	ID              uuid.UUID
	Key             string
	Name            string
	MonthlyPriceIdr int64
	TokenQuota      int64
	MaxAgents       int32
	MaxIntegrations int32
	MaxMembers      int32
	IsTrial         bool
	SortOrder       int32
	CreatedAt       time.Time
}

type QuotaPeriod struct {
	ID               uuid.UUID
	WorkspaceID      uuid.UUID
	PeriodStart      time.Time
	PeriodEnd        time.Time
	TokensGranted    int64
	TokensUsed       int64
	Warning80SentAt  *time.Time
	Warning100SentAt *time.Time
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type Routine struct {
	ID            uuid.UUID
	WorkspaceID   uuid.UUID
	AgentID       uuid.UUID
	Name          string
	Kind          string
	Cron          string
	HourStart     *int32
	HourEnd       *int32
	TriggerSource string
	Instruction   string
	Enabled       bool
	ScheduleID    string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type RoutineRun struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	RoutineID   uuid.UUID
	TaskID      *uuid.UUID
	Status      string
	Summary     string
	StartedAt   time.Time
	FinishedAt  *time.Time
}

type Session struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	RefreshTokenHash string
	RotatedFrom      *uuid.UUID
	UserAgent        string
	Ip               string
	ExpiresAt        time.Time
	RevokedAt        *time.Time
	CreatedAt        time.Time
}

type Subscription struct {
	ID                 uuid.UUID
	WorkspaceID        uuid.UUID
	PlanID             uuid.UUID
	Status             string
	CurrentPeriodStart time.Time
	CurrentPeriodEnd   time.Time
	GraceUntil         *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type Task struct {
	ID             uuid.UUID
	WorkspaceID    uuid.UUID
	AgentID        uuid.UUID
	ParentTaskID   *uuid.UUID
	ConversationID *uuid.UUID
	Trigger        string
	Title          string
	Status         string
	WorkflowID     string
	TemporalRunID  string
	StoppedReason  string
	Summary        string
	StepCount      int32
	InputTokens    int64
	OutputTokens   int64
	CostMicros     int64
	StartedAt      *time.Time
	FinishedAt     *time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type TaskStep struct {
	ID           uuid.UUID
	WorkspaceID  uuid.UUID
	TaskID       uuid.UUID
	Seq          int32
	Kind         string
	ToolName     string
	ToolLabel    string
	Input        []byte
	Output       []byte
	InputTokens  int32
	OutputTokens int32
	PrunedAt     *time.Time
	CreatedAt    time.Time
}

type Team struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Name        string
	Kind        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type ToolCatalog struct {
	Name           string
	IntegrationApp string
	Label          string
	Description    string
	CreatedAt      time.Time
}

// Daily usage totals per workspace, provider, model, and purpose. Days follow Asia/Jakarta, which is where the customers are.
type UsageDaily struct {
	WorkspaceID      uuid.UUID
	Day              time.Time
	Provider         string
	Model            string
	Purpose          string
	Calls            int64
	InputTokens      int64
	OutputTokens     int64
	CacheReadTokens  int64
	CacheWriteTokens int64
	CostMicros       int64
}

type UsageLedger struct {
	ID               int64
	WorkspaceID      uuid.UUID
	AgentID          *uuid.UUID
	TaskID           *uuid.UUID
	Provider         string
	Model            string
	Purpose          string
	InputTokens      int32
	OutputTokens     int32
	CacheReadTokens  int32
	CacheWriteTokens int32
	CostMicros       int64
	CreatedAt        time.Time
}

type User struct {
	ID              uuid.UUID
	Email           string
	PasswordHash    string
	EmailVerifiedAt *time.Time
	GoogleSubject   *string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	OnboardedAt     *time.Time
}

type Workspace struct {
	ID             uuid.UUID
	Name           string
	BusinessField  string
	Timezone       string
	Language       string
	WorkHoursStart pgtype.Time
	WorkHoursEnd   pgtype.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
	OwnerUserID    *uuid.UUID
}
