// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Passwords is an autogenerated mock type for the Passwords type
type Passwords struct {
	mock.Mock
}

type Passwords_Expecter struct {
	mock *mock.Mock
}

func (_m *Passwords) EXPECT() *Passwords_Expecter {
	return &Passwords_Expecter{mock: &_m.Mock}
}

// Hash provides a mock function with given fields: password
func (_m *Passwords) Hash(password string) (string, error) {
	ret := _m.Called(password)

	if len(ret) == 0 {
		panic("no return value specified for Hash")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(password)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Passwords_Hash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hash'
type Passwords_Hash_Call struct {
	*mock.Call
}

// Hash is a helper method to define mock.On call
//   - password string
func (_e *Passwords_Expecter) Hash(password interface{}) *Passwords_Hash_Call {
	return &Passwords_Hash_Call{Call: _e.mock.On("Hash", password)}
}

func (_c *Passwords_Hash_Call) Run(run func(password string)) *Passwords_Hash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Passwords_Hash_Call) Return(_a0 string, _a1 error) *Passwords_Hash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Passwords_Hash_Call) RunAndReturn(run func(string) (string, error)) *Passwords_Hash_Call {
	_c.Call.Return(run)
	return _c
}

// Validate provides a mock function with given fields: password
func (_m *Passwords) Validate(password string) error {
	ret := _m.Called(password)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Passwords_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type Passwords_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - password string
func (_e *Passwords_Expecter) Validate(password interface{}) *Passwords_Validate_Call {
	return &Passwords_Validate_Call{Call: _e.mock.On("Validate", password)}
}

func (_c *Passwords_Validate_Call) Run(run func(password string)) *Passwords_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Passwords_Validate_Call) Return(_a0 error) *Passwords_Validate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Passwords_Validate_Call) RunAndReturn(run func(string) error) *Passwords_Validate_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function with given fields: hash, password
func (_m *Passwords) Verify(hash string, password string) (bool, error) {
	ret := _m.Called(hash, password)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (bool, error)); ok {
		return rf(hash, password)
	}
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(hash, password)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(hash, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Passwords_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type Passwords_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - hash string
//   - password string
func (_e *Passwords_Expecter) Verify(hash interface{}, password interface{}) *Passwords_Verify_Call {
	return &Passwords_Verify_Call{Call: _e.mock.On("Verify", hash, password)}
}

func (_c *Passwords_Verify_Call) Run(run func(hash string, password string)) *Passwords_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *Passwords_Verify_Call) Return(_a0 bool, _a1 error) *Passwords_Verify_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Passwords_Verify_Call) RunAndReturn(run func(string, string) (bool, error)) *Passwords_Verify_Call {
	_c.Call.Return(run)
	return _c
}

// NewPasswords creates a new instance of Passwords. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPasswords(t interface {
	mock.TestingT
	Cleanup(func())
}) *Passwords {
	mock := &Passwords{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
