// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/robzlabz/employeebot/apps/backend/internal/modules/auth/domain"
	mock "github.com/stretchr/testify/mock"
)

// GoogleProvider is an autogenerated mock type for the GoogleProvider type
type GoogleProvider struct {
	mock.Mock
}

type GoogleProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *GoogleProvider) EXPECT() *GoogleProvider_Expecter {
	return &GoogleProvider_Expecter{mock: &_m.Mock}
}

// AuthCodeURL provides a mock function with given fields: state
func (_m *GoogleProvider) AuthCodeURL(state string) string {
	ret := _m.Called(state)

	if len(ret) == 0 {
		panic("no return value specified for AuthCodeURL")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(state)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GoogleProvider_AuthCodeURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthCodeURL'
type GoogleProvider_AuthCodeURL_Call struct {
	*mock.Call
}

// AuthCodeURL is a helper method to define mock.On call
//   - state string
func (_e *GoogleProvider_Expecter) AuthCodeURL(state interface{}) *GoogleProvider_AuthCodeURL_Call {
	return &GoogleProvider_AuthCodeURL_Call{Call: _e.mock.On("AuthCodeURL", state)}
}

func (_c *GoogleProvider_AuthCodeURL_Call) Run(run func(state string)) *GoogleProvider_AuthCodeURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *GoogleProvider_AuthCodeURL_Call) Return(_a0 string) *GoogleProvider_AuthCodeURL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *GoogleProvider_AuthCodeURL_Call) RunAndReturn(run func(string) string) *GoogleProvider_AuthCodeURL_Call {
	_c.Call.Return(run)
	return _c
}

// Exchange provides a mock function with given fields: ctx, code
func (_m *GoogleProvider) Exchange(ctx context.Context, code string) (domain.GoogleUser, error) {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for Exchange")
	}

	var r0 domain.GoogleUser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.GoogleUser, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.GoogleUser); ok {
		r0 = rf(ctx, code)
	} else {
		r0 = ret.Get(0).(domain.GoogleUser)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GoogleProvider_Exchange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exchange'
type GoogleProvider_Exchange_Call struct {
	*mock.Call
}

// Exchange is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *GoogleProvider_Expecter) Exchange(ctx interface{}, code interface{}) *GoogleProvider_Exchange_Call {
	return &GoogleProvider_Exchange_Call{Call: _e.mock.On("Exchange", ctx, code)}
}

func (_c *GoogleProvider_Exchange_Call) Run(run func(ctx context.Context, code string)) *GoogleProvider_Exchange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *GoogleProvider_Exchange_Call) Return(_a0 domain.GoogleUser, _a1 error) *GoogleProvider_Exchange_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GoogleProvider_Exchange_Call) RunAndReturn(run func(context.Context, string) (domain.GoogleUser, error)) *GoogleProvider_Exchange_Call {
	_c.Call.Return(run)
	return _c
}

// NewGoogleProvider creates a new instance of GoogleProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGoogleProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *GoogleProvider {
	mock := &GoogleProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
