// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	domain "github.com/robzlabz/employeebot/apps/backend/internal/modules/auth/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// TokenIssuer is an autogenerated mock type for the TokenIssuer type
type TokenIssuer struct {
	mock.Mock
}

type TokenIssuer_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenIssuer) EXPECT() *TokenIssuer_Expecter {
	return &TokenIssuer_Expecter{mock: &_m.Mock}
}

// Issue provides a mock function with given fields: userID, sessionID
func (_m *TokenIssuer) Issue(userID uuid.UUID, sessionID uuid.UUID) (string, time.Time, error) {
	ret := _m.Called(userID, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for Issue")
	}

	var r0 string
	var r1 time.Time
	var r2 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) (string, time.Time, error)); ok {
		return rf(userID, sessionID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) string); ok {
		r0 = rf(userID, sessionID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, uuid.UUID) time.Time); ok {
		r1 = rf(userID, sessionID)
	} else {
		r1 = ret.Get(1).(time.Time)
	}

	if rf, ok := ret.Get(2).(func(uuid.UUID, uuid.UUID) error); ok {
		r2 = rf(userID, sessionID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// TokenIssuer_Issue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Issue'
type TokenIssuer_Issue_Call struct {
	*mock.Call
}

// Issue is a helper method to define mock.On call
//   - userID uuid.UUID
//   - sessionID uuid.UUID
func (_e *TokenIssuer_Expecter) Issue(userID interface{}, sessionID interface{}) *TokenIssuer_Issue_Call {
	return &TokenIssuer_Issue_Call{Call: _e.mock.On("Issue", userID, sessionID)}
}

func (_c *TokenIssuer_Issue_Call) Run(run func(userID uuid.UUID, sessionID uuid.UUID)) *TokenIssuer_Issue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *TokenIssuer_Issue_Call) Return(_a0 string, _a1 time.Time, _a2 error) *TokenIssuer_Issue_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *TokenIssuer_Issue_Call) RunAndReturn(run func(uuid.UUID, uuid.UUID) (string, time.Time, error)) *TokenIssuer_Issue_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function with given fields: token
func (_m *TokenIssuer) Verify(token string) (domain.AccessClaims, error) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 domain.AccessClaims
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (domain.AccessClaims, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) domain.AccessClaims); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Get(0).(domain.AccessClaims)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TokenIssuer_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type TokenIssuer_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - token string
func (_e *TokenIssuer_Expecter) Verify(token interface{}) *TokenIssuer_Verify_Call {
	return &TokenIssuer_Verify_Call{Call: _e.mock.On("Verify", token)}
}

func (_c *TokenIssuer_Verify_Call) Run(run func(token string)) *TokenIssuer_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *TokenIssuer_Verify_Call) Return(_a0 domain.AccessClaims, _a1 error) *TokenIssuer_Verify_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TokenIssuer_Verify_Call) RunAndReturn(run func(string) (domain.AccessClaims, error)) *TokenIssuer_Verify_Call {
	_c.Call.Return(run)
	return _c
}

// NewTokenIssuer creates a new instance of TokenIssuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenIssuer(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenIssuer {
	mock := &TokenIssuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
