// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/robzlabz/employeebot/apps/backend/internal/modules/auth/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// ConsumeEmailVerificationToken provides a mock function with given fields: ctx, tokenHash
func (_m *Repository) ConsumeEmailVerificationToken(ctx context.Context, tokenHash string) (uuid.UUID, error) {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for ConsumeEmailVerificationToken")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (uuid.UUID, error)); ok {
		return rf(ctx, tokenHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) uuid.UUID); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_ConsumeEmailVerificationToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConsumeEmailVerificationToken'
type Repository_ConsumeEmailVerificationToken_Call struct {
	*mock.Call
}

// ConsumeEmailVerificationToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *Repository_Expecter) ConsumeEmailVerificationToken(ctx interface{}, tokenHash interface{}) *Repository_ConsumeEmailVerificationToken_Call {
	return &Repository_ConsumeEmailVerificationToken_Call{Call: _e.mock.On("ConsumeEmailVerificationToken", ctx, tokenHash)}
}

func (_c *Repository_ConsumeEmailVerificationToken_Call) Run(run func(ctx context.Context, tokenHash string)) *Repository_ConsumeEmailVerificationToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Repository_ConsumeEmailVerificationToken_Call) Return(_a0 uuid.UUID, _a1 error) *Repository_ConsumeEmailVerificationToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_ConsumeEmailVerificationToken_Call) RunAndReturn(run func(context.Context, string) (uuid.UUID, error)) *Repository_ConsumeEmailVerificationToken_Call {
	_c.Call.Return(run)
	return _c
}

// ConsumePasswordResetToken provides a mock function with given fields: ctx, tokenHash
func (_m *Repository) ConsumePasswordResetToken(ctx context.Context, tokenHash string) (uuid.UUID, error) {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for ConsumePasswordResetToken")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (uuid.UUID, error)); ok {
		return rf(ctx, tokenHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) uuid.UUID); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_ConsumePasswordResetToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConsumePasswordResetToken'
type Repository_ConsumePasswordResetToken_Call struct {
	*mock.Call
}

// ConsumePasswordResetToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *Repository_Expecter) ConsumePasswordResetToken(ctx interface{}, tokenHash interface{}) *Repository_ConsumePasswordResetToken_Call {
	return &Repository_ConsumePasswordResetToken_Call{Call: _e.mock.On("ConsumePasswordResetToken", ctx, tokenHash)}
}

func (_c *Repository_ConsumePasswordResetToken_Call) Run(run func(ctx context.Context, tokenHash string)) *Repository_ConsumePasswordResetToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Repository_ConsumePasswordResetToken_Call) Return(_a0 uuid.UUID, _a1 error) *Repository_ConsumePasswordResetToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_ConsumePasswordResetToken_Call) RunAndReturn(run func(context.Context, string) (uuid.UUID, error)) *Repository_ConsumePasswordResetToken_Call {
	_c.Call.Return(run)
	return _c
}

// CreateEmailVerificationToken provides a mock function with given fields: ctx, userID, tokenHash, expiresAt
func (_m *Repository) CreateEmailVerificationToken(ctx context.Context, userID uuid.UUID, tokenHash string, expiresAt time.Time) error {
	ret := _m.Called(ctx, userID, tokenHash, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for CreateEmailVerificationToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, time.Time) error); ok {
		r0 = rf(ctx, userID, tokenHash, expiresAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_CreateEmailVerificationToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateEmailVerificationToken'
type Repository_CreateEmailVerificationToken_Call struct {
	*mock.Call
}

// CreateEmailVerificationToken is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - tokenHash string
//   - expiresAt time.Time
func (_e *Repository_Expecter) CreateEmailVerificationToken(ctx interface{}, userID interface{}, tokenHash interface{}, expiresAt interface{}) *Repository_CreateEmailVerificationToken_Call {
	return &Repository_CreateEmailVerificationToken_Call{Call: _e.mock.On("CreateEmailVerificationToken", ctx, userID, tokenHash, expiresAt)}
}

func (_c *Repository_CreateEmailVerificationToken_Call) Run(run func(ctx context.Context, userID uuid.UUID, tokenHash string, expiresAt time.Time)) *Repository_CreateEmailVerificationToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(time.Time))
	})
	return _c
}

func (_c *Repository_CreateEmailVerificationToken_Call) Return(_a0 error) *Repository_CreateEmailVerificationToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_CreateEmailVerificationToken_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, time.Time) error) *Repository_CreateEmailVerificationToken_Call {
	_c.Call.Return(run)
	return _c
}

// CreateGoogleUser provides a mock function with given fields: ctx, email, subject
func (_m *Repository) CreateGoogleUser(ctx context.Context, email string, subject string) (domain.User, error) {
	ret := _m.Called(ctx, email, subject)

	if len(ret) == 0 {
		panic("no return value specified for CreateGoogleUser")
	}

	var r0 domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (domain.User, error)); ok {
		return rf(ctx, email, subject)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) domain.User); ok {
		r0 = rf(ctx, email, subject)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, email, subject)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_CreateGoogleUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateGoogleUser'
type Repository_CreateGoogleUser_Call struct {
	*mock.Call
}

// CreateGoogleUser is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - subject string
func (_e *Repository_Expecter) CreateGoogleUser(ctx interface{}, email interface{}, subject interface{}) *Repository_CreateGoogleUser_Call {
	return &Repository_CreateGoogleUser_Call{Call: _e.mock.On("CreateGoogleUser", ctx, email, subject)}
}

func (_c *Repository_CreateGoogleUser_Call) Run(run func(ctx context.Context, email string, subject string)) *Repository_CreateGoogleUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Repository_CreateGoogleUser_Call) Return(_a0 domain.User, _a1 error) *Repository_CreateGoogleUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_CreateGoogleUser_Call) RunAndReturn(run func(context.Context, string, string) (domain.User, error)) *Repository_CreateGoogleUser_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePasswordResetToken provides a mock function with given fields: ctx, userID, tokenHash, expiresAt
func (_m *Repository) CreatePasswordResetToken(ctx context.Context, userID uuid.UUID, tokenHash string, expiresAt time.Time) error {
	ret := _m.Called(ctx, userID, tokenHash, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for CreatePasswordResetToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, time.Time) error); ok {
		r0 = rf(ctx, userID, tokenHash, expiresAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_CreatePasswordResetToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePasswordResetToken'
type Repository_CreatePasswordResetToken_Call struct {
	*mock.Call
}

// CreatePasswordResetToken is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - tokenHash string
//   - expiresAt time.Time
func (_e *Repository_Expecter) CreatePasswordResetToken(ctx interface{}, userID interface{}, tokenHash interface{}, expiresAt interface{}) *Repository_CreatePasswordResetToken_Call {
	return &Repository_CreatePasswordResetToken_Call{Call: _e.mock.On("CreatePasswordResetToken", ctx, userID, tokenHash, expiresAt)}
}

func (_c *Repository_CreatePasswordResetToken_Call) Run(run func(ctx context.Context, userID uuid.UUID, tokenHash string, expiresAt time.Time)) *Repository_CreatePasswordResetToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(time.Time))
	})
	return _c
}

func (_c *Repository_CreatePasswordResetToken_Call) Return(_a0 error) *Repository_CreatePasswordResetToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_CreatePasswordResetToken_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, time.Time) error) *Repository_CreatePasswordResetToken_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSession provides a mock function with given fields: ctx, session
func (_m *Repository) CreateSession(ctx context.Context, session domain.NewSession) (domain.SessionRecord, error) {
	ret := _m.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 domain.SessionRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.NewSession) (domain.SessionRecord, error)); ok {
		return rf(ctx, session)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.NewSession) domain.SessionRecord); ok {
		r0 = rf(ctx, session)
	} else {
		r0 = ret.Get(0).(domain.SessionRecord)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.NewSession) error); ok {
		r1 = rf(ctx, session)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type Repository_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - session domain.NewSession
func (_e *Repository_Expecter) CreateSession(ctx interface{}, session interface{}) *Repository_CreateSession_Call {
	return &Repository_CreateSession_Call{Call: _e.mock.On("CreateSession", ctx, session)}
}

func (_c *Repository_CreateSession_Call) Run(run func(ctx context.Context, session domain.NewSession)) *Repository_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.NewSession))
	})
	return _c
}

func (_c *Repository_CreateSession_Call) Return(_a0 domain.SessionRecord, _a1 error) *Repository_CreateSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_CreateSession_Call) RunAndReturn(run func(context.Context, domain.NewSession) (domain.SessionRecord, error)) *Repository_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function with given fields: ctx, email, passwordHash
func (_m *Repository) CreateUser(ctx context.Context, email string, passwordHash string) (domain.User, error) {
	ret := _m.Called(ctx, email, passwordHash)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (domain.User, error)); ok {
		return rf(ctx, email, passwordHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) domain.User); ok {
		r0 = rf(ctx, email, passwordHash)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, email, passwordHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type Repository_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - passwordHash string
func (_e *Repository_Expecter) CreateUser(ctx interface{}, email interface{}, passwordHash interface{}) *Repository_CreateUser_Call {
	return &Repository_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, email, passwordHash)}
}

func (_c *Repository_CreateUser_Call) Run(run func(ctx context.Context, email string, passwordHash string)) *Repository_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Repository_CreateUser_Call) Return(_a0 domain.User, _a1 error) *Repository_CreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_CreateUser_Call) RunAndReturn(run func(context.Context, string, string) (domain.User, error)) *Repository_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// LinkGoogleSubject provides a mock function with given fields: ctx, userID, subject
func (_m *Repository) LinkGoogleSubject(ctx context.Context, userID uuid.UUID, subject string) (domain.User, error) {
	ret := _m.Called(ctx, userID, subject)

	if len(ret) == 0 {
		panic("no return value specified for LinkGoogleSubject")
	}

	var r0 domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (domain.User, error)); ok {
		return rf(ctx, userID, subject)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) domain.User); ok {
		r0 = rf(ctx, userID, subject)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, userID, subject)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_LinkGoogleSubject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LinkGoogleSubject'
type Repository_LinkGoogleSubject_Call struct {
	*mock.Call
}

// LinkGoogleSubject is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - subject string
func (_e *Repository_Expecter) LinkGoogleSubject(ctx interface{}, userID interface{}, subject interface{}) *Repository_LinkGoogleSubject_Call {
	return &Repository_LinkGoogleSubject_Call{Call: _e.mock.On("LinkGoogleSubject", ctx, userID, subject)}
}

func (_c *Repository_LinkGoogleSubject_Call) Run(run func(ctx context.Context, userID uuid.UUID, subject string)) *Repository_LinkGoogleSubject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *Repository_LinkGoogleSubject_Call) Return(_a0 domain.User, _a1 error) *Repository_LinkGoogleSubject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_LinkGoogleSubject_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) (domain.User, error)) *Repository_LinkGoogleSubject_Call {
	_c.Call.Return(run)
	return _c
}

// MarkEmailVerified provides a mock function with given fields: ctx, userID
func (_m *Repository) MarkEmailVerified(ctx context.Context, userID uuid.UUID) (domain.User, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkEmailVerified")
	}

	var r0 domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.User, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.User); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_MarkEmailVerified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkEmailVerified'
type Repository_MarkEmailVerified_Call struct {
	*mock.Call
}

// MarkEmailVerified is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *Repository_Expecter) MarkEmailVerified(ctx interface{}, userID interface{}) *Repository_MarkEmailVerified_Call {
	return &Repository_MarkEmailVerified_Call{Call: _e.mock.On("MarkEmailVerified", ctx, userID)}
}

func (_c *Repository_MarkEmailVerified_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *Repository_MarkEmailVerified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *Repository_MarkEmailVerified_Call) Return(_a0 domain.User, _a1 error) *Repository_MarkEmailVerified_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_MarkEmailVerified_Call) RunAndReturn(run func(context.Context, uuid.UUID) (domain.User, error)) *Repository_MarkEmailVerified_Call {
	_c.Call.Return(run)
	return _c
}

// MarkOnboarded provides a mock function with given fields: ctx, userID
func (_m *Repository) MarkOnboarded(ctx context.Context, userID uuid.UUID) (domain.User, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkOnboarded")
	}

	var r0 domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.User, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.User); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_MarkOnboarded_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkOnboarded'
type Repository_MarkOnboarded_Call struct {
	*mock.Call
}

// MarkOnboarded is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *Repository_Expecter) MarkOnboarded(ctx interface{}, userID interface{}) *Repository_MarkOnboarded_Call {
	return &Repository_MarkOnboarded_Call{Call: _e.mock.On("MarkOnboarded", ctx, userID)}
}

func (_c *Repository_MarkOnboarded_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *Repository_MarkOnboarded_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *Repository_MarkOnboarded_Call) Return(_a0 domain.User, _a1 error) *Repository_MarkOnboarded_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_MarkOnboarded_Call) RunAndReturn(run func(context.Context, uuid.UUID) (domain.User, error)) *Repository_MarkOnboarded_Call {
	_c.Call.Return(run)
	return _c
}

// PasswordHash provides a mock function with given fields: ctx, userID
func (_m *Repository) PasswordHash(ctx context.Context, userID uuid.UUID) (string, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for PasswordHash")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (string, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) string); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_PasswordHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PasswordHash'
type Repository_PasswordHash_Call struct {
	*mock.Call
}

// PasswordHash is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *Repository_Expecter) PasswordHash(ctx interface{}, userID interface{}) *Repository_PasswordHash_Call {
	return &Repository_PasswordHash_Call{Call: _e.mock.On("PasswordHash", ctx, userID)}
}

func (_c *Repository_PasswordHash_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *Repository_PasswordHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *Repository_PasswordHash_Call) Return(_a0 string, _a1 error) *Repository_PasswordHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_PasswordHash_Call) RunAndReturn(run func(context.Context, uuid.UUID) (string, error)) *Repository_PasswordHash_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeSession provides a mock function with given fields: ctx, id
func (_m *Repository) RevokeSession(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for RevokeSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_RevokeSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeSession'
type Repository_RevokeSession_Call struct {
	*mock.Call
}

// RevokeSession is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *Repository_Expecter) RevokeSession(ctx interface{}, id interface{}) *Repository_RevokeSession_Call {
	return &Repository_RevokeSession_Call{Call: _e.mock.On("RevokeSession", ctx, id)}
}

func (_c *Repository_RevokeSession_Call) Run(run func(ctx context.Context, id uuid.UUID)) *Repository_RevokeSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *Repository_RevokeSession_Call) Return(_a0 error) *Repository_RevokeSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_RevokeSession_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *Repository_RevokeSession_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeSessionByTokenHash provides a mock function with given fields: ctx, tokenHash
func (_m *Repository) RevokeSessionByTokenHash(ctx context.Context, tokenHash string) error {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for RevokeSessionByTokenHash")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_RevokeSessionByTokenHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeSessionByTokenHash'
type Repository_RevokeSessionByTokenHash_Call struct {
	*mock.Call
}

// RevokeSessionByTokenHash is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *Repository_Expecter) RevokeSessionByTokenHash(ctx interface{}, tokenHash interface{}) *Repository_RevokeSessionByTokenHash_Call {
	return &Repository_RevokeSessionByTokenHash_Call{Call: _e.mock.On("RevokeSessionByTokenHash", ctx, tokenHash)}
}

func (_c *Repository_RevokeSessionByTokenHash_Call) Run(run func(ctx context.Context, tokenHash string)) *Repository_RevokeSessionByTokenHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Repository_RevokeSessionByTokenHash_Call) Return(_a0 error) *Repository_RevokeSessionByTokenHash_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_RevokeSessionByTokenHash_Call) RunAndReturn(run func(context.Context, string) error) *Repository_RevokeSessionByTokenHash_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeSessionsForUser provides a mock function with given fields: ctx, userID
func (_m *Repository) RevokeSessionsForUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeSessionsForUser")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int64, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int64); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_RevokeSessionsForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeSessionsForUser'
type Repository_RevokeSessionsForUser_Call struct {
	*mock.Call
}

// RevokeSessionsForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *Repository_Expecter) RevokeSessionsForUser(ctx interface{}, userID interface{}) *Repository_RevokeSessionsForUser_Call {
	return &Repository_RevokeSessionsForUser_Call{Call: _e.mock.On("RevokeSessionsForUser", ctx, userID)}
}

func (_c *Repository_RevokeSessionsForUser_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *Repository_RevokeSessionsForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *Repository_RevokeSessionsForUser_Call) Return(_a0 int64, _a1 error) *Repository_RevokeSessionsForUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_RevokeSessionsForUser_Call) RunAndReturn(run func(context.Context, uuid.UUID) (int64, error)) *Repository_RevokeSessionsForUser_Call {
	_c.Call.Return(run)
	return _c
}

// SessionByID provides a mock function with given fields: ctx, id
func (_m *Repository) SessionByID(ctx context.Context, id uuid.UUID) (domain.SessionRecord, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for SessionByID")
	}

	var r0 domain.SessionRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.SessionRecord, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.SessionRecord); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.SessionRecord)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_SessionByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SessionByID'
type Repository_SessionByID_Call struct {
	*mock.Call
}

// SessionByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *Repository_Expecter) SessionByID(ctx interface{}, id interface{}) *Repository_SessionByID_Call {
	return &Repository_SessionByID_Call{Call: _e.mock.On("SessionByID", ctx, id)}
}

func (_c *Repository_SessionByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *Repository_SessionByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *Repository_SessionByID_Call) Return(_a0 domain.SessionRecord, _a1 error) *Repository_SessionByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_SessionByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (domain.SessionRecord, error)) *Repository_SessionByID_Call {
	_c.Call.Return(run)
	return _c
}

// SessionByTokenHash provides a mock function with given fields: ctx, tokenHash
func (_m *Repository) SessionByTokenHash(ctx context.Context, tokenHash string) (domain.SessionRecord, error) {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for SessionByTokenHash")
	}

	var r0 domain.SessionRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.SessionRecord, error)); ok {
		return rf(ctx, tokenHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.SessionRecord); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		r0 = ret.Get(0).(domain.SessionRecord)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_SessionByTokenHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SessionByTokenHash'
type Repository_SessionByTokenHash_Call struct {
	*mock.Call
}

// SessionByTokenHash is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *Repository_Expecter) SessionByTokenHash(ctx interface{}, tokenHash interface{}) *Repository_SessionByTokenHash_Call {
	return &Repository_SessionByTokenHash_Call{Call: _e.mock.On("SessionByTokenHash", ctx, tokenHash)}
}

func (_c *Repository_SessionByTokenHash_Call) Run(run func(ctx context.Context, tokenHash string)) *Repository_SessionByTokenHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Repository_SessionByTokenHash_Call) Return(_a0 domain.SessionRecord, _a1 error) *Repository_SessionByTokenHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_SessionByTokenHash_Call) RunAndReturn(run func(context.Context, string) (domain.SessionRecord, error)) *Repository_SessionByTokenHash_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePasswordHash provides a mock function with given fields: ctx, userID, hash
func (_m *Repository) UpdatePasswordHash(ctx context.Context, userID uuid.UUID, hash string) (domain.User, error) {
	ret := _m.Called(ctx, userID, hash)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePasswordHash")
	}

	var r0 domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (domain.User, error)); ok {
		return rf(ctx, userID, hash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) domain.User); ok {
		r0 = rf(ctx, userID, hash)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, userID, hash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_UpdatePasswordHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePasswordHash'
type Repository_UpdatePasswordHash_Call struct {
	*mock.Call
}

// UpdatePasswordHash is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - hash string
func (_e *Repository_Expecter) UpdatePasswordHash(ctx interface{}, userID interface{}, hash interface{}) *Repository_UpdatePasswordHash_Call {
	return &Repository_UpdatePasswordHash_Call{Call: _e.mock.On("UpdatePasswordHash", ctx, userID, hash)}
}

func (_c *Repository_UpdatePasswordHash_Call) Run(run func(ctx context.Context, userID uuid.UUID, hash string)) *Repository_UpdatePasswordHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *Repository_UpdatePasswordHash_Call) Return(_a0 domain.User, _a1 error) *Repository_UpdatePasswordHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_UpdatePasswordHash_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) (domain.User, error)) *Repository_UpdatePasswordHash_Call {
	_c.Call.Return(run)
	return _c
}

// UserByEmail provides a mock function with given fields: ctx, email
func (_m *Repository) UserByEmail(ctx context.Context, email string) (domain.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for UserByEmail")
	}

	var r0 domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.User); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_UserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserByEmail'
type Repository_UserByEmail_Call struct {
	*mock.Call
}

// UserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *Repository_Expecter) UserByEmail(ctx interface{}, email interface{}) *Repository_UserByEmail_Call {
	return &Repository_UserByEmail_Call{Call: _e.mock.On("UserByEmail", ctx, email)}
}

func (_c *Repository_UserByEmail_Call) Run(run func(ctx context.Context, email string)) *Repository_UserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Repository_UserByEmail_Call) Return(_a0 domain.User, _a1 error) *Repository_UserByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_UserByEmail_Call) RunAndReturn(run func(context.Context, string) (domain.User, error)) *Repository_UserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// UserByGoogleSubject provides a mock function with given fields: ctx, subject
func (_m *Repository) UserByGoogleSubject(ctx context.Context, subject string) (domain.User, error) {
	ret := _m.Called(ctx, subject)

	if len(ret) == 0 {
		panic("no return value specified for UserByGoogleSubject")
	}

	var r0 domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.User, error)); ok {
		return rf(ctx, subject)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.User); ok {
		r0 = rf(ctx, subject)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, subject)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_UserByGoogleSubject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserByGoogleSubject'
type Repository_UserByGoogleSubject_Call struct {
	*mock.Call
}

// UserByGoogleSubject is a helper method to define mock.On call
//   - ctx context.Context
//   - subject string
func (_e *Repository_Expecter) UserByGoogleSubject(ctx interface{}, subject interface{}) *Repository_UserByGoogleSubject_Call {
	return &Repository_UserByGoogleSubject_Call{Call: _e.mock.On("UserByGoogleSubject", ctx, subject)}
}

func (_c *Repository_UserByGoogleSubject_Call) Run(run func(ctx context.Context, subject string)) *Repository_UserByGoogleSubject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Repository_UserByGoogleSubject_Call) Return(_a0 domain.User, _a1 error) *Repository_UserByGoogleSubject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_UserByGoogleSubject_Call) RunAndReturn(run func(context.Context, string) (domain.User, error)) *Repository_UserByGoogleSubject_Call {
	_c.Call.Return(run)
	return _c
}

// UserByID provides a mock function with given fields: ctx, id
func (_m *Repository) UserByID(ctx context.Context, id uuid.UUID) (domain.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for UserByID")
	}

	var r0 domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.User); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_UserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserByID'
type Repository_UserByID_Call struct {
	*mock.Call
}

// UserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *Repository_Expecter) UserByID(ctx interface{}, id interface{}) *Repository_UserByID_Call {
	return &Repository_UserByID_Call{Call: _e.mock.On("UserByID", ctx, id)}
}

func (_c *Repository_UserByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *Repository_UserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *Repository_UserByID_Call) Return(_a0 domain.User, _a1 error) *Repository_UserByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_UserByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (domain.User, error)) *Repository_UserByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
