// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/robzlabz/employeebot/apps/backend/internal/modules/auth/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// AssertVerified provides a mock function with given fields: ctx, userID
func (_m *Service) AssertVerified(ctx context.Context, userID uuid.UUID) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for AssertVerified")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_AssertVerified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssertVerified'
type Service_AssertVerified_Call struct {
	*mock.Call
}

// AssertVerified is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *Service_Expecter) AssertVerified(ctx interface{}, userID interface{}) *Service_AssertVerified_Call {
	return &Service_AssertVerified_Call{Call: _e.mock.On("AssertVerified", ctx, userID)}
}

func (_c *Service_AssertVerified_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *Service_AssertVerified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *Service_AssertVerified_Call) Return(_a0 error) *Service_AssertVerified_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_AssertVerified_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *Service_AssertVerified_Call {
	_c.Call.Return(run)
	return _c
}

// Authenticate provides a mock function with given fields: ctx, accessToken
func (_m *Service) Authenticate(ctx context.Context, accessToken string) (domain.User, error) {
	ret := _m.Called(ctx, accessToken)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.User, error)); ok {
		return rf(ctx, accessToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.User); ok {
		r0 = rf(ctx, accessToken)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, accessToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type Service_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
func (_e *Service_Expecter) Authenticate(ctx interface{}, accessToken interface{}) *Service_Authenticate_Call {
	return &Service_Authenticate_Call{Call: _e.mock.On("Authenticate", ctx, accessToken)}
}

func (_c *Service_Authenticate_Call) Run(run func(ctx context.Context, accessToken string)) *Service_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Service_Authenticate_Call) Return(_a0 domain.User, _a1 error) *Service_Authenticate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_Authenticate_Call) RunAndReturn(run func(context.Context, string) (domain.User, error)) *Service_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}

// CurrentUser provides a mock function with given fields: ctx, userID
func (_m *Service) CurrentUser(ctx context.Context, userID uuid.UUID) (domain.User, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CurrentUser")
	}

	var r0 domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.User, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.User); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_CurrentUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CurrentUser'
type Service_CurrentUser_Call struct {
	*mock.Call
}

// CurrentUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *Service_Expecter) CurrentUser(ctx interface{}, userID interface{}) *Service_CurrentUser_Call {
	return &Service_CurrentUser_Call{Call: _e.mock.On("CurrentUser", ctx, userID)}
}

func (_c *Service_CurrentUser_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *Service_CurrentUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *Service_CurrentUser_Call) Return(_a0 domain.User, _a1 error) *Service_CurrentUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_CurrentUser_Call) RunAndReturn(run func(context.Context, uuid.UUID) (domain.User, error)) *Service_CurrentUser_Call {
	_c.Call.Return(run)
	return _c
}

// GoogleAuthURL provides a mock function with given fields: ctx
func (_m *Service) GoogleAuthURL(ctx context.Context) (string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GoogleAuthURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_GoogleAuthURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GoogleAuthURL'
type Service_GoogleAuthURL_Call struct {
	*mock.Call
}

// GoogleAuthURL is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Service_Expecter) GoogleAuthURL(ctx interface{}) *Service_GoogleAuthURL_Call {
	return &Service_GoogleAuthURL_Call{Call: _e.mock.On("GoogleAuthURL", ctx)}
}

func (_c *Service_GoogleAuthURL_Call) Run(run func(ctx context.Context)) *Service_GoogleAuthURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Service_GoogleAuthURL_Call) Return(_a0 string, _a1 error) *Service_GoogleAuthURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_GoogleAuthURL_Call) RunAndReturn(run func(context.Context) (string, error)) *Service_GoogleAuthURL_Call {
	_c.Call.Return(run)
	return _c
}

// GoogleCallback provides a mock function with given fields: ctx, req
func (_m *Service) GoogleCallback(ctx context.Context, req domain.GoogleCallbackRequest) (domain.Session, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GoogleCallback")
	}

	var r0 domain.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.GoogleCallbackRequest) (domain.Session, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.GoogleCallbackRequest) domain.Session); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(domain.Session)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.GoogleCallbackRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_GoogleCallback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GoogleCallback'
type Service_GoogleCallback_Call struct {
	*mock.Call
}

// GoogleCallback is a helper method to define mock.On call
//   - ctx context.Context
//   - req domain.GoogleCallbackRequest
func (_e *Service_Expecter) GoogleCallback(ctx interface{}, req interface{}) *Service_GoogleCallback_Call {
	return &Service_GoogleCallback_Call{Call: _e.mock.On("GoogleCallback", ctx, req)}
}

func (_c *Service_GoogleCallback_Call) Run(run func(ctx context.Context, req domain.GoogleCallbackRequest)) *Service_GoogleCallback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.GoogleCallbackRequest))
	})
	return _c
}

func (_c *Service_GoogleCallback_Call) Return(_a0 domain.Session, _a1 error) *Service_GoogleCallback_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_GoogleCallback_Call) RunAndReturn(run func(context.Context, domain.GoogleCallbackRequest) (domain.Session, error)) *Service_GoogleCallback_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function with given fields: ctx, req
func (_m *Service) Login(ctx context.Context, req domain.LoginRequest) (domain.Session, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 domain.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.LoginRequest) (domain.Session, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.LoginRequest) domain.Session); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(domain.Session)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.LoginRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type Service_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - req domain.LoginRequest
func (_e *Service_Expecter) Login(ctx interface{}, req interface{}) *Service_Login_Call {
	return &Service_Login_Call{Call: _e.mock.On("Login", ctx, req)}
}

func (_c *Service_Login_Call) Run(run func(ctx context.Context, req domain.LoginRequest)) *Service_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.LoginRequest))
	})
	return _c
}

func (_c *Service_Login_Call) Return(_a0 domain.Session, _a1 error) *Service_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_Login_Call) RunAndReturn(run func(context.Context, domain.LoginRequest) (domain.Session, error)) *Service_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function with given fields: ctx, refreshToken
func (_m *Service) Logout(ctx context.Context, refreshToken string) error {
	ret := _m.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, refreshToken)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type Service_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *Service_Expecter) Logout(ctx interface{}, refreshToken interface{}) *Service_Logout_Call {
	return &Service_Logout_Call{Call: _e.mock.On("Logout", ctx, refreshToken)}
}

func (_c *Service_Logout_Call) Run(run func(ctx context.Context, refreshToken string)) *Service_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Service_Logout_Call) Return(_a0 error) *Service_Logout_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_Logout_Call) RunAndReturn(run func(context.Context, string) error) *Service_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// Refresh provides a mock function with given fields: ctx, refreshToken
func (_m *Service) Refresh(ctx context.Context, refreshToken string) (domain.Session, error) {
	ret := _m.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 domain.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Session, error)); ok {
		return rf(ctx, refreshToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Session); ok {
		r0 = rf(ctx, refreshToken)
	} else {
		r0 = ret.Get(0).(domain.Session)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type Service_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *Service_Expecter) Refresh(ctx interface{}, refreshToken interface{}) *Service_Refresh_Call {
	return &Service_Refresh_Call{Call: _e.mock.On("Refresh", ctx, refreshToken)}
}

func (_c *Service_Refresh_Call) Run(run func(ctx context.Context, refreshToken string)) *Service_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Service_Refresh_Call) Return(_a0 domain.Session, _a1 error) *Service_Refresh_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_Refresh_Call) RunAndReturn(run func(context.Context, string) (domain.Session, error)) *Service_Refresh_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: ctx, req
func (_m *Service) Register(ctx context.Context, req domain.RegisterRequest) (domain.User, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.RegisterRequest) (domain.User, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.RegisterRequest) domain.User); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.RegisterRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type Service_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - req domain.RegisterRequest
func (_e *Service_Expecter) Register(ctx interface{}, req interface{}) *Service_Register_Call {
	return &Service_Register_Call{Call: _e.mock.On("Register", ctx, req)}
}

func (_c *Service_Register_Call) Run(run func(ctx context.Context, req domain.RegisterRequest)) *Service_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.RegisterRequest))
	})
	return _c
}

func (_c *Service_Register_Call) Return(_a0 domain.User, _a1 error) *Service_Register_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_Register_Call) RunAndReturn(run func(context.Context, domain.RegisterRequest) (domain.User, error)) *Service_Register_Call {
	_c.Call.Return(run)
	return _c
}

// RequestPasswordReset provides a mock function with given fields: ctx, email
func (_m *Service) RequestPasswordReset(ctx context.Context, email string) error {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for RequestPasswordReset")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_RequestPasswordReset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestPasswordReset'
type Service_RequestPasswordReset_Call struct {
	*mock.Call
}

// RequestPasswordReset is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *Service_Expecter) RequestPasswordReset(ctx interface{}, email interface{}) *Service_RequestPasswordReset_Call {
	return &Service_RequestPasswordReset_Call{Call: _e.mock.On("RequestPasswordReset", ctx, email)}
}

func (_c *Service_RequestPasswordReset_Call) Run(run func(ctx context.Context, email string)) *Service_RequestPasswordReset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Service_RequestPasswordReset_Call) Return(_a0 error) *Service_RequestPasswordReset_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_RequestPasswordReset_Call) RunAndReturn(run func(context.Context, string) error) *Service_RequestPasswordReset_Call {
	_c.Call.Return(run)
	return _c
}

// ResendVerification provides a mock function with given fields: ctx, email
func (_m *Service) ResendVerification(ctx context.Context, email string) error {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for ResendVerification")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_ResendVerification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResendVerification'
type Service_ResendVerification_Call struct {
	*mock.Call
}

// ResendVerification is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *Service_Expecter) ResendVerification(ctx interface{}, email interface{}) *Service_ResendVerification_Call {
	return &Service_ResendVerification_Call{Call: _e.mock.On("ResendVerification", ctx, email)}
}

func (_c *Service_ResendVerification_Call) Run(run func(ctx context.Context, email string)) *Service_ResendVerification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Service_ResendVerification_Call) Return(_a0 error) *Service_ResendVerification_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_ResendVerification_Call) RunAndReturn(run func(context.Context, string) error) *Service_ResendVerification_Call {
	_c.Call.Return(run)
	return _c
}

// ResetPassword provides a mock function with given fields: ctx, req
func (_m *Service) ResetPassword(ctx context.Context, req domain.ResetPasswordRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ResetPassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ResetPasswordRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_ResetPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetPassword'
type Service_ResetPassword_Call struct {
	*mock.Call
}

// ResetPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - req domain.ResetPasswordRequest
func (_e *Service_Expecter) ResetPassword(ctx interface{}, req interface{}) *Service_ResetPassword_Call {
	return &Service_ResetPassword_Call{Call: _e.mock.On("ResetPassword", ctx, req)}
}

func (_c *Service_ResetPassword_Call) Run(run func(ctx context.Context, req domain.ResetPasswordRequest)) *Service_ResetPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.ResetPasswordRequest))
	})
	return _c
}

func (_c *Service_ResetPassword_Call) Return(_a0 error) *Service_ResetPassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_ResetPassword_Call) RunAndReturn(run func(context.Context, domain.ResetPasswordRequest) error) *Service_ResetPassword_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyEmail provides a mock function with given fields: ctx, token
func (_m *Service) VerifyEmail(ctx context.Context, token string) (domain.User, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for VerifyEmail")
	}

	var r0 domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.User, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.User); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_VerifyEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyEmail'
type Service_VerifyEmail_Call struct {
	*mock.Call
}

// VerifyEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *Service_Expecter) VerifyEmail(ctx interface{}, token interface{}) *Service_VerifyEmail_Call {
	return &Service_VerifyEmail_Call{Call: _e.mock.On("VerifyEmail", ctx, token)}
}

func (_c *Service_VerifyEmail_Call) Run(run func(ctx context.Context, token string)) *Service_VerifyEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Service_VerifyEmail_Call) Return(_a0 domain.User, _a1 error) *Service_VerifyEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_VerifyEmail_Call) RunAndReturn(run func(context.Context, string) (domain.User, error)) *Service_VerifyEmail_Call {
	_c.Call.Return(run)
	return _c
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
