// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// StateSigner is an autogenerated mock type for the StateSigner type
type StateSigner struct {
	mock.Mock
}

type StateSigner_Expecter struct {
	mock *mock.Mock
}

func (_m *StateSigner) EXPECT() *StateSigner_Expecter {
	return &StateSigner_Expecter{mock: &_m.Mock}
}

// Sign provides a mock function with no fields
func (_m *StateSigner) Sign() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Sign")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StateSigner_Sign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sign'
type StateSigner_Sign_Call struct {
	*mock.Call
}

// Sign is a helper method to define mock.On call
func (_e *StateSigner_Expecter) Sign() *StateSigner_Sign_Call {
	return &StateSigner_Sign_Call{Call: _e.mock.On("Sign")}
}

func (_c *StateSigner_Sign_Call) Run(run func()) *StateSigner_Sign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *StateSigner_Sign_Call) Return(_a0 string, _a1 error) *StateSigner_Sign_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StateSigner_Sign_Call) RunAndReturn(run func() (string, error)) *StateSigner_Sign_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function with given fields: state
func (_m *StateSigner) Verify(state string) error {
	ret := _m.Called(state)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(state)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StateSigner_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type StateSigner_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - state string
func (_e *StateSigner_Expecter) Verify(state interface{}) *StateSigner_Verify_Call {
	return &StateSigner_Verify_Call{Call: _e.mock.On("Verify", state)}
}

func (_c *StateSigner_Verify_Call) Run(run func(state string)) *StateSigner_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *StateSigner_Verify_Call) Return(_a0 error) *StateSigner_Verify_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StateSigner_Verify_Call) RunAndReturn(run func(string) error) *StateSigner_Verify_Call {
	_c.Call.Return(run)
	return _c
}

// NewStateSigner creates a new instance of StateSigner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStateSigner(t interface {
	mock.TestingT
	Cleanup(func())
}) *StateSigner {
	mock := &StateSigner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
