// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/robzlabz/employeebot/apps/backend/internal/modules/auth/domain"
	mock "github.com/stretchr/testify/mock"
)

// LoginThrottle is an autogenerated mock type for the LoginThrottle type
type LoginThrottle struct {
	mock.Mock
}

type LoginThrottle_Expecter struct {
	mock *mock.Mock
}

func (_m *LoginThrottle) EXPECT() *LoginThrottle_Expecter {
	return &LoginThrottle_Expecter{mock: &_m.Mock}
}

// Allow provides a mock function with given fields: ctx, key, capacity, refill
func (_m *LoginThrottle) Allow(ctx context.Context, key string, capacity int, refill float64) (domain.ThrottleResult, error) {
	ret := _m.Called(ctx, key, capacity, refill)

	if len(ret) == 0 {
		panic("no return value specified for Allow")
	}

	var r0 domain.ThrottleResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, float64) (domain.ThrottleResult, error)); ok {
		return rf(ctx, key, capacity, refill)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, float64) domain.ThrottleResult); ok {
		r0 = rf(ctx, key, capacity, refill)
	} else {
		r0 = ret.Get(0).(domain.ThrottleResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, float64) error); ok {
		r1 = rf(ctx, key, capacity, refill)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoginThrottle_Allow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Allow'
type LoginThrottle_Allow_Call struct {
	*mock.Call
}

// Allow is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - capacity int
//   - refill float64
func (_e *LoginThrottle_Expecter) Allow(ctx interface{}, key interface{}, capacity interface{}, refill interface{}) *LoginThrottle_Allow_Call {
	return &LoginThrottle_Allow_Call{Call: _e.mock.On("Allow", ctx, key, capacity, refill)}
}

func (_c *LoginThrottle_Allow_Call) Run(run func(ctx context.Context, key string, capacity int, refill float64)) *LoginThrottle_Allow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(float64))
	})
	return _c
}

func (_c *LoginThrottle_Allow_Call) Return(_a0 domain.ThrottleResult, _a1 error) *LoginThrottle_Allow_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LoginThrottle_Allow_Call) RunAndReturn(run func(context.Context, string, int, float64) (domain.ThrottleResult, error)) *LoginThrottle_Allow_Call {
	_c.Call.Return(run)
	return _c
}

// Reset provides a mock function with given fields: ctx, key
func (_m *LoginThrottle) Reset(ctx context.Context, key string) error {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Reset")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LoginThrottle_Reset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reset'
type LoginThrottle_Reset_Call struct {
	*mock.Call
}

// Reset is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *LoginThrottle_Expecter) Reset(ctx interface{}, key interface{}) *LoginThrottle_Reset_Call {
	return &LoginThrottle_Reset_Call{Call: _e.mock.On("Reset", ctx, key)}
}

func (_c *LoginThrottle_Reset_Call) Run(run func(ctx context.Context, key string)) *LoginThrottle_Reset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *LoginThrottle_Reset_Call) Return(_a0 error) *LoginThrottle_Reset_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LoginThrottle_Reset_Call) RunAndReturn(run func(context.Context, string) error) *LoginThrottle_Reset_Call {
	_c.Call.Return(run)
	return _c
}

// NewLoginThrottle creates a new instance of LoginThrottle. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLoginThrottle(t interface {
	mock.TestingT
	Cleanup(func())
}) *LoginThrottle {
	mock := &LoginThrottle{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
