// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: health.sql

package sqlcgen

import (
	"context"
)

const ping = `-- name: Ping :one
SELECT 1::int AS ok
`

// Proves the database is reachable. Kept as the health module's only query so
// the sqlc pipeline (generate + diff gate in CI) is exercised from day one.
func (q *Queries) Ping(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, ping)
	var ok int32
	err := row.Scan(&ok)
	return ok, err
}
