// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type ActivityEvent struct {
	ID             int64
	WorkspaceID    pgtype.UUID
	Type           string
	ActorAgentID   pgtype.UUID
	ActorUserID    pgtype.UUID
	ConversationID pgtype.UUID
	TaskID         pgtype.UUID
	DraftID        pgtype.UUID
	Payload        []byte
	CreatedAt      pgtype.Timestamptz
}

type Agent struct {
	ID           pgtype.UUID
	WorkspaceID  pgtype.UUID
	TeamID       pgtype.UUID
	Name         string
	Role         string
	Persona      string
	Tone         string
	Shape        string
	Color        string
	Status       string
	TemplateKey  string
	DefaultModel []byte
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type AgentGrant struct {
	ID            pgtype.UUID
	WorkspaceID   pgtype.UUID
	AgentID       pgtype.UUID
	IntegrationID pgtype.UUID
	Permission    string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type AgentTemplate struct {
	ID           pgtype.UUID
	Key          string
	Name         string
	Role         string
	Persona      string
	Tone         string
	Shape        string
	Color        string
	Tools        []byte
	Integrations []byte
	DefaultModel []byte
	SortOrder    int32
	CreatedAt    pgtype.Timestamptz
}

type ApprovalPolicy struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
	ActionKind  string
	Mode        string
	MaxAmount   *int64
	UpdatedBy   pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type AuditLog struct {
	ID           int64
	WorkspaceID  pgtype.UUID
	ActorUserID  pgtype.UUID
	ActorAgentID pgtype.UUID
	Action       string
	ObjectType   string
	ObjectID     string
	Metadata     []byte
	CreatedAt    pgtype.Timestamptz
}

type BillingInvoice struct {
	ID                pgtype.UUID
	WorkspaceID       pgtype.UUID
	SubscriptionID    pgtype.UUID
	Provider          string
	ProviderReference string
	AmountIdr         int64
	Status            string
	PeriodStart       pgtype.Timestamptz
	PeriodEnd         pgtype.Timestamptz
	PaidAt            pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type Conversation struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
	Kind        string
	Title       string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type ConversationParticipant struct {
	ID             pgtype.UUID
	WorkspaceID    pgtype.UUID
	ConversationID pgtype.UUID
	AgentID        pgtype.UUID
	UserID         pgtype.UUID
	CreatedAt      pgtype.Timestamptz
}

type Draft struct {
	ID             pgtype.UUID
	WorkspaceID    pgtype.UUID
	TaskID         pgtype.UUID
	AgentID        pgtype.UUID
	ActionKind     string
	Payload        []byte
	Status         string
	Revision       int32
	DecidedBy      pgtype.UUID
	DecidedAt      pgtype.Timestamptz
	DecisionNote   string
	SentAt         pgtype.Timestamptz
	IdempotencyKey string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type Integration struct {
	ID                    pgtype.UUID
	WorkspaceID           pgtype.UUID
	App                   string
	AccountLabel          string
	Status                string
	Scopes                []string
	AccessTokenEncrypted  []byte
	RefreshTokenEncrypted []byte
	TokenExpiresAt        pgtype.Timestamptz
	DataKeyWrapped        []byte
	DataKeyKmsKeyID       string
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

type KnowledgeItem struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
	AgentID     pgtype.UUID
	Source      string
	ChunkIndex  int32
	Content     string
	Embedding   *pgvector.Vector
	Status      string
	CreatedAt   pgtype.Timestamptz
}

type Member struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
	UserID      pgtype.UUID
	Role        string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Memory struct {
	ID              pgtype.UUID
	WorkspaceID     pgtype.UUID
	AgentID         pgtype.UUID
	Content         string
	Kind            string
	SourceMessageID pgtype.UUID
	Embedding       *pgvector.Vector
	Pinned          bool
	CreatedBy       string
	SupersededBy    pgtype.UUID
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type Message struct {
	ID             pgtype.UUID
	WorkspaceID    pgtype.UUID
	ConversationID pgtype.UUID
	AuthorAgentID  pgtype.UUID
	AuthorUserID   pgtype.UUID
	Blocks         []byte
	Attachments    []byte
	TaskID         pgtype.UUID
	CreatedAt      pgtype.Timestamptz
}

type Plan struct {
	ID              pgtype.UUID
	Key             string
	Name            string
	MonthlyPriceIdr int64
	TokenQuota      int64
	MaxAgents       int32
	MaxIntegrations int32
	MaxMembers      int32
	IsTrial         bool
	SortOrder       int32
	CreatedAt       pgtype.Timestamptz
}

type QuotaPeriod struct {
	ID               pgtype.UUID
	WorkspaceID      pgtype.UUID
	PeriodStart      pgtype.Timestamptz
	PeriodEnd        pgtype.Timestamptz
	TokensGranted    int64
	TokensUsed       int64
	Warning80SentAt  pgtype.Timestamptz
	Warning100SentAt pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type Routine struct {
	ID            pgtype.UUID
	WorkspaceID   pgtype.UUID
	AgentID       pgtype.UUID
	Name          string
	Kind          string
	Cron          string
	HourStart     *int32
	HourEnd       *int32
	TriggerSource string
	Instruction   string
	Enabled       bool
	ScheduleID    string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type RoutineRun struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
	RoutineID   pgtype.UUID
	TaskID      pgtype.UUID
	Status      string
	Summary     string
	StartedAt   pgtype.Timestamptz
	FinishedAt  pgtype.Timestamptz
}

type Subscription struct {
	ID                 pgtype.UUID
	WorkspaceID        pgtype.UUID
	PlanID             pgtype.UUID
	Status             string
	CurrentPeriodStart pgtype.Timestamptz
	CurrentPeriodEnd   pgtype.Timestamptz
	GraceUntil         pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type Task struct {
	ID             pgtype.UUID
	WorkspaceID    pgtype.UUID
	AgentID        pgtype.UUID
	ParentTaskID   pgtype.UUID
	ConversationID pgtype.UUID
	Trigger        string
	Title          string
	Status         string
	WorkflowID     string
	TemporalRunID  string
	StoppedReason  string
	Summary        string
	StepCount      int32
	InputTokens    int64
	OutputTokens   int64
	CostMicros     int64
	StartedAt      pgtype.Timestamptz
	FinishedAt     pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type TaskStep struct {
	ID           pgtype.UUID
	WorkspaceID  pgtype.UUID
	TaskID       pgtype.UUID
	Seq          int32
	Kind         string
	ToolName     string
	ToolLabel    string
	Input        []byte
	Output       []byte
	InputTokens  int32
	OutputTokens int32
	PrunedAt     pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

type Team struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
	Name        string
	Kind        string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type UsageLedger struct {
	ID               int64
	WorkspaceID      pgtype.UUID
	AgentID          pgtype.UUID
	TaskID           pgtype.UUID
	Provider         string
	Model            string
	Purpose          string
	InputTokens      int32
	OutputTokens     int32
	CacheReadTokens  int32
	CacheWriteTokens int32
	CostMicros       int64
	CreatedAt        pgtype.Timestamptz
}

type User struct {
	ID              pgtype.UUID
	Email           string
	PasswordHash    string
	EmailVerifiedAt pgtype.Timestamptz
	GoogleSubject   *string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type Workspace struct {
	ID             pgtype.UUID
	Name           string
	BusinessField  string
	Timezone       string
	Language       string
	WorkHoursStart pgtype.Time
	WorkHoursEnd   pgtype.Time
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}
