// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/robzlabz/employeebot/apps/backend/internal/modules/llm/domain"
	mock "github.com/stretchr/testify/mock"
)

// Resolver is an autogenerated mock type for the Resolver type
type Resolver struct {
	mock.Mock
}

type Resolver_Expecter struct {
	mock *mock.Mock
}

func (_m *Resolver) EXPECT() *Resolver_Expecter {
	return &Resolver_Expecter{mock: &_m.Mock}
}

// Default provides a mock function with no fields
func (_m *Resolver) Default() domain.ProviderConfig {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Default")
	}

	var r0 domain.ProviderConfig
	if rf, ok := ret.Get(0).(func() domain.ProviderConfig); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(domain.ProviderConfig)
	}

	return r0
}

// Resolver_Default_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Default'
type Resolver_Default_Call struct {
	*mock.Call
}

// Default is a helper method to define mock.On call
func (_e *Resolver_Expecter) Default() *Resolver_Default_Call {
	return &Resolver_Default_Call{Call: _e.mock.On("Default")}
}

func (_c *Resolver_Default_Call) Run(run func()) *Resolver_Default_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Resolver_Default_Call) Return(_a0 domain.ProviderConfig) *Resolver_Default_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Resolver_Default_Call) RunAndReturn(run func() domain.ProviderConfig) *Resolver_Default_Call {
	_c.Call.Return(run)
	return _c
}

// Provider provides a mock function with given fields: cfg
func (_m *Resolver) Provider(cfg domain.ProviderConfig) (domain.Provider, error) {
	ret := _m.Called(cfg)

	if len(ret) == 0 {
		panic("no return value specified for Provider")
	}

	var r0 domain.Provider
	var r1 error
	if rf, ok := ret.Get(0).(func(domain.ProviderConfig) (domain.Provider, error)); ok {
		return rf(cfg)
	}
	if rf, ok := ret.Get(0).(func(domain.ProviderConfig) domain.Provider); ok {
		r0 = rf(cfg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.Provider)
		}
	}

	if rf, ok := ret.Get(1).(func(domain.ProviderConfig) error); ok {
		r1 = rf(cfg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Resolver_Provider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Provider'
type Resolver_Provider_Call struct {
	*mock.Call
}

// Provider is a helper method to define mock.On call
//   - cfg domain.ProviderConfig
func (_e *Resolver_Expecter) Provider(cfg interface{}) *Resolver_Provider_Call {
	return &Resolver_Provider_Call{Call: _e.mock.On("Provider", cfg)}
}

func (_c *Resolver_Provider_Call) Run(run func(cfg domain.ProviderConfig)) *Resolver_Provider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(domain.ProviderConfig))
	})
	return _c
}

func (_c *Resolver_Provider_Call) Return(_a0 domain.Provider, _a1 error) *Resolver_Provider_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Resolver_Provider_Call) RunAndReturn(run func(domain.ProviderConfig) (domain.Provider, error)) *Resolver_Provider_Call {
	_c.Call.Return(run)
	return _c
}

// Resolve provides a mock function with given fields: ctx, scope
func (_m *Resolver) Resolve(ctx context.Context, scope domain.Scope) ([]domain.ProviderConfig, error) {
	ret := _m.Called(ctx, scope)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 []domain.ProviderConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope) ([]domain.ProviderConfig, error)); ok {
		return rf(ctx, scope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope) []domain.ProviderConfig); ok {
		r0 = rf(ctx, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ProviderConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Scope) error); ok {
		r1 = rf(ctx, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Resolver_Resolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolve'
type Resolver_Resolve_Call struct {
	*mock.Call
}

// Resolve is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
func (_e *Resolver_Expecter) Resolve(ctx interface{}, scope interface{}) *Resolver_Resolve_Call {
	return &Resolver_Resolve_Call{Call: _e.mock.On("Resolve", ctx, scope)}
}

func (_c *Resolver_Resolve_Call) Run(run func(ctx context.Context, scope domain.Scope)) *Resolver_Resolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope))
	})
	return _c
}

func (_c *Resolver_Resolve_Call) Return(_a0 []domain.ProviderConfig, _a1 error) *Resolver_Resolve_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Resolver_Resolve_Call) RunAndReturn(run func(context.Context, domain.Scope) ([]domain.ProviderConfig, error)) *Resolver_Resolve_Call {
	_c.Call.Return(run)
	return _c
}

// NewResolver creates a new instance of Resolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *Resolver {
	mock := &Resolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
