// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	domain "github.com/robzlabz/employeebot/apps/backend/internal/modules/llm/domain"
	mock "github.com/stretchr/testify/mock"
)

// CostTable is an autogenerated mock type for the CostTable type
type CostTable struct {
	mock.Mock
}

type CostTable_Expecter struct {
	mock *mock.Mock
}

func (_m *CostTable) EXPECT() *CostTable_Expecter {
	return &CostTable_Expecter{mock: &_m.Mock}
}

// Cost provides a mock function with given fields: model, usage
func (_m *CostTable) Cost(model string, usage domain.Usage) int64 {
	ret := _m.Called(model, usage)

	if len(ret) == 0 {
		panic("no return value specified for Cost")
	}

	var r0 int64
	if rf, ok := ret.Get(0).(func(string, domain.Usage) int64); ok {
		r0 = rf(model, usage)
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// CostTable_Cost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cost'
type CostTable_Cost_Call struct {
	*mock.Call
}

// Cost is a helper method to define mock.On call
//   - model string
//   - usage domain.Usage
func (_e *CostTable_Expecter) Cost(model interface{}, usage interface{}) *CostTable_Cost_Call {
	return &CostTable_Cost_Call{Call: _e.mock.On("Cost", model, usage)}
}

func (_c *CostTable_Cost_Call) Run(run func(model string, usage domain.Usage)) *CostTable_Cost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(domain.Usage))
	})
	return _c
}

func (_c *CostTable_Cost_Call) Return(_a0 int64) *CostTable_Cost_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CostTable_Cost_Call) RunAndReturn(run func(string, domain.Usage) int64) *CostTable_Cost_Call {
	_c.Call.Return(run)
	return _c
}

// NewCostTable creates a new instance of CostTable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCostTable(t interface {
	mock.TestingT
	Cleanup(func())
}) *CostTable {
	mock := &CostTable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
