// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/robzlabz/employeebot/apps/backend/internal/modules/llm/domain"
	mock "github.com/stretchr/testify/mock"
)

// Provider is an autogenerated mock type for the Provider type
type Provider struct {
	mock.Mock
}

type Provider_Expecter struct {
	mock *mock.Mock
}

func (_m *Provider) EXPECT() *Provider_Expecter {
	return &Provider_Expecter{mock: &_m.Mock}
}

// Capabilities provides a mock function with no fields
func (_m *Provider) Capabilities() domain.Capabilities {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Capabilities")
	}

	var r0 domain.Capabilities
	if rf, ok := ret.Get(0).(func() domain.Capabilities); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(domain.Capabilities)
	}

	return r0
}

// Provider_Capabilities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Capabilities'
type Provider_Capabilities_Call struct {
	*mock.Call
}

// Capabilities is a helper method to define mock.On call
func (_e *Provider_Expecter) Capabilities() *Provider_Capabilities_Call {
	return &Provider_Capabilities_Call{Call: _e.mock.On("Capabilities")}
}

func (_c *Provider_Capabilities_Call) Run(run func()) *Provider_Capabilities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Provider_Capabilities_Call) Return(_a0 domain.Capabilities) *Provider_Capabilities_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Provider_Capabilities_Call) RunAndReturn(run func() domain.Capabilities) *Provider_Capabilities_Call {
	_c.Call.Return(run)
	return _c
}

// Chat provides a mock function with given fields: ctx, req
func (_m *Provider) Chat(ctx context.Context, req domain.ChatRequest) (domain.ChatResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Chat")
	}

	var r0 domain.ChatResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ChatRequest) (domain.ChatResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.ChatRequest) domain.ChatResponse); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(domain.ChatResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.ChatRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Provider_Chat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Chat'
type Provider_Chat_Call struct {
	*mock.Call
}

// Chat is a helper method to define mock.On call
//   - ctx context.Context
//   - req domain.ChatRequest
func (_e *Provider_Expecter) Chat(ctx interface{}, req interface{}) *Provider_Chat_Call {
	return &Provider_Chat_Call{Call: _e.mock.On("Chat", ctx, req)}
}

func (_c *Provider_Chat_Call) Run(run func(ctx context.Context, req domain.ChatRequest)) *Provider_Chat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.ChatRequest))
	})
	return _c
}

func (_c *Provider_Chat_Call) Return(_a0 domain.ChatResponse, _a1 error) *Provider_Chat_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Provider_Chat_Call) RunAndReturn(run func(context.Context, domain.ChatRequest) (domain.ChatResponse, error)) *Provider_Chat_Call {
	_c.Call.Return(run)
	return _c
}

// Model provides a mock function with no fields
func (_m *Provider) Model() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Model")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Provider_Model_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Model'
type Provider_Model_Call struct {
	*mock.Call
}

// Model is a helper method to define mock.On call
func (_e *Provider_Expecter) Model() *Provider_Model_Call {
	return &Provider_Model_Call{Call: _e.mock.On("Model")}
}

func (_c *Provider_Model_Call) Run(run func()) *Provider_Model_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Provider_Model_Call) Return(_a0 string) *Provider_Model_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Provider_Model_Call) RunAndReturn(run func() string) *Provider_Model_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function with no fields
func (_m *Provider) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Provider_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type Provider_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *Provider_Expecter) Name() *Provider_Name_Call {
	return &Provider_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *Provider_Name_Call) Run(run func()) *Provider_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Provider_Name_Call) Return(_a0 string) *Provider_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Provider_Name_Call) RunAndReturn(run func() string) *Provider_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Stream provides a mock function with given fields: ctx, req
func (_m *Provider) Stream(ctx context.Context, req domain.ChatRequest) (<-chan domain.StreamEvent, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Stream")
	}

	var r0 <-chan domain.StreamEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ChatRequest) (<-chan domain.StreamEvent, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.ChatRequest) <-chan domain.StreamEvent); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan domain.StreamEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.ChatRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Provider_Stream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stream'
type Provider_Stream_Call struct {
	*mock.Call
}

// Stream is a helper method to define mock.On call
//   - ctx context.Context
//   - req domain.ChatRequest
func (_e *Provider_Expecter) Stream(ctx interface{}, req interface{}) *Provider_Stream_Call {
	return &Provider_Stream_Call{Call: _e.mock.On("Stream", ctx, req)}
}

func (_c *Provider_Stream_Call) Run(run func(ctx context.Context, req domain.ChatRequest)) *Provider_Stream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.ChatRequest))
	})
	return _c
}

func (_c *Provider_Stream_Call) Return(_a0 <-chan domain.StreamEvent, _a1 error) *Provider_Stream_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Provider_Stream_Call) RunAndReturn(run func(context.Context, domain.ChatRequest) (<-chan domain.StreamEvent, error)) *Provider_Stream_Call {
	_c.Call.Return(run)
	return _c
}

// NewProvider creates a new instance of Provider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *Provider {
	mock := &Provider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
