// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SecretBox is an autogenerated mock type for the SecretBox type
type SecretBox struct {
	mock.Mock
}

type SecretBox_Expecter struct {
	mock *mock.Mock
}

func (_m *SecretBox) EXPECT() *SecretBox_Expecter {
	return &SecretBox_Expecter{mock: &_m.Mock}
}

// Decrypt provides a mock function with given fields: ciphertext
func (_m *SecretBox) Decrypt(ciphertext []byte) (string, error) {
	ret := _m.Called(ciphertext)

	if len(ret) == 0 {
		panic("no return value specified for Decrypt")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) (string, error)); ok {
		return rf(ciphertext)
	}
	if rf, ok := ret.Get(0).(func([]byte) string); ok {
		r0 = rf(ciphertext)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(ciphertext)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SecretBox_Decrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decrypt'
type SecretBox_Decrypt_Call struct {
	*mock.Call
}

// Decrypt is a helper method to define mock.On call
//   - ciphertext []byte
func (_e *SecretBox_Expecter) Decrypt(ciphertext interface{}) *SecretBox_Decrypt_Call {
	return &SecretBox_Decrypt_Call{Call: _e.mock.On("Decrypt", ciphertext)}
}

func (_c *SecretBox_Decrypt_Call) Run(run func(ciphertext []byte)) *SecretBox_Decrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *SecretBox_Decrypt_Call) Return(_a0 string, _a1 error) *SecretBox_Decrypt_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SecretBox_Decrypt_Call) RunAndReturn(run func([]byte) (string, error)) *SecretBox_Decrypt_Call {
	_c.Call.Return(run)
	return _c
}

// Encrypt provides a mock function with given fields: plaintext
func (_m *SecretBox) Encrypt(plaintext string) ([]byte, error) {
	ret := _m.Called(plaintext)

	if len(ret) == 0 {
		panic("no return value specified for Encrypt")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return rf(plaintext)
	}
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(plaintext)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(plaintext)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SecretBox_Encrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encrypt'
type SecretBox_Encrypt_Call struct {
	*mock.Call
}

// Encrypt is a helper method to define mock.On call
//   - plaintext string
func (_e *SecretBox_Expecter) Encrypt(plaintext interface{}) *SecretBox_Encrypt_Call {
	return &SecretBox_Encrypt_Call{Call: _e.mock.On("Encrypt", plaintext)}
}

func (_c *SecretBox_Encrypt_Call) Run(run func(plaintext string)) *SecretBox_Encrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *SecretBox_Encrypt_Call) Return(_a0 []byte, _a1 error) *SecretBox_Encrypt_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SecretBox_Encrypt_Call) RunAndReturn(run func(string) ([]byte, error)) *SecretBox_Encrypt_Call {
	_c.Call.Return(run)
	return _c
}

// NewSecretBox creates a new instance of SecretBox. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSecretBox(t interface {
	mock.TestingT
	Cleanup(func())
}) *SecretBox {
	mock := &SecretBox{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
