// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/robzlabz/employeebot/apps/backend/internal/modules/llm/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// AgentStore is an autogenerated mock type for the AgentStore type
type AgentStore struct {
	mock.Mock
}

type AgentStore_Expecter struct {
	mock *mock.Mock
}

func (_m *AgentStore) EXPECT() *AgentStore_Expecter {
	return &AgentStore_Expecter{mock: &_m.Mock}
}

// AgentModel provides a mock function with given fields: ctx, workspaceID, agentID
func (_m *AgentStore) AgentModel(ctx context.Context, workspaceID uuid.UUID, agentID uuid.UUID) (domain.AgentOverride, error) {
	ret := _m.Called(ctx, workspaceID, agentID)

	if len(ret) == 0 {
		panic("no return value specified for AgentModel")
	}

	var r0 domain.AgentOverride
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (domain.AgentOverride, error)); ok {
		return rf(ctx, workspaceID, agentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) domain.AgentOverride); ok {
		r0 = rf(ctx, workspaceID, agentID)
	} else {
		r0 = ret.Get(0).(domain.AgentOverride)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, workspaceID, agentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AgentStore_AgentModel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AgentModel'
type AgentStore_AgentModel_Call struct {
	*mock.Call
}

// AgentModel is a helper method to define mock.On call
//   - ctx context.Context
//   - workspaceID uuid.UUID
//   - agentID uuid.UUID
func (_e *AgentStore_Expecter) AgentModel(ctx interface{}, workspaceID interface{}, agentID interface{}) *AgentStore_AgentModel_Call {
	return &AgentStore_AgentModel_Call{Call: _e.mock.On("AgentModel", ctx, workspaceID, agentID)}
}

func (_c *AgentStore_AgentModel_Call) Run(run func(ctx context.Context, workspaceID uuid.UUID, agentID uuid.UUID)) *AgentStore_AgentModel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *AgentStore_AgentModel_Call) Return(_a0 domain.AgentOverride, _a1 error) *AgentStore_AgentModel_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AgentStore_AgentModel_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (domain.AgentOverride, error)) *AgentStore_AgentModel_Call {
	_c.Call.Return(run)
	return _c
}

// SetAgentModel provides a mock function with given fields: ctx, workspaceID, agentID, override
func (_m *AgentStore) SetAgentModel(ctx context.Context, workspaceID uuid.UUID, agentID uuid.UUID, override domain.AgentOverride) error {
	ret := _m.Called(ctx, workspaceID, agentID, override)

	if len(ret) == 0 {
		panic("no return value specified for SetAgentModel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, domain.AgentOverride) error); ok {
		r0 = rf(ctx, workspaceID, agentID, override)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AgentStore_SetAgentModel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAgentModel'
type AgentStore_SetAgentModel_Call struct {
	*mock.Call
}

// SetAgentModel is a helper method to define mock.On call
//   - ctx context.Context
//   - workspaceID uuid.UUID
//   - agentID uuid.UUID
//   - override domain.AgentOverride
func (_e *AgentStore_Expecter) SetAgentModel(ctx interface{}, workspaceID interface{}, agentID interface{}, override interface{}) *AgentStore_SetAgentModel_Call {
	return &AgentStore_SetAgentModel_Call{Call: _e.mock.On("SetAgentModel", ctx, workspaceID, agentID, override)}
}

func (_c *AgentStore_SetAgentModel_Call) Run(run func(ctx context.Context, workspaceID uuid.UUID, agentID uuid.UUID, override domain.AgentOverride)) *AgentStore_SetAgentModel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(domain.AgentOverride))
	})
	return _c
}

func (_c *AgentStore_SetAgentModel_Call) Return(_a0 error) *AgentStore_SetAgentModel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AgentStore_SetAgentModel_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, domain.AgentOverride) error) *AgentStore_SetAgentModel_Call {
	_c.Call.Return(run)
	return _c
}

// NewAgentStore creates a new instance of AgentStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAgentStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *AgentStore {
	mock := &AgentStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
