// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/robzlabz/employeebot/apps/backend/internal/modules/llm/domain"
	mock "github.com/stretchr/testify/mock"
)

// UsageRecorder is an autogenerated mock type for the UsageRecorder type
type UsageRecorder struct {
	mock.Mock
}

type UsageRecorder_Expecter struct {
	mock *mock.Mock
}

func (_m *UsageRecorder) EXPECT() *UsageRecorder_Expecter {
	return &UsageRecorder_Expecter{mock: &_m.Mock}
}

// Record provides a mock function with given fields: ctx, entry
func (_m *UsageRecorder) Record(ctx context.Context, entry domain.UsageEntry) error {
	ret := _m.Called(ctx, entry)

	if len(ret) == 0 {
		panic("no return value specified for Record")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.UsageEntry) error); ok {
		r0 = rf(ctx, entry)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UsageRecorder_Record_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Record'
type UsageRecorder_Record_Call struct {
	*mock.Call
}

// Record is a helper method to define mock.On call
//   - ctx context.Context
//   - entry domain.UsageEntry
func (_e *UsageRecorder_Expecter) Record(ctx interface{}, entry interface{}) *UsageRecorder_Record_Call {
	return &UsageRecorder_Record_Call{Call: _e.mock.On("Record", ctx, entry)}
}

func (_c *UsageRecorder_Record_Call) Run(run func(ctx context.Context, entry domain.UsageEntry)) *UsageRecorder_Record_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.UsageEntry))
	})
	return _c
}

func (_c *UsageRecorder_Record_Call) Return(_a0 error) *UsageRecorder_Record_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UsageRecorder_Record_Call) RunAndReturn(run func(context.Context, domain.UsageEntry) error) *UsageRecorder_Record_Call {
	_c.Call.Return(run)
	return _c
}

// NewUsageRecorder creates a new instance of UsageRecorder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUsageRecorder(t interface {
	mock.TestingT
	Cleanup(func())
}) *UsageRecorder {
	mock := &UsageRecorder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
