// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/robzlabz/employeebot/apps/backend/internal/modules/llm/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// UsageReader is an autogenerated mock type for the UsageReader type
type UsageReader struct {
	mock.Mock
}

type UsageReader_Expecter struct {
	mock *mock.Mock
}

func (_m *UsageReader) EXPECT() *UsageReader_Expecter {
	return &UsageReader_Expecter{mock: &_m.Mock}
}

// Daily provides a mock function with given fields: ctx, workspaceID, since
func (_m *UsageReader) Daily(ctx context.Context, workspaceID uuid.UUID, since time.Time) ([]domain.UsageDaily, error) {
	ret := _m.Called(ctx, workspaceID, since)

	if len(ret) == 0 {
		panic("no return value specified for Daily")
	}

	var r0 []domain.UsageDaily
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) ([]domain.UsageDaily, error)); ok {
		return rf(ctx, workspaceID, since)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) []domain.UsageDaily); ok {
		r0 = rf(ctx, workspaceID, since)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.UsageDaily)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r1 = rf(ctx, workspaceID, since)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UsageReader_Daily_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Daily'
type UsageReader_Daily_Call struct {
	*mock.Call
}

// Daily is a helper method to define mock.On call
//   - ctx context.Context
//   - workspaceID uuid.UUID
//   - since time.Time
func (_e *UsageReader_Expecter) Daily(ctx interface{}, workspaceID interface{}, since interface{}) *UsageReader_Daily_Call {
	return &UsageReader_Daily_Call{Call: _e.mock.On("Daily", ctx, workspaceID, since)}
}

func (_c *UsageReader_Daily_Call) Run(run func(ctx context.Context, workspaceID uuid.UUID, since time.Time)) *UsageReader_Daily_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time))
	})
	return _c
}

func (_c *UsageReader_Daily_Call) Return(_a0 []domain.UsageDaily, _a1 error) *UsageReader_Daily_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UsageReader_Daily_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time) ([]domain.UsageDaily, error)) *UsageReader_Daily_Call {
	_c.Call.Return(run)
	return _c
}

// SumSince provides a mock function with given fields: ctx, workspaceID, since
func (_m *UsageReader) SumSince(ctx context.Context, workspaceID uuid.UUID, since time.Time) (int64, error) {
	ret := _m.Called(ctx, workspaceID, since)

	if len(ret) == 0 {
		panic("no return value specified for SumSince")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) (int64, error)); ok {
		return rf(ctx, workspaceID, since)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) int64); ok {
		r0 = rf(ctx, workspaceID, since)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r1 = rf(ctx, workspaceID, since)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UsageReader_SumSince_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SumSince'
type UsageReader_SumSince_Call struct {
	*mock.Call
}

// SumSince is a helper method to define mock.On call
//   - ctx context.Context
//   - workspaceID uuid.UUID
//   - since time.Time
func (_e *UsageReader_Expecter) SumSince(ctx interface{}, workspaceID interface{}, since interface{}) *UsageReader_SumSince_Call {
	return &UsageReader_SumSince_Call{Call: _e.mock.On("SumSince", ctx, workspaceID, since)}
}

func (_c *UsageReader_SumSince_Call) Run(run func(ctx context.Context, workspaceID uuid.UUID, since time.Time)) *UsageReader_SumSince_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time))
	})
	return _c
}

func (_c *UsageReader_SumSince_Call) Return(_a0 int64, _a1 error) *UsageReader_SumSince_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UsageReader_SumSince_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time) (int64, error)) *UsageReader_SumSince_Call {
	_c.Call.Return(run)
	return _c
}

// NewUsageReader creates a new instance of UsageReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUsageReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *UsageReader {
	mock := &UsageReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
