// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	domain "github.com/robzlabz/employeebot/apps/backend/internal/modules/llm/domain"
	mock "github.com/stretchr/testify/mock"
)

// Factory is an autogenerated mock type for the Factory type
type Factory struct {
	mock.Mock
}

type Factory_Expecter struct {
	mock *mock.Mock
}

func (_m *Factory) EXPECT() *Factory_Expecter {
	return &Factory_Expecter{mock: &_m.Mock}
}

// Build provides a mock function with given fields: cfg
func (_m *Factory) Build(cfg domain.ProviderConfig) (domain.Provider, error) {
	ret := _m.Called(cfg)

	if len(ret) == 0 {
		panic("no return value specified for Build")
	}

	var r0 domain.Provider
	var r1 error
	if rf, ok := ret.Get(0).(func(domain.ProviderConfig) (domain.Provider, error)); ok {
		return rf(cfg)
	}
	if rf, ok := ret.Get(0).(func(domain.ProviderConfig) domain.Provider); ok {
		r0 = rf(cfg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.Provider)
		}
	}

	if rf, ok := ret.Get(1).(func(domain.ProviderConfig) error); ok {
		r1 = rf(cfg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Factory_Build_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Build'
type Factory_Build_Call struct {
	*mock.Call
}

// Build is a helper method to define mock.On call
//   - cfg domain.ProviderConfig
func (_e *Factory_Expecter) Build(cfg interface{}) *Factory_Build_Call {
	return &Factory_Build_Call{Call: _e.mock.On("Build", cfg)}
}

func (_c *Factory_Build_Call) Run(run func(cfg domain.ProviderConfig)) *Factory_Build_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(domain.ProviderConfig))
	})
	return _c
}

func (_c *Factory_Build_Call) Return(_a0 domain.Provider, _a1 error) *Factory_Build_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Factory_Build_Call) RunAndReturn(run func(domain.ProviderConfig) (domain.Provider, error)) *Factory_Build_Call {
	_c.Call.Return(run)
	return _c
}

// NewFactory creates a new instance of Factory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *Factory {
	mock := &Factory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
