// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/robzlabz/employeebot/apps/backend/internal/modules/llm/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// Gateway is an autogenerated mock type for the Gateway type
type Gateway struct {
	mock.Mock
}

type Gateway_Expecter struct {
	mock *mock.Mock
}

func (_m *Gateway) EXPECT() *Gateway_Expecter {
	return &Gateway_Expecter{mock: &_m.Mock}
}

// AgentModel provides a mock function with given fields: ctx, scope
func (_m *Gateway) AgentModel(ctx context.Context, scope domain.Scope) (domain.AgentOverride, error) {
	ret := _m.Called(ctx, scope)

	if len(ret) == 0 {
		panic("no return value specified for AgentModel")
	}

	var r0 domain.AgentOverride
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope) (domain.AgentOverride, error)); ok {
		return rf(ctx, scope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope) domain.AgentOverride); ok {
		r0 = rf(ctx, scope)
	} else {
		r0 = ret.Get(0).(domain.AgentOverride)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Scope) error); ok {
		r1 = rf(ctx, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Gateway_AgentModel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AgentModel'
type Gateway_AgentModel_Call struct {
	*mock.Call
}

// AgentModel is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
func (_e *Gateway_Expecter) AgentModel(ctx interface{}, scope interface{}) *Gateway_AgentModel_Call {
	return &Gateway_AgentModel_Call{Call: _e.mock.On("AgentModel", ctx, scope)}
}

func (_c *Gateway_AgentModel_Call) Run(run func(ctx context.Context, scope domain.Scope)) *Gateway_AgentModel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope))
	})
	return _c
}

func (_c *Gateway_AgentModel_Call) Return(_a0 domain.AgentOverride, _a1 error) *Gateway_AgentModel_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Gateway_AgentModel_Call) RunAndReturn(run func(context.Context, domain.Scope) (domain.AgentOverride, error)) *Gateway_AgentModel_Call {
	_c.Call.Return(run)
	return _c
}

// Chat provides a mock function with given fields: ctx, scope, req
func (_m *Gateway) Chat(ctx context.Context, scope domain.Scope, req domain.ChatRequest) (domain.ChatResponse, error) {
	ret := _m.Called(ctx, scope, req)

	if len(ret) == 0 {
		panic("no return value specified for Chat")
	}

	var r0 domain.ChatResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, domain.ChatRequest) (domain.ChatResponse, error)); ok {
		return rf(ctx, scope, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, domain.ChatRequest) domain.ChatResponse); ok {
		r0 = rf(ctx, scope, req)
	} else {
		r0 = ret.Get(0).(domain.ChatResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Scope, domain.ChatRequest) error); ok {
		r1 = rf(ctx, scope, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Gateway_Chat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Chat'
type Gateway_Chat_Call struct {
	*mock.Call
}

// Chat is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
//   - req domain.ChatRequest
func (_e *Gateway_Expecter) Chat(ctx interface{}, scope interface{}, req interface{}) *Gateway_Chat_Call {
	return &Gateway_Chat_Call{Call: _e.mock.On("Chat", ctx, scope, req)}
}

func (_c *Gateway_Chat_Call) Run(run func(ctx context.Context, scope domain.Scope, req domain.ChatRequest)) *Gateway_Chat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope), args[2].(domain.ChatRequest))
	})
	return _c
}

func (_c *Gateway_Chat_Call) Return(_a0 domain.ChatResponse, _a1 error) *Gateway_Chat_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Gateway_Chat_Call) RunAndReturn(run func(context.Context, domain.Scope, domain.ChatRequest) (domain.ChatResponse, error)) *Gateway_Chat_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, scope, id
func (_m *Gateway) Delete(ctx context.Context, scope domain.Scope, id uuid.UUID) error {
	ret := _m.Called(ctx, scope, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, uuid.UUID) error); ok {
		r0 = rf(ctx, scope, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Gateway_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type Gateway_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
//   - id uuid.UUID
func (_e *Gateway_Expecter) Delete(ctx interface{}, scope interface{}, id interface{}) *Gateway_Delete_Call {
	return &Gateway_Delete_Call{Call: _e.mock.On("Delete", ctx, scope, id)}
}

func (_c *Gateway_Delete_Call) Run(run func(ctx context.Context, scope domain.Scope, id uuid.UUID)) *Gateway_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *Gateway_Delete_Call) Return(_a0 error) *Gateway_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Gateway_Delete_Call) RunAndReturn(run func(context.Context, domain.Scope, uuid.UUID) error) *Gateway_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Providers provides a mock function with given fields: ctx, scope
func (_m *Gateway) Providers(ctx context.Context, scope domain.Scope) ([]domain.Redacted, error) {
	ret := _m.Called(ctx, scope)

	if len(ret) == 0 {
		panic("no return value specified for Providers")
	}

	var r0 []domain.Redacted
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope) ([]domain.Redacted, error)); ok {
		return rf(ctx, scope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope) []domain.Redacted); ok {
		r0 = rf(ctx, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Redacted)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Scope) error); ok {
		r1 = rf(ctx, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Gateway_Providers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Providers'
type Gateway_Providers_Call struct {
	*mock.Call
}

// Providers is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
func (_e *Gateway_Expecter) Providers(ctx interface{}, scope interface{}) *Gateway_Providers_Call {
	return &Gateway_Providers_Call{Call: _e.mock.On("Providers", ctx, scope)}
}

func (_c *Gateway_Providers_Call) Run(run func(ctx context.Context, scope domain.Scope)) *Gateway_Providers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope))
	})
	return _c
}

func (_c *Gateway_Providers_Call) Return(_a0 []domain.Redacted, _a1 error) *Gateway_Providers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Gateway_Providers_Call) RunAndReturn(run func(context.Context, domain.Scope) ([]domain.Redacted, error)) *Gateway_Providers_Call {
	_c.Call.Return(run)
	return _c
}

// SetAgentModel provides a mock function with given fields: ctx, scope, override
func (_m *Gateway) SetAgentModel(ctx context.Context, scope domain.Scope, override domain.AgentOverride) error {
	ret := _m.Called(ctx, scope, override)

	if len(ret) == 0 {
		panic("no return value specified for SetAgentModel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, domain.AgentOverride) error); ok {
		r0 = rf(ctx, scope, override)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Gateway_SetAgentModel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAgentModel'
type Gateway_SetAgentModel_Call struct {
	*mock.Call
}

// SetAgentModel is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
//   - override domain.AgentOverride
func (_e *Gateway_Expecter) SetAgentModel(ctx interface{}, scope interface{}, override interface{}) *Gateway_SetAgentModel_Call {
	return &Gateway_SetAgentModel_Call{Call: _e.mock.On("SetAgentModel", ctx, scope, override)}
}

func (_c *Gateway_SetAgentModel_Call) Run(run func(ctx context.Context, scope domain.Scope, override domain.AgentOverride)) *Gateway_SetAgentModel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope), args[2].(domain.AgentOverride))
	})
	return _c
}

func (_c *Gateway_SetAgentModel_Call) Return(_a0 error) *Gateway_SetAgentModel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Gateway_SetAgentModel_Call) RunAndReturn(run func(context.Context, domain.Scope, domain.AgentOverride) error) *Gateway_SetAgentModel_Call {
	_c.Call.Return(run)
	return _c
}

// Stream provides a mock function with given fields: ctx, scope, req
func (_m *Gateway) Stream(ctx context.Context, scope domain.Scope, req domain.ChatRequest) (<-chan domain.StreamEvent, error) {
	ret := _m.Called(ctx, scope, req)

	if len(ret) == 0 {
		panic("no return value specified for Stream")
	}

	var r0 <-chan domain.StreamEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, domain.ChatRequest) (<-chan domain.StreamEvent, error)); ok {
		return rf(ctx, scope, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, domain.ChatRequest) <-chan domain.StreamEvent); ok {
		r0 = rf(ctx, scope, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan domain.StreamEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Scope, domain.ChatRequest) error); ok {
		r1 = rf(ctx, scope, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Gateway_Stream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stream'
type Gateway_Stream_Call struct {
	*mock.Call
}

// Stream is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
//   - req domain.ChatRequest
func (_e *Gateway_Expecter) Stream(ctx interface{}, scope interface{}, req interface{}) *Gateway_Stream_Call {
	return &Gateway_Stream_Call{Call: _e.mock.On("Stream", ctx, scope, req)}
}

func (_c *Gateway_Stream_Call) Run(run func(ctx context.Context, scope domain.Scope, req domain.ChatRequest)) *Gateway_Stream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope), args[2].(domain.ChatRequest))
	})
	return _c
}

func (_c *Gateway_Stream_Call) Return(_a0 <-chan domain.StreamEvent, _a1 error) *Gateway_Stream_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Gateway_Stream_Call) RunAndReturn(run func(context.Context, domain.Scope, domain.ChatRequest) (<-chan domain.StreamEvent, error)) *Gateway_Stream_Call {
	_c.Call.Return(run)
	return _c
}

// Test provides a mock function with given fields: ctx, scope, id
func (_m *Gateway) Test(ctx context.Context, scope domain.Scope, id uuid.UUID) (domain.Capabilities, error) {
	ret := _m.Called(ctx, scope, id)

	if len(ret) == 0 {
		panic("no return value specified for Test")
	}

	var r0 domain.Capabilities
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, uuid.UUID) (domain.Capabilities, error)); ok {
		return rf(ctx, scope, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, uuid.UUID) domain.Capabilities); ok {
		r0 = rf(ctx, scope, id)
	} else {
		r0 = ret.Get(0).(domain.Capabilities)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Scope, uuid.UUID) error); ok {
		r1 = rf(ctx, scope, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Gateway_Test_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Test'
type Gateway_Test_Call struct {
	*mock.Call
}

// Test is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
//   - id uuid.UUID
func (_e *Gateway_Expecter) Test(ctx interface{}, scope interface{}, id interface{}) *Gateway_Test_Call {
	return &Gateway_Test_Call{Call: _e.mock.On("Test", ctx, scope, id)}
}

func (_c *Gateway_Test_Call) Run(run func(ctx context.Context, scope domain.Scope, id uuid.UUID)) *Gateway_Test_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *Gateway_Test_Call) Return(_a0 domain.Capabilities, _a1 error) *Gateway_Test_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Gateway_Test_Call) RunAndReturn(run func(context.Context, domain.Scope, uuid.UUID) (domain.Capabilities, error)) *Gateway_Test_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function with given fields: ctx, scope, req
func (_m *Gateway) Upsert(ctx context.Context, scope domain.Scope, req domain.UpsertRequest) (domain.Redacted, error) {
	ret := _m.Called(ctx, scope, req)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 domain.Redacted
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, domain.UpsertRequest) (domain.Redacted, error)); ok {
		return rf(ctx, scope, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, domain.UpsertRequest) domain.Redacted); ok {
		r0 = rf(ctx, scope, req)
	} else {
		r0 = ret.Get(0).(domain.Redacted)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Scope, domain.UpsertRequest) error); ok {
		r1 = rf(ctx, scope, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Gateway_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type Gateway_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
//   - req domain.UpsertRequest
func (_e *Gateway_Expecter) Upsert(ctx interface{}, scope interface{}, req interface{}) *Gateway_Upsert_Call {
	return &Gateway_Upsert_Call{Call: _e.mock.On("Upsert", ctx, scope, req)}
}

func (_c *Gateway_Upsert_Call) Run(run func(ctx context.Context, scope domain.Scope, req domain.UpsertRequest)) *Gateway_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope), args[2].(domain.UpsertRequest))
	})
	return _c
}

func (_c *Gateway_Upsert_Call) Return(_a0 domain.Redacted, _a1 error) *Gateway_Upsert_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Gateway_Upsert_Call) RunAndReturn(run func(context.Context, domain.Scope, domain.UpsertRequest) (domain.Redacted, error)) *Gateway_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// Usage provides a mock function with given fields: ctx, scope, days
func (_m *Gateway) Usage(ctx context.Context, scope domain.Scope, days int) ([]domain.UsageDaily, error) {
	ret := _m.Called(ctx, scope, days)

	if len(ret) == 0 {
		panic("no return value specified for Usage")
	}

	var r0 []domain.UsageDaily
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, int) ([]domain.UsageDaily, error)); ok {
		return rf(ctx, scope, days)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, int) []domain.UsageDaily); ok {
		r0 = rf(ctx, scope, days)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.UsageDaily)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Scope, int) error); ok {
		r1 = rf(ctx, scope, days)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Gateway_Usage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Usage'
type Gateway_Usage_Call struct {
	*mock.Call
}

// Usage is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
//   - days int
func (_e *Gateway_Expecter) Usage(ctx interface{}, scope interface{}, days interface{}) *Gateway_Usage_Call {
	return &Gateway_Usage_Call{Call: _e.mock.On("Usage", ctx, scope, days)}
}

func (_c *Gateway_Usage_Call) Run(run func(ctx context.Context, scope domain.Scope, days int)) *Gateway_Usage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope), args[2].(int))
	})
	return _c
}

func (_c *Gateway_Usage_Call) Return(_a0 []domain.UsageDaily, _a1 error) *Gateway_Usage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Gateway_Usage_Call) RunAndReturn(run func(context.Context, domain.Scope, int) ([]domain.UsageDaily, error)) *Gateway_Usage_Call {
	_c.Call.Return(run)
	return _c
}

// NewGateway creates a new instance of Gateway. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGateway(t interface {
	mock.TestingT
	Cleanup(func())
}) *Gateway {
	mock := &Gateway{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
