// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const agentActivity = `-- name: AgentActivity :many
SELECT a.id,
       EXISTS (
           SELECT 1 FROM tasks t
           WHERE t.agent_id = a.id AND t.status IN ('queued', 'running')
       ) AS working,
       EXISTS (
           SELECT 1 FROM drafts d
           WHERE d.agent_id = a.id AND d.status = 'pending'
       ) AS waiting
FROM agents a
WHERE a.workspace_id = $1 AND a.deleted_at IS NULL
`

type AgentActivityRow struct {
	ID      uuid.UUID
	Working bool
	Waiting bool
}

// The raw inputs of the derived display status, for every live Bolu at once.
// "working" is a task in flight, "waiting" is a draft waiting for a human.
func (q *Queries) AgentActivity(ctx context.Context, workspaceID uuid.UUID) ([]AgentActivityRow, error) {
	rows, err := q.db.Query(ctx, agentActivity, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentActivityRow{}
	for rows.Next() {
		var i AgentActivityRow
		if err := rows.Scan(&i.ID, &i.Working, &i.Waiting); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const agentActivityByID = `-- name: AgentActivityByID :one
SELECT a.id,
       EXISTS (
           SELECT 1 FROM tasks t
           WHERE t.agent_id = a.id AND t.status IN ('queued', 'running')
       ) AS working,
       EXISTS (
           SELECT 1 FROM drafts d
           WHERE d.agent_id = a.id AND d.status = 'pending'
       ) AS waiting
FROM agents a
WHERE a.id = $1 AND a.workspace_id = $2 AND a.deleted_at IS NULL
`

type AgentActivityByIDParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

type AgentActivityByIDRow struct {
	ID      uuid.UUID
	Working bool
	Waiting bool
}

func (q *Queries) AgentActivityByID(ctx context.Context, arg AgentActivityByIDParams) (AgentActivityByIDRow, error) {
	row := q.db.QueryRow(ctx, agentActivityByID, arg.ID, arg.WorkspaceID)
	var i AgentActivityByIDRow
	err := row.Scan(&i.ID, &i.Working, &i.Waiting)
	return i, err
}

const allowedToolsForAgent = `-- name: AllowedToolsForAgent :many
SELECT tc.name, tc.integration_app, tc.label, tc.description
FROM agents a
JOIN tool_catalog tc ON tc.name IN (SELECT jsonb_array_elements_text(a.tools))
JOIN integrations i ON i.workspace_id = a.workspace_id AND i.app = tc.integration_app
JOIN agent_grants g ON g.agent_id = a.id AND g.integration_id = i.id
WHERE a.id = $1 AND a.workspace_id = $2 AND a.deleted_at IS NULL
  AND (g.permission = 'read_write' OR tc.label = 'read')
ORDER BY tc.name
`

type AllowedToolsForAgentParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

type AllowedToolsForAgentRow struct {
	Name           string
	IntegrationApp string
	Label          string
	Description    string
}

// The effective tool list: what the agent asks for, restricted to integrations
// it was actually granted. A read-only grant keeps only the tools that cannot
// touch anything outside Bolu.
func (q *Queries) AllowedToolsForAgent(ctx context.Context, arg AllowedToolsForAgentParams) ([]AllowedToolsForAgentRow, error) {
	rows, err := q.db.Query(ctx, allowedToolsForAgent, arg.ID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AllowedToolsForAgentRow{}
	for rows.Next() {
		var i AllowedToolsForAgentRow
		if err := rows.Scan(
			&i.Name,
			&i.IntegrationApp,
			&i.Label,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const copyAgentTemplates = `-- name: CopyAgentTemplates :execrows
INSERT INTO agents (workspace_id, team_id, name, role, persona, tone, shape, color, tools, template_key, default_model)
SELECT $1, $2, t.name, t.role, t.persona, t.tone, t.shape, t.color, t.tools, t.key, t.default_model
FROM agent_templates t
ORDER BY t.sort_order
`

type CopyAgentTemplatesParams struct {
	WorkspaceID uuid.UUID
	TeamID      uuid.UUID
}

// The onboarding step: every template becomes a Bolu of the new workspace. The
// caller runs this inside the onboarding transaction, so a workspace is never
// left without its team.
func (q *Queries) CopyAgentTemplates(ctx context.Context, arg CopyAgentTemplatesParams) (int64, error) {
	result, err := q.db.Exec(ctx, copyAgentTemplates, arg.WorkspaceID, arg.TeamID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countLiveAgents = `-- name: CountLiveAgents :one
SELECT count(*)::bigint FROM agents
WHERE workspace_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountLiveAgents(ctx context.Context, workspaceID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countLiveAgents, workspaceID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countRunningTasksForAgent = `-- name: CountRunningTasksForAgent :one
SELECT count(*)::bigint FROM tasks
WHERE agent_id = $1 AND status IN ('queued', 'running')
`

// Guards the delete: a Bolu that is working must be left alone until it stops.
func (q *Queries) CountRunningTasksForAgent(ctx context.Context, agentID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRunningTasksForAgent, agentID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createAgent = `-- name: CreateAgent :one
INSERT INTO agents (workspace_id, team_id, name, role, persona, tone, shape, color, tools, template_key, default_model)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, workspace_id, team_id, name, role, persona, tone, shape, color, status, template_key, default_model, created_at, updated_at, deleted_at, tools
`

type CreateAgentParams struct {
	WorkspaceID  uuid.UUID
	TeamID       uuid.UUID
	Name         string
	Role         string
	Persona      string
	Tone         string
	Shape        string
	Color        string
	Tools        []byte
	TemplateKey  string
	DefaultModel []byte
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, createAgent,
		arg.WorkspaceID,
		arg.TeamID,
		arg.Name,
		arg.Role,
		arg.Persona,
		arg.Tone,
		arg.Shape,
		arg.Color,
		arg.Tools,
		arg.TemplateKey,
		arg.DefaultModel,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TeamID,
		&i.Name,
		&i.Role,
		&i.Persona,
		&i.Tone,
		&i.Shape,
		&i.Color,
		&i.Status,
		&i.TemplateKey,
		&i.DefaultModel,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Tools,
	)
	return i, err
}

const deleteGrant = `-- name: DeleteGrant :execrows
DELETE FROM agent_grants
WHERE workspace_id = $1 AND agent_id = $2 AND integration_id = $3
`

type DeleteGrantParams struct {
	WorkspaceID   uuid.UUID
	AgentID       uuid.UUID
	IntegrationID uuid.UUID
}

func (q *Queries) DeleteGrant(ctx context.Context, arg DeleteGrantParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGrant, arg.WorkspaceID, arg.AgentID, arg.IntegrationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAgent = `-- name: GetAgent :one
SELECT a.id, a.workspace_id, a.team_id, a.name, a.role, a.persona, a.tone, a.shape, a.color, a.status, a.template_key, a.default_model, a.created_at, a.updated_at, a.deleted_at, a.tools, t.name AS team_name, t.kind AS team_kind
FROM agents a
JOIN teams t ON t.id = a.team_id
WHERE a.id = $1 AND a.workspace_id = $2 AND a.deleted_at IS NULL
`

type GetAgentParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

type GetAgentRow struct {
	ID           uuid.UUID
	WorkspaceID  uuid.UUID
	TeamID       uuid.UUID
	Name         string
	Role         string
	Persona      string
	Tone         string
	Shape        string
	Color        string
	Status       string
	TemplateKey  string
	DefaultModel []byte
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    *time.Time
	Tools        []byte
	TeamName     string
	TeamKind     string
}

func (q *Queries) GetAgent(ctx context.Context, arg GetAgentParams) (GetAgentRow, error) {
	row := q.db.QueryRow(ctx, getAgent, arg.ID, arg.WorkspaceID)
	var i GetAgentRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TeamID,
		&i.Name,
		&i.Role,
		&i.Persona,
		&i.Tone,
		&i.Shape,
		&i.Color,
		&i.Status,
		&i.TemplateKey,
		&i.DefaultModel,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Tools,
		&i.TeamName,
		&i.TeamKind,
	)
	return i, err
}

const getAgentTemplate = `-- name: GetAgentTemplate :one
SELECT id, key, name, role, persona, tone, shape, color, tools, integrations, default_model, sort_order, created_at FROM agent_templates WHERE key = $1
`

func (q *Queries) GetAgentTemplate(ctx context.Context, key string) (AgentTemplate, error) {
	row := q.db.QueryRow(ctx, getAgentTemplate, key)
	var i AgentTemplate
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Role,
		&i.Persona,
		&i.Tone,
		&i.Shape,
		&i.Color,
		&i.Tools,
		&i.Integrations,
		&i.DefaultModel,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const latestPendingDraftForAgent = `-- name: LatestPendingDraftForAgent :one
SELECT id, action_kind, created_at
FROM drafts
WHERE agent_id = $1 AND status = 'pending'
ORDER BY created_at DESC
LIMIT 1
`

type LatestPendingDraftForAgentRow struct {
	ID         uuid.UUID
	ActionKind string
	CreatedAt  time.Time
}

func (q *Queries) LatestPendingDraftForAgent(ctx context.Context, agentID uuid.UUID) (LatestPendingDraftForAgentRow, error) {
	row := q.db.QueryRow(ctx, latestPendingDraftForAgent, agentID)
	var i LatestPendingDraftForAgentRow
	err := row.Scan(&i.ID, &i.ActionKind, &i.CreatedAt)
	return i, err
}

const latestTaskForAgent = `-- name: LatestTaskForAgent :one
SELECT id, title, status, created_at
FROM tasks
WHERE agent_id = $1 AND status IN ('queued', 'running')
ORDER BY created_at DESC
LIMIT 1
`

type LatestTaskForAgentRow struct {
	ID        uuid.UUID
	Title     string
	Status    string
	CreatedAt time.Time
}

// The "why" behind a derived status, shown next to the Bolu in the UI.
func (q *Queries) LatestTaskForAgent(ctx context.Context, agentID uuid.UUID) (LatestTaskForAgentRow, error) {
	row := q.db.QueryRow(ctx, latestTaskForAgent, agentID)
	var i LatestTaskForAgentRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listAgentTemplates = `-- name: ListAgentTemplates :many

SELECT id, key, name, role, persona, tone, shape, color, tools, integrations, default_model, sort_order, created_at FROM agent_templates ORDER BY sort_order
`

// ------------------------------------------------------------------ templates
// Not tenant data: the same six profiles for every workspace.
func (q *Queries) ListAgentTemplates(ctx context.Context) ([]AgentTemplate, error) {
	rows, err := q.db.Query(ctx, listAgentTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentTemplate{}
	for rows.Next() {
		var i AgentTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Name,
			&i.Role,
			&i.Persona,
			&i.Tone,
			&i.Shape,
			&i.Color,
			&i.Tools,
			&i.Integrations,
			&i.DefaultModel,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgents = `-- name: ListAgents :many
SELECT a.id, a.workspace_id, a.team_id, a.name, a.role, a.persona, a.tone, a.shape, a.color, a.status, a.template_key, a.default_model, a.created_at, a.updated_at, a.deleted_at, a.tools, t.name AS team_name, t.kind AS team_kind
FROM agents a
JOIN teams t ON t.id = a.team_id
WHERE a.workspace_id = $1 AND a.deleted_at IS NULL
ORDER BY t.name, a.created_at
`

type ListAgentsRow struct {
	ID           uuid.UUID
	WorkspaceID  uuid.UUID
	TeamID       uuid.UUID
	Name         string
	Role         string
	Persona      string
	Tone         string
	Shape        string
	Color        string
	Status       string
	TemplateKey  string
	DefaultModel []byte
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    *time.Time
	Tools        []byte
	TeamName     string
	TeamKind     string
}

// The registry. Soft-deleted Bolu are invisible, and the team is joined so the
// list can be grouped without a second query.
func (q *Queries) ListAgents(ctx context.Context, workspaceID uuid.UUID) ([]ListAgentsRow, error) {
	rows, err := q.db.Query(ctx, listAgents, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgentsRow{}
	for rows.Next() {
		var i ListAgentsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.TeamID,
			&i.Name,
			&i.Role,
			&i.Persona,
			&i.Tone,
			&i.Shape,
			&i.Color,
			&i.Status,
			&i.TemplateKey,
			&i.DefaultModel,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Tools,
			&i.TeamName,
			&i.TeamKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrants = `-- name: ListGrants :many

SELECT g.id, g.agent_id, g.integration_id, g.permission, g.created_at, g.updated_at,
       i.app AS integration_app, i.account_label, i.status AS integration_status
FROM agent_grants g
JOIN integrations i ON i.id = g.integration_id
WHERE g.workspace_id = $1 AND g.agent_id = $2
ORDER BY i.app
`

type ListGrantsParams struct {
	WorkspaceID uuid.UUID
	AgentID     uuid.UUID
}

type ListGrantsRow struct {
	ID                uuid.UUID
	AgentID           uuid.UUID
	IntegrationID     uuid.UUID
	Permission        string
	CreatedAt         time.Time
	UpdatedAt         time.Time
	IntegrationApp    string
	AccountLabel      string
	IntegrationStatus string
}

// ------------------------------------------------------------------- grants
func (q *Queries) ListGrants(ctx context.Context, arg ListGrantsParams) ([]ListGrantsRow, error) {
	rows, err := q.db.Query(ctx, listGrants, arg.WorkspaceID, arg.AgentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGrantsRow{}
	for rows.Next() {
		var i ListGrantsRow
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.IntegrationID,
			&i.Permission,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IntegrationApp,
			&i.AccountLabel,
			&i.IntegrationStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIntegrations = `-- name: ListIntegrations :many
SELECT id, workspace_id, app, account_label, status, scopes, access_token_encrypted, refresh_token_encrypted, token_expires_at, data_key_wrapped, data_key_kms_key_id, created_at, updated_at FROM integrations WHERE workspace_id = $1 ORDER BY app, account_label
`

// The integrations of the workspace, which the grant screen lists.
func (q *Queries) ListIntegrations(ctx context.Context, workspaceID uuid.UUID) ([]Integration, error) {
	rows, err := q.db.Query(ctx, listIntegrations, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Integration{}
	for rows.Next() {
		var i Integration
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.App,
			&i.AccountLabel,
			&i.Status,
			&i.Scopes,
			&i.AccessTokenEncrypted,
			&i.RefreshTokenEncrypted,
			&i.TokenExpiresAt,
			&i.DataKeyWrapped,
			&i.DataKeyKmsKeyID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listToolCatalog = `-- name: ListToolCatalog :many
SELECT name, integration_app, label, description, created_at FROM tool_catalog ORDER BY integration_app, name
`

func (q *Queries) ListToolCatalog(ctx context.Context) ([]ToolCatalog, error) {
	rows, err := q.db.Query(ctx, listToolCatalog)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ToolCatalog{}
	for rows.Next() {
		var i ToolCatalog
		if err := rows.Scan(
			&i.Name,
			&i.IntegrationApp,
			&i.Label,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceTeams = `-- name: ListWorkspaceTeams :many
SELECT id, workspace_id, name, kind, created_at, updated_at FROM teams WHERE workspace_id = $1 ORDER BY name
`

// The teams of the workspace, which the registry groups its Bolu by.
func (q *Queries) ListWorkspaceTeams(ctx context.Context, workspaceID uuid.UUID) ([]Team, error) {
	rows, err := q.db.Query(ctx, listWorkspaceTeams, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Team{}
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Kind,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveAgentToTeam = `-- name: MoveAgentToTeam :one
UPDATE agents
SET team_id = $3, updated_at = now()
WHERE id = $1 AND workspace_id = $2 AND deleted_at IS NULL
RETURNING id, workspace_id, team_id, name, role, persona, tone, shape, color, status, template_key, default_model, created_at, updated_at, deleted_at, tools
`

type MoveAgentToTeamParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	TeamID      uuid.UUID
}

func (q *Queries) MoveAgentToTeam(ctx context.Context, arg MoveAgentToTeamParams) (Agent, error) {
	row := q.db.QueryRow(ctx, moveAgentToTeam, arg.ID, arg.WorkspaceID, arg.TeamID)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TeamID,
		&i.Name,
		&i.Role,
		&i.Persona,
		&i.Tone,
		&i.Shape,
		&i.Color,
		&i.Status,
		&i.TemplateKey,
		&i.DefaultModel,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Tools,
	)
	return i, err
}

const setAgentStatus = `-- name: SetAgentStatus :one
UPDATE agents
SET status = $3, updated_at = now()
WHERE id = $1 AND workspace_id = $2 AND deleted_at IS NULL
RETURNING id, workspace_id, team_id, name, role, persona, tone, shape, color, status, template_key, default_model, created_at, updated_at, deleted_at, tools
`

type SetAgentStatusParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Status      string
}

// The rest switch. The display status is never stored; see AgentActivity.
func (q *Queries) SetAgentStatus(ctx context.Context, arg SetAgentStatusParams) (Agent, error) {
	row := q.db.QueryRow(ctx, setAgentStatus, arg.ID, arg.WorkspaceID, arg.Status)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TeamID,
		&i.Name,
		&i.Role,
		&i.Persona,
		&i.Tone,
		&i.Shape,
		&i.Color,
		&i.Status,
		&i.TemplateKey,
		&i.DefaultModel,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Tools,
	)
	return i, err
}

const softDeleteAgent = `-- name: SoftDeleteAgent :execrows
UPDATE agents
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND workspace_id = $2 AND deleted_at IS NULL
`

type SoftDeleteAgentParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) SoftDeleteAgent(ctx context.Context, arg SoftDeleteAgentParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteAgent, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAgent = `-- name: UpdateAgent :one
UPDATE agents
SET name = $3,
    role = $4,
    persona = $5,
    tone = $6,
    shape = $7,
    color = $8,
    tools = $9,
    default_model = $10,
    updated_at = now()
WHERE id = $1 AND workspace_id = $2 AND deleted_at IS NULL
RETURNING id, workspace_id, team_id, name, role, persona, tone, shape, color, status, template_key, default_model, created_at, updated_at, deleted_at, tools
`

type UpdateAgentParams struct {
	ID           uuid.UUID
	WorkspaceID  uuid.UUID
	Name         string
	Role         string
	Persona      string
	Tone         string
	Shape        string
	Color        string
	Tools        []byte
	DefaultModel []byte
}

// Only the editable profile. The team is changed through MoveAgent so the
// workspace_id guard stays in one place.
func (q *Queries) UpdateAgent(ctx context.Context, arg UpdateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, updateAgent,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Role,
		arg.Persona,
		arg.Tone,
		arg.Shape,
		arg.Color,
		arg.Tools,
		arg.DefaultModel,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TeamID,
		&i.Name,
		&i.Role,
		&i.Persona,
		&i.Tone,
		&i.Shape,
		&i.Color,
		&i.Status,
		&i.TemplateKey,
		&i.DefaultModel,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Tools,
	)
	return i, err
}

const upsertGrant = `-- name: UpsertGrant :one
INSERT INTO agent_grants (workspace_id, agent_id, integration_id, permission)
VALUES ($1, $2, $3, $4)
ON CONFLICT (agent_id, integration_id)
DO UPDATE SET permission = EXCLUDED.permission, updated_at = now()
RETURNING id, workspace_id, agent_id, integration_id, permission, created_at, updated_at
`

type UpsertGrantParams struct {
	WorkspaceID   uuid.UUID
	AgentID       uuid.UUID
	IntegrationID uuid.UUID
	Permission    string
}

func (q *Queries) UpsertGrant(ctx context.Context, arg UpsertGrantParams) (AgentGrant, error) {
	row := q.db.QueryRow(ctx, upsertGrant,
		arg.WorkspaceID,
		arg.AgentID,
		arg.IntegrationID,
		arg.Permission,
	)
	var i AgentGrant
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AgentID,
		&i.IntegrationID,
		&i.Permission,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
