// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_override.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const getAgentModelOverride = `-- name: GetAgentModelOverride :one

SELECT default_model FROM agents
WHERE id = $1 AND workspace_id = $2 AND deleted_at IS NULL
`

type GetAgentModelOverrideParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

// The per-Bolu model override.
//
// It lives in agents.default_model, which the agent module owns, because that is
// where the profile it belongs to is stored. The shape of the value is this
// module's concern: the provider id, the model, and the sealed per-Bolu key. The
// agent registry treats the column as an opaque JSONB document and never reads
// into it, which is why the two modules do not disagree about its contents.
func (q *Queries) GetAgentModelOverride(ctx context.Context, arg GetAgentModelOverrideParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getAgentModelOverride, arg.ID, arg.WorkspaceID)
	var default_model []byte
	err := row.Scan(&default_model)
	return default_model, err
}

const setAgentModelOverride = `-- name: SetAgentModelOverride :execrows
UPDATE agents
SET default_model = $3, updated_at = now()
WHERE id = $1 AND workspace_id = $2 AND deleted_at IS NULL
`

type SetAgentModelOverrideParams struct {
	ID           uuid.UUID
	WorkspaceID  uuid.UUID
	DefaultModel []byte
}

func (q *Queries) SetAgentModelOverride(ctx context.Context, arg SetAgentModelOverrideParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAgentModelOverride, arg.ID, arg.WorkspaceID, arg.DefaultModel)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
