// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: provider.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const clearDefaultProviders = `-- name: ClearDefaultProviders :execrows
UPDATE llm_providers
SET is_default = false, updated_at = now()
WHERE workspace_id = $1 AND id <> $2 AND is_default
`

type ClearDefaultProvidersParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

// At most one default exists (partial unique index), so a new default is set by
// clearing the others in the same transaction.
func (q *Queries) ClearDefaultProviders(ctx context.Context, arg ClearDefaultProvidersParams) (int64, error) {
	result, err := q.db.Exec(ctx, clearDefaultProviders, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createProvider = `-- name: CreateProvider :one
INSERT INTO llm_providers (
    workspace_id, name, adapter, base_url, model, api_key_encrypted,
    priority, max_tokens, context_tokens, is_default, enabled
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, workspace_id, name, adapter, base_url, model, api_key_encrypted, priority, max_tokens, context_tokens, is_default, enabled, created_at, updated_at
`

type CreateProviderParams struct {
	WorkspaceID     uuid.UUID
	Name            string
	Adapter         string
	BaseUrl         string
	Model           string
	ApiKeyEncrypted []byte
	Priority        int32
	MaxTokens       int32
	ContextTokens   int32
	IsDefault       bool
	Enabled         bool
}

func (q *Queries) CreateProvider(ctx context.Context, arg CreateProviderParams) (LlmProvider, error) {
	row := q.db.QueryRow(ctx, createProvider,
		arg.WorkspaceID,
		arg.Name,
		arg.Adapter,
		arg.BaseUrl,
		arg.Model,
		arg.ApiKeyEncrypted,
		arg.Priority,
		arg.MaxTokens,
		arg.ContextTokens,
		arg.IsDefault,
		arg.Enabled,
	)
	var i LlmProvider
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Adapter,
		&i.BaseUrl,
		&i.Model,
		&i.ApiKeyEncrypted,
		&i.Priority,
		&i.MaxTokens,
		&i.ContextTokens,
		&i.IsDefault,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProvider = `-- name: DeleteProvider :execrows
DELETE FROM llm_providers WHERE id = $1 AND workspace_id = $2
`

type DeleteProviderParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) DeleteProvider(ctx context.Context, arg DeleteProviderParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProvider, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProvider = `-- name: GetProvider :one
SELECT id, workspace_id, name, adapter, base_url, model, api_key_encrypted, priority, max_tokens, context_tokens, is_default, enabled, created_at, updated_at FROM llm_providers WHERE id = $1 AND workspace_id = $2
`

type GetProviderParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) GetProvider(ctx context.Context, arg GetProviderParams) (LlmProvider, error) {
	row := q.db.QueryRow(ctx, getProvider, arg.ID, arg.WorkspaceID)
	var i LlmProvider
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Adapter,
		&i.BaseUrl,
		&i.Model,
		&i.ApiKeyEncrypted,
		&i.Priority,
		&i.MaxTokens,
		&i.ContextTokens,
		&i.IsDefault,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProviders = `-- name: ListProviders :many

SELECT id, workspace_id, name, adapter, base_url, model, api_key_encrypted, priority, max_tokens, context_tokens, is_default, enabled, created_at, updated_at FROM llm_providers
WHERE workspace_id = $1
ORDER BY is_default DESC, priority, created_at
`

// Provider configuration of a workspace. Every query is scoped by workspace_id
// as well as by the Row Level Security policy, so a wrong id in application
// code still cannot reach another tenant's row.
// The settings screen: every provider, the default first and then the fallback
// order. Disabled ones are included, because the screen shows them greyed out.
func (q *Queries) ListProviders(ctx context.Context, workspaceID uuid.UUID) ([]LlmProvider, error) {
	rows, err := q.db.Query(ctx, listProviders, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LlmProvider{}
	for rows.Next() {
		var i LlmProvider
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Adapter,
			&i.BaseUrl,
			&i.Model,
			&i.ApiKeyEncrypted,
			&i.Priority,
			&i.MaxTokens,
			&i.ContextTokens,
			&i.IsDefault,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProvider = `-- name: UpdateProvider :one
UPDATE llm_providers
SET name = $3,
    adapter = $4,
    base_url = $5,
    model = $6,
    api_key_encrypted = CASE
        WHEN $12::bytea IS NULL THEN api_key_encrypted
        ELSE NULLIF($12::bytea, ''::bytea)
    END,
    priority = $7,
    max_tokens = $8,
    context_tokens = $9,
    is_default = $10,
    enabled = $11,
    updated_at = now()
WHERE id = $1 AND workspace_id = $2
RETURNING id, workspace_id, name, adapter, base_url, model, api_key_encrypted, priority, max_tokens, context_tokens, is_default, enabled, created_at, updated_at
`

type UpdateProviderParams struct {
	ID              uuid.UUID
	WorkspaceID     uuid.UUID
	Name            string
	Adapter         string
	BaseUrl         string
	Model           string
	Priority        int32
	MaxTokens       int32
	ContextTokens   int32
	IsDefault       bool
	Enabled         bool
	ApiKeyEncrypted []byte
}

// The key has three states, and they are not the same thing:
//
//	NULL   → keep the stored key (the settings screen never receives the secret
//	         back, so it cannot send it again; renaming must not wipe it);
//	''     → clear the key (the operator removed it);
//	bytes  → replace it with this ciphertext.
func (q *Queries) UpdateProvider(ctx context.Context, arg UpdateProviderParams) (LlmProvider, error) {
	row := q.db.QueryRow(ctx, updateProvider,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Adapter,
		arg.BaseUrl,
		arg.Model,
		arg.Priority,
		arg.MaxTokens,
		arg.ContextTokens,
		arg.IsDefault,
		arg.Enabled,
		arg.ApiKeyEncrypted,
	)
	var i LlmProvider
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Adapter,
		&i.BaseUrl,
		&i.Model,
		&i.ApiKeyEncrypted,
		&i.Priority,
		&i.MaxTokens,
		&i.ContextTokens,
		&i.IsDefault,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
