// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usage.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertUsageEntry = `-- name: InsertUsageEntry :one

INSERT INTO usage_ledger (
    workspace_id, agent_id, task_id, provider, model, purpose,
    input_tokens, output_tokens, cache_read_tokens, cache_write_tokens, cost_micros
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, created_at
`

type InsertUsageEntryParams struct {
	WorkspaceID      uuid.UUID
	AgentID          *uuid.UUID
	TaskID           *uuid.UUID
	Provider         string
	Model            string
	Purpose          string
	InputTokens      int32
	OutputTokens     int32
	CacheReadTokens  int32
	CacheWriteTokens int32
	CostMicros       int64
}

type InsertUsageEntryRow struct {
	ID        int64
	CreatedAt time.Time
}

// Usage ledger access: the write that every provider call makes, and the daily
// aggregation the dashboard and the quota screen read.
// One row per provider call. This is the audit trail of what a workspace spent,
// so it is inserted even when the call later failed to be useful.
func (q *Queries) InsertUsageEntry(ctx context.Context, arg InsertUsageEntryParams) (InsertUsageEntryRow, error) {
	row := q.db.QueryRow(ctx, insertUsageEntry,
		arg.WorkspaceID,
		arg.AgentID,
		arg.TaskID,
		arg.Provider,
		arg.Model,
		arg.Purpose,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CacheReadTokens,
		arg.CacheWriteTokens,
		arg.CostMicros,
	)
	var i InsertUsageEntryRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const listDailyUsage = `-- name: ListDailyUsage :many
SELECT workspace_id, day, provider, model, purpose, calls, input_tokens, output_tokens, cache_read_tokens, cache_write_tokens, cost_micros FROM usage_daily
WHERE workspace_id = $1 AND day >= $2
ORDER BY day DESC, provider, model
`

type ListDailyUsageParams struct {
	WorkspaceID uuid.UUID
	Day         time.Time
}

// Per-day totals, most recent first. Days follow Asia/Jakarta, which is where
// the customers are.
func (q *Queries) ListDailyUsage(ctx context.Context, arg ListDailyUsageParams) ([]UsageDaily, error) {
	rows, err := q.db.Query(ctx, listDailyUsage, arg.WorkspaceID, arg.Day)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsageDaily{}
	for rows.Next() {
		var i UsageDaily
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.Day,
			&i.Provider,
			&i.Model,
			&i.Purpose,
			&i.Calls,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheReadTokens,
			&i.CacheWriteTokens,
			&i.CostMicros,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumTokensSince = `-- name: SumTokensSince :one
SELECT COALESCE(sum(input_tokens + output_tokens), 0)::bigint AS tokens
FROM usage_ledger
WHERE workspace_id = $1 AND created_at >= $2
`

type SumTokensSinceParams struct {
	WorkspaceID uuid.UUID
	CreatedAt   time.Time
}

// The durable quota fallback: the live counter lives in Redis, but a Redis
// restart must not silently grant a fresh allowance.
func (q *Queries) SumTokensSince(ctx context.Context, arg SumTokensSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, sumTokensSince, arg.WorkspaceID, arg.CreatedAt)
	var tokens int64
	err := row.Scan(&tokens)
	return tokens, err
}
