// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/robzlabz/employeebot/apps/backend/internal/modules/chat/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// AgentDirectory is an autogenerated mock type for the AgentDirectory type
type AgentDirectory struct {
	mock.Mock
}

type AgentDirectory_Expecter struct {
	mock *mock.Mock
}

func (_m *AgentDirectory) EXPECT() *AgentDirectory_Expecter {
	return &AgentDirectory_Expecter{mock: &_m.Mock}
}

// Active provides a mock function with given fields: ref
func (_m *AgentDirectory) Active(ref domain.AgentRef) bool {
	ret := _m.Called(ref)

	if len(ret) == 0 {
		panic("no return value specified for Active")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(domain.AgentRef) bool); ok {
		r0 = rf(ref)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// AgentDirectory_Active_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Active'
type AgentDirectory_Active_Call struct {
	*mock.Call
}

// Active is a helper method to define mock.On call
//   - ref domain.AgentRef
func (_e *AgentDirectory_Expecter) Active(ref interface{}) *AgentDirectory_Active_Call {
	return &AgentDirectory_Active_Call{Call: _e.mock.On("Active", ref)}
}

func (_c *AgentDirectory_Active_Call) Run(run func(ref domain.AgentRef)) *AgentDirectory_Active_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(domain.AgentRef))
	})
	return _c
}

func (_c *AgentDirectory_Active_Call) Return(_a0 bool) *AgentDirectory_Active_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AgentDirectory_Active_Call) RunAndReturn(run func(domain.AgentRef) bool) *AgentDirectory_Active_Call {
	_c.Call.Return(run)
	return _c
}

// Agent provides a mock function with given fields: ctx, scope, id
func (_m *AgentDirectory) Agent(ctx context.Context, scope domain.Scope, id uuid.UUID) (domain.AgentRef, error) {
	ret := _m.Called(ctx, scope, id)

	if len(ret) == 0 {
		panic("no return value specified for Agent")
	}

	var r0 domain.AgentRef
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, uuid.UUID) (domain.AgentRef, error)); ok {
		return rf(ctx, scope, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, uuid.UUID) domain.AgentRef); ok {
		r0 = rf(ctx, scope, id)
	} else {
		r0 = ret.Get(0).(domain.AgentRef)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Scope, uuid.UUID) error); ok {
		r1 = rf(ctx, scope, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AgentDirectory_Agent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Agent'
type AgentDirectory_Agent_Call struct {
	*mock.Call
}

// Agent is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
//   - id uuid.UUID
func (_e *AgentDirectory_Expecter) Agent(ctx interface{}, scope interface{}, id interface{}) *AgentDirectory_Agent_Call {
	return &AgentDirectory_Agent_Call{Call: _e.mock.On("Agent", ctx, scope, id)}
}

func (_c *AgentDirectory_Agent_Call) Run(run func(ctx context.Context, scope domain.Scope, id uuid.UUID)) *AgentDirectory_Agent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *AgentDirectory_Agent_Call) Return(_a0 domain.AgentRef, _a1 error) *AgentDirectory_Agent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AgentDirectory_Agent_Call) RunAndReturn(run func(context.Context, domain.Scope, uuid.UUID) (domain.AgentRef, error)) *AgentDirectory_Agent_Call {
	_c.Call.Return(run)
	return _c
}

// Agents provides a mock function with given fields: ctx, scope, ids
func (_m *AgentDirectory) Agents(ctx context.Context, scope domain.Scope, ids []uuid.UUID) ([]domain.AgentRef, error) {
	ret := _m.Called(ctx, scope, ids)

	if len(ret) == 0 {
		panic("no return value specified for Agents")
	}

	var r0 []domain.AgentRef
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, []uuid.UUID) ([]domain.AgentRef, error)); ok {
		return rf(ctx, scope, ids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, []uuid.UUID) []domain.AgentRef); ok {
		r0 = rf(ctx, scope, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.AgentRef)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Scope, []uuid.UUID) error); ok {
		r1 = rf(ctx, scope, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AgentDirectory_Agents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Agents'
type AgentDirectory_Agents_Call struct {
	*mock.Call
}

// Agents is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
//   - ids []uuid.UUID
func (_e *AgentDirectory_Expecter) Agents(ctx interface{}, scope interface{}, ids interface{}) *AgentDirectory_Agents_Call {
	return &AgentDirectory_Agents_Call{Call: _e.mock.On("Agents", ctx, scope, ids)}
}

func (_c *AgentDirectory_Agents_Call) Run(run func(ctx context.Context, scope domain.Scope, ids []uuid.UUID)) *AgentDirectory_Agents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope), args[2].([]uuid.UUID))
	})
	return _c
}

func (_c *AgentDirectory_Agents_Call) Return(_a0 []domain.AgentRef, _a1 error) *AgentDirectory_Agents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AgentDirectory_Agents_Call) RunAndReturn(run func(context.Context, domain.Scope, []uuid.UUID) ([]domain.AgentRef, error)) *AgentDirectory_Agents_Call {
	_c.Call.Return(run)
	return _c
}

// NewAgentDirectory creates a new instance of AgentDirectory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAgentDirectory(t interface {
	mock.TestingT
	Cleanup(func())
}) *AgentDirectory {
	mock := &AgentDirectory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
