// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/robzlabz/employeebot/apps/backend/internal/modules/chat/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// AttachmentRepository is an autogenerated mock type for the AttachmentRepository type
type AttachmentRepository struct {
	mock.Mock
}

type AttachmentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *AttachmentRepository) EXPECT() *AttachmentRepository_Expecter {
	return &AttachmentRepository_Expecter{mock: &_m.Mock}
}

// ListForMessage provides a mock function with given fields: ctx, scope, messageID
func (_m *AttachmentRepository) ListForMessage(ctx context.Context, scope domain.Scope, messageID uuid.UUID) ([]domain.Attachment, error) {
	ret := _m.Called(ctx, scope, messageID)

	if len(ret) == 0 {
		panic("no return value specified for ListForMessage")
	}

	var r0 []domain.Attachment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, uuid.UUID) ([]domain.Attachment, error)); ok {
		return rf(ctx, scope, messageID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, uuid.UUID) []domain.Attachment); ok {
		r0 = rf(ctx, scope, messageID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Attachment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Scope, uuid.UUID) error); ok {
		r1 = rf(ctx, scope, messageID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AttachmentRepository_ListForMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListForMessage'
type AttachmentRepository_ListForMessage_Call struct {
	*mock.Call
}

// ListForMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
//   - messageID uuid.UUID
func (_e *AttachmentRepository_Expecter) ListForMessage(ctx interface{}, scope interface{}, messageID interface{}) *AttachmentRepository_ListForMessage_Call {
	return &AttachmentRepository_ListForMessage_Call{Call: _e.mock.On("ListForMessage", ctx, scope, messageID)}
}

func (_c *AttachmentRepository_ListForMessage_Call) Run(run func(ctx context.Context, scope domain.Scope, messageID uuid.UUID)) *AttachmentRepository_ListForMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *AttachmentRepository_ListForMessage_Call) Return(_a0 []domain.Attachment, _a1 error) *AttachmentRepository_ListForMessage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AttachmentRepository_ListForMessage_Call) RunAndReturn(run func(context.Context, domain.Scope, uuid.UUID) ([]domain.Attachment, error)) *AttachmentRepository_ListForMessage_Call {
	_c.Call.Return(run)
	return _c
}

// Open provides a mock function with given fields: ctx, scope, id
func (_m *AttachmentRepository) Open(ctx context.Context, scope domain.Scope, id uuid.UUID) (domain.Attachment, error) {
	ret := _m.Called(ctx, scope, id)

	if len(ret) == 0 {
		panic("no return value specified for Open")
	}

	var r0 domain.Attachment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, uuid.UUID) (domain.Attachment, error)); ok {
		return rf(ctx, scope, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, uuid.UUID) domain.Attachment); ok {
		r0 = rf(ctx, scope, id)
	} else {
		r0 = ret.Get(0).(domain.Attachment)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Scope, uuid.UUID) error); ok {
		r1 = rf(ctx, scope, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AttachmentRepository_Open_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Open'
type AttachmentRepository_Open_Call struct {
	*mock.Call
}

// Open is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
//   - id uuid.UUID
func (_e *AttachmentRepository_Expecter) Open(ctx interface{}, scope interface{}, id interface{}) *AttachmentRepository_Open_Call {
	return &AttachmentRepository_Open_Call{Call: _e.mock.On("Open", ctx, scope, id)}
}

func (_c *AttachmentRepository_Open_Call) Run(run func(ctx context.Context, scope domain.Scope, id uuid.UUID)) *AttachmentRepository_Open_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *AttachmentRepository_Open_Call) Return(_a0 domain.Attachment, _a1 error) *AttachmentRepository_Open_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AttachmentRepository_Open_Call) RunAndReturn(run func(context.Context, domain.Scope, uuid.UUID) (domain.Attachment, error)) *AttachmentRepository_Open_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, scope, attachment, content
func (_m *AttachmentRepository) Save(ctx context.Context, scope domain.Scope, attachment domain.Attachment, content []byte) (domain.Attachment, error) {
	ret := _m.Called(ctx, scope, attachment, content)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 domain.Attachment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, domain.Attachment, []byte) (domain.Attachment, error)); ok {
		return rf(ctx, scope, attachment, content)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, domain.Attachment, []byte) domain.Attachment); ok {
		r0 = rf(ctx, scope, attachment, content)
	} else {
		r0 = ret.Get(0).(domain.Attachment)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Scope, domain.Attachment, []byte) error); ok {
		r1 = rf(ctx, scope, attachment, content)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AttachmentRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type AttachmentRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
//   - attachment domain.Attachment
//   - content []byte
func (_e *AttachmentRepository_Expecter) Save(ctx interface{}, scope interface{}, attachment interface{}, content interface{}) *AttachmentRepository_Save_Call {
	return &AttachmentRepository_Save_Call{Call: _e.mock.On("Save", ctx, scope, attachment, content)}
}

func (_c *AttachmentRepository_Save_Call) Run(run func(ctx context.Context, scope domain.Scope, attachment domain.Attachment, content []byte)) *AttachmentRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope), args[2].(domain.Attachment), args[3].([]byte))
	})
	return _c
}

func (_c *AttachmentRepository_Save_Call) Return(_a0 domain.Attachment, _a1 error) *AttachmentRepository_Save_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AttachmentRepository_Save_Call) RunAndReturn(run func(context.Context, domain.Scope, domain.Attachment, []byte) (domain.Attachment, error)) *AttachmentRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewAttachmentRepository creates a new instance of AttachmentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAttachmentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AttachmentRepository {
	mock := &AttachmentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
