// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/robzlabz/employeebot/apps/backend/internal/modules/chat/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MessageRepository is an autogenerated mock type for the MessageRepository type
type MessageRepository struct {
	mock.Mock
}

type MessageRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MessageRepository) EXPECT() *MessageRepository_Expecter {
	return &MessageRepository_Expecter{mock: &_m.Mock}
}

// Append provides a mock function with given fields: ctx, scope, message
func (_m *MessageRepository) Append(ctx context.Context, scope domain.Scope, message domain.Message) (domain.Message, error) {
	ret := _m.Called(ctx, scope, message)

	if len(ret) == 0 {
		panic("no return value specified for Append")
	}

	var r0 domain.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, domain.Message) (domain.Message, error)); ok {
		return rf(ctx, scope, message)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, domain.Message) domain.Message); ok {
		r0 = rf(ctx, scope, message)
	} else {
		r0 = ret.Get(0).(domain.Message)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Scope, domain.Message) error); ok {
		r1 = rf(ctx, scope, message)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MessageRepository_Append_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Append'
type MessageRepository_Append_Call struct {
	*mock.Call
}

// Append is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
//   - message domain.Message
func (_e *MessageRepository_Expecter) Append(ctx interface{}, scope interface{}, message interface{}) *MessageRepository_Append_Call {
	return &MessageRepository_Append_Call{Call: _e.mock.On("Append", ctx, scope, message)}
}

func (_c *MessageRepository_Append_Call) Run(run func(ctx context.Context, scope domain.Scope, message domain.Message)) *MessageRepository_Append_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope), args[2].(domain.Message))
	})
	return _c
}

func (_c *MessageRepository_Append_Call) Return(_a0 domain.Message, _a1 error) *MessageRepository_Append_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MessageRepository_Append_Call) RunAndReturn(run func(context.Context, domain.Scope, domain.Message) (domain.Message, error)) *MessageRepository_Append_Call {
	_c.Call.Return(run)
	return _c
}

// GetMessage provides a mock function with given fields: ctx, scope, id
func (_m *MessageRepository) GetMessage(ctx context.Context, scope domain.Scope, id uuid.UUID) (domain.Message, error) {
	ret := _m.Called(ctx, scope, id)

	if len(ret) == 0 {
		panic("no return value specified for GetMessage")
	}

	var r0 domain.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, uuid.UUID) (domain.Message, error)); ok {
		return rf(ctx, scope, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, uuid.UUID) domain.Message); ok {
		r0 = rf(ctx, scope, id)
	} else {
		r0 = ret.Get(0).(domain.Message)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Scope, uuid.UUID) error); ok {
		r1 = rf(ctx, scope, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MessageRepository_GetMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessage'
type MessageRepository_GetMessage_Call struct {
	*mock.Call
}

// GetMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
//   - id uuid.UUID
func (_e *MessageRepository_Expecter) GetMessage(ctx interface{}, scope interface{}, id interface{}) *MessageRepository_GetMessage_Call {
	return &MessageRepository_GetMessage_Call{Call: _e.mock.On("GetMessage", ctx, scope, id)}
}

func (_c *MessageRepository_GetMessage_Call) Run(run func(ctx context.Context, scope domain.Scope, id uuid.UUID)) *MessageRepository_GetMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MessageRepository_GetMessage_Call) Return(_a0 domain.Message, _a1 error) *MessageRepository_GetMessage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MessageRepository_GetMessage_Call) RunAndReturn(run func(context.Context, domain.Scope, uuid.UUID) (domain.Message, error)) *MessageRepository_GetMessage_Call {
	_c.Call.Return(run)
	return _c
}

// History provides a mock function with given fields: ctx, scope, conversationID, cursor
func (_m *MessageRepository) History(ctx context.Context, scope domain.Scope, conversationID uuid.UUID, cursor domain.Cursor) (domain.Page, error) {
	ret := _m.Called(ctx, scope, conversationID, cursor)

	if len(ret) == 0 {
		panic("no return value specified for History")
	}

	var r0 domain.Page
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, uuid.UUID, domain.Cursor) (domain.Page, error)); ok {
		return rf(ctx, scope, conversationID, cursor)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, uuid.UUID, domain.Cursor) domain.Page); ok {
		r0 = rf(ctx, scope, conversationID, cursor)
	} else {
		r0 = ret.Get(0).(domain.Page)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Scope, uuid.UUID, domain.Cursor) error); ok {
		r1 = rf(ctx, scope, conversationID, cursor)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MessageRepository_History_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'History'
type MessageRepository_History_Call struct {
	*mock.Call
}

// History is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
//   - conversationID uuid.UUID
//   - cursor domain.Cursor
func (_e *MessageRepository_Expecter) History(ctx interface{}, scope interface{}, conversationID interface{}, cursor interface{}) *MessageRepository_History_Call {
	return &MessageRepository_History_Call{Call: _e.mock.On("History", ctx, scope, conversationID, cursor)}
}

func (_c *MessageRepository_History_Call) Run(run func(ctx context.Context, scope domain.Scope, conversationID uuid.UUID, cursor domain.Cursor)) *MessageRepository_History_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope), args[2].(uuid.UUID), args[3].(domain.Cursor))
	})
	return _c
}

func (_c *MessageRepository_History_Call) Return(_a0 domain.Page, _a1 error) *MessageRepository_History_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MessageRepository_History_Call) RunAndReturn(run func(context.Context, domain.Scope, uuid.UUID, domain.Cursor) (domain.Page, error)) *MessageRepository_History_Call {
	_c.Call.Return(run)
	return _c
}

// LatestMessages provides a mock function with given fields: ctx, scope, conversationID, limit
func (_m *MessageRepository) LatestMessages(ctx context.Context, scope domain.Scope, conversationID uuid.UUID, limit int) ([]domain.Message, error) {
	ret := _m.Called(ctx, scope, conversationID, limit)

	if len(ret) == 0 {
		panic("no return value specified for LatestMessages")
	}

	var r0 []domain.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, uuid.UUID, int) ([]domain.Message, error)); ok {
		return rf(ctx, scope, conversationID, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, uuid.UUID, int) []domain.Message); ok {
		r0 = rf(ctx, scope, conversationID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Scope, uuid.UUID, int) error); ok {
		r1 = rf(ctx, scope, conversationID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MessageRepository_LatestMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LatestMessages'
type MessageRepository_LatestMessages_Call struct {
	*mock.Call
}

// LatestMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
//   - conversationID uuid.UUID
//   - limit int
func (_e *MessageRepository_Expecter) LatestMessages(ctx interface{}, scope interface{}, conversationID interface{}, limit interface{}) *MessageRepository_LatestMessages_Call {
	return &MessageRepository_LatestMessages_Call{Call: _e.mock.On("LatestMessages", ctx, scope, conversationID, limit)}
}

func (_c *MessageRepository_LatestMessages_Call) Run(run func(ctx context.Context, scope domain.Scope, conversationID uuid.UUID, limit int)) *MessageRepository_LatestMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope), args[2].(uuid.UUID), args[3].(int))
	})
	return _c
}

func (_c *MessageRepository_LatestMessages_Call) Return(_a0 []domain.Message, _a1 error) *MessageRepository_LatestMessages_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MessageRepository_LatestMessages_Call) RunAndReturn(run func(context.Context, domain.Scope, uuid.UUID, int) ([]domain.Message, error)) *MessageRepository_LatestMessages_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, scope, message
func (_m *MessageRepository) Update(ctx context.Context, scope domain.Scope, message domain.Message) (domain.Message, error) {
	ret := _m.Called(ctx, scope, message)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 domain.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, domain.Message) (domain.Message, error)); ok {
		return rf(ctx, scope, message)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, domain.Message) domain.Message); ok {
		r0 = rf(ctx, scope, message)
	} else {
		r0 = ret.Get(0).(domain.Message)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Scope, domain.Message) error); ok {
		r1 = rf(ctx, scope, message)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MessageRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MessageRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
//   - message domain.Message
func (_e *MessageRepository_Expecter) Update(ctx interface{}, scope interface{}, message interface{}) *MessageRepository_Update_Call {
	return &MessageRepository_Update_Call{Call: _e.mock.On("Update", ctx, scope, message)}
}

func (_c *MessageRepository_Update_Call) Run(run func(ctx context.Context, scope domain.Scope, message domain.Message)) *MessageRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope), args[2].(domain.Message))
	})
	return _c
}

func (_c *MessageRepository_Update_Call) Return(_a0 domain.Message, _a1 error) *MessageRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MessageRepository_Update_Call) RunAndReturn(run func(context.Context, domain.Scope, domain.Message) (domain.Message, error)) *MessageRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMessageRepository creates a new instance of MessageRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessageRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MessageRepository {
	mock := &MessageRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
