// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/robzlabz/employeebot/apps/backend/internal/modules/chat/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ConversationRepository is an autogenerated mock type for the ConversationRepository type
type ConversationRepository struct {
	mock.Mock
}

type ConversationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ConversationRepository) EXPECT() *ConversationRepository_Expecter {
	return &ConversationRepository_Expecter{mock: &_m.Mock}
}

// AddParticipants provides a mock function with given fields: ctx, scope, id, agentIDs, userIDs
func (_m *ConversationRepository) AddParticipants(ctx context.Context, scope domain.Scope, id uuid.UUID, agentIDs []uuid.UUID, userIDs []uuid.UUID) error {
	ret := _m.Called(ctx, scope, id, agentIDs, userIDs)

	if len(ret) == 0 {
		panic("no return value specified for AddParticipants")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, uuid.UUID, []uuid.UUID, []uuid.UUID) error); ok {
		r0 = rf(ctx, scope, id, agentIDs, userIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConversationRepository_AddParticipants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddParticipants'
type ConversationRepository_AddParticipants_Call struct {
	*mock.Call
}

// AddParticipants is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
//   - id uuid.UUID
//   - agentIDs []uuid.UUID
//   - userIDs []uuid.UUID
func (_e *ConversationRepository_Expecter) AddParticipants(ctx interface{}, scope interface{}, id interface{}, agentIDs interface{}, userIDs interface{}) *ConversationRepository_AddParticipants_Call {
	return &ConversationRepository_AddParticipants_Call{Call: _e.mock.On("AddParticipants", ctx, scope, id, agentIDs, userIDs)}
}

func (_c *ConversationRepository_AddParticipants_Call) Run(run func(ctx context.Context, scope domain.Scope, id uuid.UUID, agentIDs []uuid.UUID, userIDs []uuid.UUID)) *ConversationRepository_AddParticipants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope), args[2].(uuid.UUID), args[3].([]uuid.UUID), args[4].([]uuid.UUID))
	})
	return _c
}

func (_c *ConversationRepository_AddParticipants_Call) Return(_a0 error) *ConversationRepository_AddParticipants_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConversationRepository_AddParticipants_Call) RunAndReturn(run func(context.Context, domain.Scope, uuid.UUID, []uuid.UUID, []uuid.UUID) error) *ConversationRepository_AddParticipants_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, scope, kind, title, agentIDs, userIDs
func (_m *ConversationRepository) Create(ctx context.Context, scope domain.Scope, kind string, title string, agentIDs []uuid.UUID, userIDs []uuid.UUID) (domain.Conversation, error) {
	ret := _m.Called(ctx, scope, kind, title, agentIDs, userIDs)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Conversation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, string, string, []uuid.UUID, []uuid.UUID) (domain.Conversation, error)); ok {
		return rf(ctx, scope, kind, title, agentIDs, userIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, string, string, []uuid.UUID, []uuid.UUID) domain.Conversation); ok {
		r0 = rf(ctx, scope, kind, title, agentIDs, userIDs)
	} else {
		r0 = ret.Get(0).(domain.Conversation)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Scope, string, string, []uuid.UUID, []uuid.UUID) error); ok {
		r1 = rf(ctx, scope, kind, title, agentIDs, userIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConversationRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ConversationRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
//   - kind string
//   - title string
//   - agentIDs []uuid.UUID
//   - userIDs []uuid.UUID
func (_e *ConversationRepository_Expecter) Create(ctx interface{}, scope interface{}, kind interface{}, title interface{}, agentIDs interface{}, userIDs interface{}) *ConversationRepository_Create_Call {
	return &ConversationRepository_Create_Call{Call: _e.mock.On("Create", ctx, scope, kind, title, agentIDs, userIDs)}
}

func (_c *ConversationRepository_Create_Call) Run(run func(ctx context.Context, scope domain.Scope, kind string, title string, agentIDs []uuid.UUID, userIDs []uuid.UUID)) *ConversationRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope), args[2].(string), args[3].(string), args[4].([]uuid.UUID), args[5].([]uuid.UUID))
	})
	return _c
}

func (_c *ConversationRepository_Create_Call) Return(_a0 domain.Conversation, _a1 error) *ConversationRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConversationRepository_Create_Call) RunAndReturn(run func(context.Context, domain.Scope, string, string, []uuid.UUID, []uuid.UUID) (domain.Conversation, error)) *ConversationRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Direct provides a mock function with given fields: ctx, scope, agentID
func (_m *ConversationRepository) Direct(ctx context.Context, scope domain.Scope, agentID uuid.UUID) (domain.Conversation, error) {
	ret := _m.Called(ctx, scope, agentID)

	if len(ret) == 0 {
		panic("no return value specified for Direct")
	}

	var r0 domain.Conversation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, uuid.UUID) (domain.Conversation, error)); ok {
		return rf(ctx, scope, agentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, uuid.UUID) domain.Conversation); ok {
		r0 = rf(ctx, scope, agentID)
	} else {
		r0 = ret.Get(0).(domain.Conversation)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Scope, uuid.UUID) error); ok {
		r1 = rf(ctx, scope, agentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConversationRepository_Direct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Direct'
type ConversationRepository_Direct_Call struct {
	*mock.Call
}

// Direct is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
//   - agentID uuid.UUID
func (_e *ConversationRepository_Expecter) Direct(ctx interface{}, scope interface{}, agentID interface{}) *ConversationRepository_Direct_Call {
	return &ConversationRepository_Direct_Call{Call: _e.mock.On("Direct", ctx, scope, agentID)}
}

func (_c *ConversationRepository_Direct_Call) Run(run func(ctx context.Context, scope domain.Scope, agentID uuid.UUID)) *ConversationRepository_Direct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *ConversationRepository_Direct_Call) Return(_a0 domain.Conversation, _a1 error) *ConversationRepository_Direct_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConversationRepository_Direct_Call) RunAndReturn(run func(context.Context, domain.Scope, uuid.UUID) (domain.Conversation, error)) *ConversationRepository_Direct_Call {
	_c.Call.Return(run)
	return _c
}

// GetConversation provides a mock function with given fields: ctx, scope, id
func (_m *ConversationRepository) GetConversation(ctx context.Context, scope domain.Scope, id uuid.UUID) (domain.Conversation, error) {
	ret := _m.Called(ctx, scope, id)

	if len(ret) == 0 {
		panic("no return value specified for GetConversation")
	}

	var r0 domain.Conversation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, uuid.UUID) (domain.Conversation, error)); ok {
		return rf(ctx, scope, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, uuid.UUID) domain.Conversation); ok {
		r0 = rf(ctx, scope, id)
	} else {
		r0 = ret.Get(0).(domain.Conversation)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Scope, uuid.UUID) error); ok {
		r1 = rf(ctx, scope, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConversationRepository_GetConversation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConversation'
type ConversationRepository_GetConversation_Call struct {
	*mock.Call
}

// GetConversation is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
//   - id uuid.UUID
func (_e *ConversationRepository_Expecter) GetConversation(ctx interface{}, scope interface{}, id interface{}) *ConversationRepository_GetConversation_Call {
	return &ConversationRepository_GetConversation_Call{Call: _e.mock.On("GetConversation", ctx, scope, id)}
}

func (_c *ConversationRepository_GetConversation_Call) Run(run func(ctx context.Context, scope domain.Scope, id uuid.UUID)) *ConversationRepository_GetConversation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *ConversationRepository_GetConversation_Call) Return(_a0 domain.Conversation, _a1 error) *ConversationRepository_GetConversation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConversationRepository_GetConversation_Call) RunAndReturn(run func(context.Context, domain.Scope, uuid.UUID) (domain.Conversation, error)) *ConversationRepository_GetConversation_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, scope
func (_m *ConversationRepository) List(ctx context.Context, scope domain.Scope) ([]domain.Conversation, error) {
	ret := _m.Called(ctx, scope)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Conversation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope) ([]domain.Conversation, error)); ok {
		return rf(ctx, scope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope) []domain.Conversation); ok {
		r0 = rf(ctx, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Conversation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Scope) error); ok {
		r1 = rf(ctx, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConversationRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type ConversationRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
func (_e *ConversationRepository_Expecter) List(ctx interface{}, scope interface{}) *ConversationRepository_List_Call {
	return &ConversationRepository_List_Call{Call: _e.mock.On("List", ctx, scope)}
}

func (_c *ConversationRepository_List_Call) Run(run func(ctx context.Context, scope domain.Scope)) *ConversationRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope))
	})
	return _c
}

func (_c *ConversationRepository_List_Call) Return(_a0 []domain.Conversation, _a1 error) *ConversationRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConversationRepository_List_Call) RunAndReturn(run func(context.Context, domain.Scope) ([]domain.Conversation, error)) *ConversationRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Rename provides a mock function with given fields: ctx, scope, id, title
func (_m *ConversationRepository) Rename(ctx context.Context, scope domain.Scope, id uuid.UUID, title string) error {
	ret := _m.Called(ctx, scope, id, title)

	if len(ret) == 0 {
		panic("no return value specified for Rename")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, uuid.UUID, string) error); ok {
		r0 = rf(ctx, scope, id, title)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConversationRepository_Rename_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rename'
type ConversationRepository_Rename_Call struct {
	*mock.Call
}

// Rename is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
//   - id uuid.UUID
//   - title string
func (_e *ConversationRepository_Expecter) Rename(ctx interface{}, scope interface{}, id interface{}, title interface{}) *ConversationRepository_Rename_Call {
	return &ConversationRepository_Rename_Call{Call: _e.mock.On("Rename", ctx, scope, id, title)}
}

func (_c *ConversationRepository_Rename_Call) Run(run func(ctx context.Context, scope domain.Scope, id uuid.UUID, title string)) *ConversationRepository_Rename_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope), args[2].(uuid.UUID), args[3].(string))
	})
	return _c
}

func (_c *ConversationRepository_Rename_Call) Return(_a0 error) *ConversationRepository_Rename_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConversationRepository_Rename_Call) RunAndReturn(run func(context.Context, domain.Scope, uuid.UUID, string) error) *ConversationRepository_Rename_Call {
	_c.Call.Return(run)
	return _c
}

// NewConversationRepository creates a new instance of ConversationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConversationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConversationRepository {
	mock := &ConversationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
