// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/robzlabz/employeebot/apps/backend/internal/modules/chat/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// EventPublisher is an autogenerated mock type for the EventPublisher type
type EventPublisher struct {
	mock.Mock
}

type EventPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *EventPublisher) EXPECT() *EventPublisher_Expecter {
	return &EventPublisher_Expecter{mock: &_m.Mock}
}

// Publish provides a mock function with given fields: ctx, workspaceID, event
func (_m *EventPublisher) Publish(ctx context.Context, workspaceID uuid.UUID, event domain.Event) error {
	ret := _m.Called(ctx, workspaceID, event)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.Event) error); ok {
		r0 = rf(ctx, workspaceID, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EventPublisher_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type EventPublisher_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - workspaceID uuid.UUID
//   - event domain.Event
func (_e *EventPublisher_Expecter) Publish(ctx interface{}, workspaceID interface{}, event interface{}) *EventPublisher_Publish_Call {
	return &EventPublisher_Publish_Call{Call: _e.mock.On("Publish", ctx, workspaceID, event)}
}

func (_c *EventPublisher_Publish_Call) Run(run func(ctx context.Context, workspaceID uuid.UUID, event domain.Event)) *EventPublisher_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(domain.Event))
	})
	return _c
}

func (_c *EventPublisher_Publish_Call) Return(_a0 error) *EventPublisher_Publish_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EventPublisher_Publish_Call) RunAndReturn(run func(context.Context, uuid.UUID, domain.Event) error) *EventPublisher_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function with given fields: ctx, workspaceID
func (_m *EventPublisher) Subscribe(ctx context.Context, workspaceID uuid.UUID) (<-chan domain.Event, error) {
	ret := _m.Called(ctx, workspaceID)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 <-chan domain.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (<-chan domain.Event, error)); ok {
		return rf(ctx, workspaceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) <-chan domain.Event); ok {
		r0 = rf(ctx, workspaceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan domain.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, workspaceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EventPublisher_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type EventPublisher_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - ctx context.Context
//   - workspaceID uuid.UUID
func (_e *EventPublisher_Expecter) Subscribe(ctx interface{}, workspaceID interface{}) *EventPublisher_Subscribe_Call {
	return &EventPublisher_Subscribe_Call{Call: _e.mock.On("Subscribe", ctx, workspaceID)}
}

func (_c *EventPublisher_Subscribe_Call) Run(run func(ctx context.Context, workspaceID uuid.UUID)) *EventPublisher_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *EventPublisher_Subscribe_Call) Return(_a0 <-chan domain.Event, _a1 error) *EventPublisher_Subscribe_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EventPublisher_Subscribe_Call) RunAndReturn(run func(context.Context, uuid.UUID) (<-chan domain.Event, error)) *EventPublisher_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// NewEventPublisher creates a new instance of EventPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventPublisher {
	mock := &EventPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
