// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/robzlabz/employeebot/apps/backend/internal/modules/chat/domain"
	mock "github.com/stretchr/testify/mock"
)

// Router is an autogenerated mock type for the Router type
type Router struct {
	mock.Mock
}

type Router_Expecter struct {
	mock *mock.Mock
}

func (_m *Router) EXPECT() *Router_Expecter {
	return &Router_Expecter{mock: &_m.Mock}
}

// Pick provides a mock function with given fields: ctx, scope, conversation, message
func (_m *Router) Pick(ctx context.Context, scope domain.Scope, conversation domain.Conversation, message domain.Message) (domain.RouterDecision, error) {
	ret := _m.Called(ctx, scope, conversation, message)

	if len(ret) == 0 {
		panic("no return value specified for Pick")
	}

	var r0 domain.RouterDecision
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, domain.Conversation, domain.Message) (domain.RouterDecision, error)); ok {
		return rf(ctx, scope, conversation, message)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, domain.Conversation, domain.Message) domain.RouterDecision); ok {
		r0 = rf(ctx, scope, conversation, message)
	} else {
		r0 = ret.Get(0).(domain.RouterDecision)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Scope, domain.Conversation, domain.Message) error); ok {
		r1 = rf(ctx, scope, conversation, message)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Router_Pick_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pick'
type Router_Pick_Call struct {
	*mock.Call
}

// Pick is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
//   - conversation domain.Conversation
//   - message domain.Message
func (_e *Router_Expecter) Pick(ctx interface{}, scope interface{}, conversation interface{}, message interface{}) *Router_Pick_Call {
	return &Router_Pick_Call{Call: _e.mock.On("Pick", ctx, scope, conversation, message)}
}

func (_c *Router_Pick_Call) Run(run func(ctx context.Context, scope domain.Scope, conversation domain.Conversation, message domain.Message)) *Router_Pick_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope), args[2].(domain.Conversation), args[3].(domain.Message))
	})
	return _c
}

func (_c *Router_Pick_Call) Return(_a0 domain.RouterDecision, _a1 error) *Router_Pick_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Router_Pick_Call) RunAndReturn(run func(context.Context, domain.Scope, domain.Conversation, domain.Message) (domain.RouterDecision, error)) *Router_Pick_Call {
	_c.Call.Return(run)
	return _c
}

// NewRouter creates a new instance of Router. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRouter(t interface {
	mock.TestingT
	Cleanup(func())
}) *Router {
	mock := &Router{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
