// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/robzlabz/employeebot/apps/backend/internal/modules/chat/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// EventStore is an autogenerated mock type for the EventStore type
type EventStore struct {
	mock.Mock
}

type EventStore_Expecter struct {
	mock *mock.Mock
}

func (_m *EventStore) EXPECT() *EventStore_Expecter {
	return &EventStore_Expecter{mock: &_m.Mock}
}

// AppendEvent provides a mock function with given fields: ctx, event
func (_m *EventStore) AppendEvent(ctx context.Context, event domain.Event) (domain.Event, error) {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for AppendEvent")
	}

	var r0 domain.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Event) (domain.Event, error)); ok {
		return rf(ctx, event)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Event) domain.Event); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Get(0).(domain.Event)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Event) error); ok {
		r1 = rf(ctx, event)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EventStore_AppendEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AppendEvent'
type EventStore_AppendEvent_Call struct {
	*mock.Call
}

// AppendEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - event domain.Event
func (_e *EventStore_Expecter) AppendEvent(ctx interface{}, event interface{}) *EventStore_AppendEvent_Call {
	return &EventStore_AppendEvent_Call{Call: _e.mock.On("AppendEvent", ctx, event)}
}

func (_c *EventStore_AppendEvent_Call) Run(run func(ctx context.Context, event domain.Event)) *EventStore_AppendEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Event))
	})
	return _c
}

func (_c *EventStore_AppendEvent_Call) Return(_a0 domain.Event, _a1 error) *EventStore_AppendEvent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EventStore_AppendEvent_Call) RunAndReturn(run func(context.Context, domain.Event) (domain.Event, error)) *EventStore_AppendEvent_Call {
	_c.Call.Return(run)
	return _c
}

// LatestEvents provides a mock function with given fields: ctx, workspaceID, limit
func (_m *EventStore) LatestEvents(ctx context.Context, workspaceID uuid.UUID, limit int) ([]domain.Event, error) {
	ret := _m.Called(ctx, workspaceID, limit)

	if len(ret) == 0 {
		panic("no return value specified for LatestEvents")
	}

	var r0 []domain.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) ([]domain.Event, error)); ok {
		return rf(ctx, workspaceID, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) []domain.Event); ok {
		r0 = rf(ctx, workspaceID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int) error); ok {
		r1 = rf(ctx, workspaceID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EventStore_LatestEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LatestEvents'
type EventStore_LatestEvents_Call struct {
	*mock.Call
}

// LatestEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - workspaceID uuid.UUID
//   - limit int
func (_e *EventStore_Expecter) LatestEvents(ctx interface{}, workspaceID interface{}, limit interface{}) *EventStore_LatestEvents_Call {
	return &EventStore_LatestEvents_Call{Call: _e.mock.On("LatestEvents", ctx, workspaceID, limit)}
}

func (_c *EventStore_LatestEvents_Call) Run(run func(ctx context.Context, workspaceID uuid.UUID, limit int)) *EventStore_LatestEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int))
	})
	return _c
}

func (_c *EventStore_LatestEvents_Call) Return(_a0 []domain.Event, _a1 error) *EventStore_LatestEvents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EventStore_LatestEvents_Call) RunAndReturn(run func(context.Context, uuid.UUID, int) ([]domain.Event, error)) *EventStore_LatestEvents_Call {
	_c.Call.Return(run)
	return _c
}

// SinceEvents provides a mock function with given fields: ctx, workspaceID, afterID, limit
func (_m *EventStore) SinceEvents(ctx context.Context, workspaceID uuid.UUID, afterID int64, limit int) ([]domain.Event, error) {
	ret := _m.Called(ctx, workspaceID, afterID, limit)

	if len(ret) == 0 {
		panic("no return value specified for SinceEvents")
	}

	var r0 []domain.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int64, int) ([]domain.Event, error)); ok {
		return rf(ctx, workspaceID, afterID, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int64, int) []domain.Event); ok {
		r0 = rf(ctx, workspaceID, afterID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int64, int) error); ok {
		r1 = rf(ctx, workspaceID, afterID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EventStore_SinceEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SinceEvents'
type EventStore_SinceEvents_Call struct {
	*mock.Call
}

// SinceEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - workspaceID uuid.UUID
//   - afterID int64
//   - limit int
func (_e *EventStore_Expecter) SinceEvents(ctx interface{}, workspaceID interface{}, afterID interface{}, limit interface{}) *EventStore_SinceEvents_Call {
	return &EventStore_SinceEvents_Call{Call: _e.mock.On("SinceEvents", ctx, workspaceID, afterID, limit)}
}

func (_c *EventStore_SinceEvents_Call) Run(run func(ctx context.Context, workspaceID uuid.UUID, afterID int64, limit int)) *EventStore_SinceEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int64), args[3].(int))
	})
	return _c
}

func (_c *EventStore_SinceEvents_Call) Return(_a0 []domain.Event, _a1 error) *EventStore_SinceEvents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EventStore_SinceEvents_Call) RunAndReturn(run func(context.Context, uuid.UUID, int64, int) ([]domain.Event, error)) *EventStore_SinceEvents_Call {
	_c.Call.Return(run)
	return _c
}

// NewEventStore creates a new instance of EventStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventStore {
	mock := &EventStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
