// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/robzlabz/employeebot/apps/backend/internal/modules/chat/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// AddParticipants provides a mock function with given fields: ctx, scope, id, req
func (_m *Service) AddParticipants(ctx context.Context, scope domain.Scope, id uuid.UUID, req domain.AddParticipantsRequest) (domain.Conversation, error) {
	ret := _m.Called(ctx, scope, id, req)

	if len(ret) == 0 {
		panic("no return value specified for AddParticipants")
	}

	var r0 domain.Conversation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, uuid.UUID, domain.AddParticipantsRequest) (domain.Conversation, error)); ok {
		return rf(ctx, scope, id, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, uuid.UUID, domain.AddParticipantsRequest) domain.Conversation); ok {
		r0 = rf(ctx, scope, id, req)
	} else {
		r0 = ret.Get(0).(domain.Conversation)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Scope, uuid.UUID, domain.AddParticipantsRequest) error); ok {
		r1 = rf(ctx, scope, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_AddParticipants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddParticipants'
type Service_AddParticipants_Call struct {
	*mock.Call
}

// AddParticipants is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
//   - id uuid.UUID
//   - req domain.AddParticipantsRequest
func (_e *Service_Expecter) AddParticipants(ctx interface{}, scope interface{}, id interface{}, req interface{}) *Service_AddParticipants_Call {
	return &Service_AddParticipants_Call{Call: _e.mock.On("AddParticipants", ctx, scope, id, req)}
}

func (_c *Service_AddParticipants_Call) Run(run func(ctx context.Context, scope domain.Scope, id uuid.UUID, req domain.AddParticipantsRequest)) *Service_AddParticipants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope), args[2].(uuid.UUID), args[3].(domain.AddParticipantsRequest))
	})
	return _c
}

func (_c *Service_AddParticipants_Call) Return(_a0 domain.Conversation, _a1 error) *Service_AddParticipants_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_AddParticipants_Call) RunAndReturn(run func(context.Context, domain.Scope, uuid.UUID, domain.AddParticipantsRequest) (domain.Conversation, error)) *Service_AddParticipants_Call {
	_c.Call.Return(run)
	return _c
}

// Attach provides a mock function with given fields: ctx, scope, req, content
func (_m *Service) Attach(ctx context.Context, scope domain.Scope, req domain.AttachRequest, content []byte) (domain.Attachment, error) {
	ret := _m.Called(ctx, scope, req, content)

	if len(ret) == 0 {
		panic("no return value specified for Attach")
	}

	var r0 domain.Attachment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, domain.AttachRequest, []byte) (domain.Attachment, error)); ok {
		return rf(ctx, scope, req, content)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, domain.AttachRequest, []byte) domain.Attachment); ok {
		r0 = rf(ctx, scope, req, content)
	} else {
		r0 = ret.Get(0).(domain.Attachment)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Scope, domain.AttachRequest, []byte) error); ok {
		r1 = rf(ctx, scope, req, content)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_Attach_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Attach'
type Service_Attach_Call struct {
	*mock.Call
}

// Attach is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
//   - req domain.AttachRequest
//   - content []byte
func (_e *Service_Expecter) Attach(ctx interface{}, scope interface{}, req interface{}, content interface{}) *Service_Attach_Call {
	return &Service_Attach_Call{Call: _e.mock.On("Attach", ctx, scope, req, content)}
}

func (_c *Service_Attach_Call) Run(run func(ctx context.Context, scope domain.Scope, req domain.AttachRequest, content []byte)) *Service_Attach_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope), args[2].(domain.AttachRequest), args[3].([]byte))
	})
	return _c
}

func (_c *Service_Attach_Call) Return(_a0 domain.Attachment, _a1 error) *Service_Attach_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_Attach_Call) RunAndReturn(run func(context.Context, domain.Scope, domain.AttachRequest, []byte) (domain.Attachment, error)) *Service_Attach_Call {
	_c.Call.Return(run)
	return _c
}

// Attachment provides a mock function with given fields: ctx, scope, id
func (_m *Service) Attachment(ctx context.Context, scope domain.Scope, id uuid.UUID) (domain.Attachment, error) {
	ret := _m.Called(ctx, scope, id)

	if len(ret) == 0 {
		panic("no return value specified for Attachment")
	}

	var r0 domain.Attachment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, uuid.UUID) (domain.Attachment, error)); ok {
		return rf(ctx, scope, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, uuid.UUID) domain.Attachment); ok {
		r0 = rf(ctx, scope, id)
	} else {
		r0 = ret.Get(0).(domain.Attachment)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Scope, uuid.UUID) error); ok {
		r1 = rf(ctx, scope, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_Attachment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Attachment'
type Service_Attachment_Call struct {
	*mock.Call
}

// Attachment is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
//   - id uuid.UUID
func (_e *Service_Expecter) Attachment(ctx interface{}, scope interface{}, id interface{}) *Service_Attachment_Call {
	return &Service_Attachment_Call{Call: _e.mock.On("Attachment", ctx, scope, id)}
}

func (_c *Service_Attachment_Call) Run(run func(ctx context.Context, scope domain.Scope, id uuid.UUID)) *Service_Attachment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *Service_Attachment_Call) Return(_a0 domain.Attachment, _a1 error) *Service_Attachment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_Attachment_Call) RunAndReturn(run func(context.Context, domain.Scope, uuid.UUID) (domain.Attachment, error)) *Service_Attachment_Call {
	_c.Call.Return(run)
	return _c
}

// AttachmentContent provides a mock function with given fields: ctx, scope, id
func (_m *Service) AttachmentContent(ctx context.Context, scope domain.Scope, id uuid.UUID) (domain.Attachment, []byte, error) {
	ret := _m.Called(ctx, scope, id)

	if len(ret) == 0 {
		panic("no return value specified for AttachmentContent")
	}

	var r0 domain.Attachment
	var r1 []byte
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, uuid.UUID) (domain.Attachment, []byte, error)); ok {
		return rf(ctx, scope, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, uuid.UUID) domain.Attachment); ok {
		r0 = rf(ctx, scope, id)
	} else {
		r0 = ret.Get(0).(domain.Attachment)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Scope, uuid.UUID) []byte); ok {
		r1 = rf(ctx, scope, id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]byte)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, domain.Scope, uuid.UUID) error); ok {
		r2 = rf(ctx, scope, id)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Service_AttachmentContent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AttachmentContent'
type Service_AttachmentContent_Call struct {
	*mock.Call
}

// AttachmentContent is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
//   - id uuid.UUID
func (_e *Service_Expecter) AttachmentContent(ctx interface{}, scope interface{}, id interface{}) *Service_AttachmentContent_Call {
	return &Service_AttachmentContent_Call{Call: _e.mock.On("AttachmentContent", ctx, scope, id)}
}

func (_c *Service_AttachmentContent_Call) Run(run func(ctx context.Context, scope domain.Scope, id uuid.UUID)) *Service_AttachmentContent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *Service_AttachmentContent_Call) Return(_a0 domain.Attachment, _a1 []byte, _a2 error) *Service_AttachmentContent_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Service_AttachmentContent_Call) RunAndReturn(run func(context.Context, domain.Scope, uuid.UUID) (domain.Attachment, []byte, error)) *Service_AttachmentContent_Call {
	_c.Call.Return(run)
	return _c
}

// Content provides a mock function with given fields: ctx, reference
func (_m *Service) Content(ctx context.Context, reference string) ([]byte, error) {
	ret := _m.Called(ctx, reference)

	if len(ret) == 0 {
		panic("no return value specified for Content")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return rf(ctx, reference)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = rf(ctx, reference)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, reference)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_Content_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Content'
type Service_Content_Call struct {
	*mock.Call
}

// Content is a helper method to define mock.On call
//   - ctx context.Context
//   - reference string
func (_e *Service_Expecter) Content(ctx interface{}, reference interface{}) *Service_Content_Call {
	return &Service_Content_Call{Call: _e.mock.On("Content", ctx, reference)}
}

func (_c *Service_Content_Call) Run(run func(ctx context.Context, reference string)) *Service_Content_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Service_Content_Call) Return(_a0 []byte, _a1 error) *Service_Content_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_Content_Call) RunAndReturn(run func(context.Context, string) ([]byte, error)) *Service_Content_Call {
	_c.Call.Return(run)
	return _c
}

// Conversation provides a mock function with given fields: ctx, scope, id
func (_m *Service) Conversation(ctx context.Context, scope domain.Scope, id uuid.UUID) (domain.Conversation, error) {
	ret := _m.Called(ctx, scope, id)

	if len(ret) == 0 {
		panic("no return value specified for Conversation")
	}

	var r0 domain.Conversation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, uuid.UUID) (domain.Conversation, error)); ok {
		return rf(ctx, scope, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, uuid.UUID) domain.Conversation); ok {
		r0 = rf(ctx, scope, id)
	} else {
		r0 = ret.Get(0).(domain.Conversation)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Scope, uuid.UUID) error); ok {
		r1 = rf(ctx, scope, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_Conversation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Conversation'
type Service_Conversation_Call struct {
	*mock.Call
}

// Conversation is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
//   - id uuid.UUID
func (_e *Service_Expecter) Conversation(ctx interface{}, scope interface{}, id interface{}) *Service_Conversation_Call {
	return &Service_Conversation_Call{Call: _e.mock.On("Conversation", ctx, scope, id)}
}

func (_c *Service_Conversation_Call) Run(run func(ctx context.Context, scope domain.Scope, id uuid.UUID)) *Service_Conversation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *Service_Conversation_Call) Return(_a0 domain.Conversation, _a1 error) *Service_Conversation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_Conversation_Call) RunAndReturn(run func(context.Context, domain.Scope, uuid.UUID) (domain.Conversation, error)) *Service_Conversation_Call {
	_c.Call.Return(run)
	return _c
}

// Conversations provides a mock function with given fields: ctx, scope
func (_m *Service) Conversations(ctx context.Context, scope domain.Scope) ([]domain.Conversation, error) {
	ret := _m.Called(ctx, scope)

	if len(ret) == 0 {
		panic("no return value specified for Conversations")
	}

	var r0 []domain.Conversation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope) ([]domain.Conversation, error)); ok {
		return rf(ctx, scope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope) []domain.Conversation); ok {
		r0 = rf(ctx, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Conversation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Scope) error); ok {
		r1 = rf(ctx, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_Conversations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Conversations'
type Service_Conversations_Call struct {
	*mock.Call
}

// Conversations is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
func (_e *Service_Expecter) Conversations(ctx interface{}, scope interface{}) *Service_Conversations_Call {
	return &Service_Conversations_Call{Call: _e.mock.On("Conversations", ctx, scope)}
}

func (_c *Service_Conversations_Call) Run(run func(ctx context.Context, scope domain.Scope)) *Service_Conversations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope))
	})
	return _c
}

func (_c *Service_Conversations_Call) Return(_a0 []domain.Conversation, _a1 error) *Service_Conversations_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_Conversations_Call) RunAndReturn(run func(context.Context, domain.Scope) ([]domain.Conversation, error)) *Service_Conversations_Call {
	_c.Call.Return(run)
	return _c
}

// CreateGroup provides a mock function with given fields: ctx, scope, req
func (_m *Service) CreateGroup(ctx context.Context, scope domain.Scope, req domain.CreateGroupRequest) (domain.Conversation, error) {
	ret := _m.Called(ctx, scope, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateGroup")
	}

	var r0 domain.Conversation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, domain.CreateGroupRequest) (domain.Conversation, error)); ok {
		return rf(ctx, scope, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, domain.CreateGroupRequest) domain.Conversation); ok {
		r0 = rf(ctx, scope, req)
	} else {
		r0 = ret.Get(0).(domain.Conversation)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Scope, domain.CreateGroupRequest) error); ok {
		r1 = rf(ctx, scope, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_CreateGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateGroup'
type Service_CreateGroup_Call struct {
	*mock.Call
}

// CreateGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
//   - req domain.CreateGroupRequest
func (_e *Service_Expecter) CreateGroup(ctx interface{}, scope interface{}, req interface{}) *Service_CreateGroup_Call {
	return &Service_CreateGroup_Call{Call: _e.mock.On("CreateGroup", ctx, scope, req)}
}

func (_c *Service_CreateGroup_Call) Run(run func(ctx context.Context, scope domain.Scope, req domain.CreateGroupRequest)) *Service_CreateGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope), args[2].(domain.CreateGroupRequest))
	})
	return _c
}

func (_c *Service_CreateGroup_Call) Return(_a0 domain.Conversation, _a1 error) *Service_CreateGroup_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_CreateGroup_Call) RunAndReturn(run func(context.Context, domain.Scope, domain.CreateGroupRequest) (domain.Conversation, error)) *Service_CreateGroup_Call {
	_c.Call.Return(run)
	return _c
}

// Direct provides a mock function with given fields: ctx, scope, agentID
func (_m *Service) Direct(ctx context.Context, scope domain.Scope, agentID uuid.UUID) (domain.Conversation, error) {
	ret := _m.Called(ctx, scope, agentID)

	if len(ret) == 0 {
		panic("no return value specified for Direct")
	}

	var r0 domain.Conversation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, uuid.UUID) (domain.Conversation, error)); ok {
		return rf(ctx, scope, agentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, uuid.UUID) domain.Conversation); ok {
		r0 = rf(ctx, scope, agentID)
	} else {
		r0 = ret.Get(0).(domain.Conversation)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Scope, uuid.UUID) error); ok {
		r1 = rf(ctx, scope, agentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_Direct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Direct'
type Service_Direct_Call struct {
	*mock.Call
}

// Direct is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
//   - agentID uuid.UUID
func (_e *Service_Expecter) Direct(ctx interface{}, scope interface{}, agentID interface{}) *Service_Direct_Call {
	return &Service_Direct_Call{Call: _e.mock.On("Direct", ctx, scope, agentID)}
}

func (_c *Service_Direct_Call) Run(run func(ctx context.Context, scope domain.Scope, agentID uuid.UUID)) *Service_Direct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *Service_Direct_Call) Return(_a0 domain.Conversation, _a1 error) *Service_Direct_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_Direct_Call) RunAndReturn(run func(context.Context, domain.Scope, uuid.UUID) (domain.Conversation, error)) *Service_Direct_Call {
	_c.Call.Return(run)
	return _c
}

// Events provides a mock function with given fields: ctx, scope, afterID, limit
func (_m *Service) Events(ctx context.Context, scope domain.Scope, afterID int64, limit int) ([]domain.Event, error) {
	ret := _m.Called(ctx, scope, afterID, limit)

	if len(ret) == 0 {
		panic("no return value specified for Events")
	}

	var r0 []domain.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, int64, int) ([]domain.Event, error)); ok {
		return rf(ctx, scope, afterID, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, int64, int) []domain.Event); ok {
		r0 = rf(ctx, scope, afterID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Scope, int64, int) error); ok {
		r1 = rf(ctx, scope, afterID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_Events_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Events'
type Service_Events_Call struct {
	*mock.Call
}

// Events is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
//   - afterID int64
//   - limit int
func (_e *Service_Expecter) Events(ctx interface{}, scope interface{}, afterID interface{}, limit interface{}) *Service_Events_Call {
	return &Service_Events_Call{Call: _e.mock.On("Events", ctx, scope, afterID, limit)}
}

func (_c *Service_Events_Call) Run(run func(ctx context.Context, scope domain.Scope, afterID int64, limit int)) *Service_Events_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope), args[2].(int64), args[3].(int))
	})
	return _c
}

func (_c *Service_Events_Call) Return(_a0 []domain.Event, _a1 error) *Service_Events_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_Events_Call) RunAndReturn(run func(context.Context, domain.Scope, int64, int) ([]domain.Event, error)) *Service_Events_Call {
	_c.Call.Return(run)
	return _c
}

// History provides a mock function with given fields: ctx, scope, conversationID, cursor
func (_m *Service) History(ctx context.Context, scope domain.Scope, conversationID uuid.UUID, cursor domain.Cursor) (domain.Page, error) {
	ret := _m.Called(ctx, scope, conversationID, cursor)

	if len(ret) == 0 {
		panic("no return value specified for History")
	}

	var r0 domain.Page
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, uuid.UUID, domain.Cursor) (domain.Page, error)); ok {
		return rf(ctx, scope, conversationID, cursor)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, uuid.UUID, domain.Cursor) domain.Page); ok {
		r0 = rf(ctx, scope, conversationID, cursor)
	} else {
		r0 = ret.Get(0).(domain.Page)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Scope, uuid.UUID, domain.Cursor) error); ok {
		r1 = rf(ctx, scope, conversationID, cursor)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_History_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'History'
type Service_History_Call struct {
	*mock.Call
}

// History is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
//   - conversationID uuid.UUID
//   - cursor domain.Cursor
func (_e *Service_Expecter) History(ctx interface{}, scope interface{}, conversationID interface{}, cursor interface{}) *Service_History_Call {
	return &Service_History_Call{Call: _e.mock.On("History", ctx, scope, conversationID, cursor)}
}

func (_c *Service_History_Call) Run(run func(ctx context.Context, scope domain.Scope, conversationID uuid.UUID, cursor domain.Cursor)) *Service_History_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope), args[2].(uuid.UUID), args[3].(domain.Cursor))
	})
	return _c
}

func (_c *Service_History_Call) Return(_a0 domain.Page, _a1 error) *Service_History_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_History_Call) RunAndReturn(run func(context.Context, domain.Scope, uuid.UUID, domain.Cursor) (domain.Page, error)) *Service_History_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function with given fields: ctx, scope, req
func (_m *Service) Send(ctx context.Context, scope domain.Scope, req domain.SendRequest) (domain.SendResult, error) {
	ret := _m.Called(ctx, scope, req)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 domain.SendResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, domain.SendRequest) (domain.SendResult, error)); ok {
		return rf(ctx, scope, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, domain.SendRequest) domain.SendResult); ok {
		r0 = rf(ctx, scope, req)
	} else {
		r0 = ret.Get(0).(domain.SendResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Scope, domain.SendRequest) error); ok {
		r1 = rf(ctx, scope, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type Service_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
//   - req domain.SendRequest
func (_e *Service_Expecter) Send(ctx interface{}, scope interface{}, req interface{}) *Service_Send_Call {
	return &Service_Send_Call{Call: _e.mock.On("Send", ctx, scope, req)}
}

func (_c *Service_Send_Call) Run(run func(ctx context.Context, scope domain.Scope, req domain.SendRequest)) *Service_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope), args[2].(domain.SendRequest))
	})
	return _c
}

func (_c *Service_Send_Call) Return(_a0 domain.SendResult, _a1 error) *Service_Send_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_Send_Call) RunAndReturn(run func(context.Context, domain.Scope, domain.SendRequest) (domain.SendResult, error)) *Service_Send_Call {
	_c.Call.Return(run)
	return _c
}

// Stream provides a mock function with given fields: ctx, scope, afterID
func (_m *Service) Stream(ctx context.Context, scope domain.Scope, afterID int64) (<-chan domain.Event, error) {
	ret := _m.Called(ctx, scope, afterID)

	if len(ret) == 0 {
		panic("no return value specified for Stream")
	}

	var r0 <-chan domain.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, int64) (<-chan domain.Event, error)); ok {
		return rf(ctx, scope, afterID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, int64) <-chan domain.Event); ok {
		r0 = rf(ctx, scope, afterID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan domain.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Scope, int64) error); ok {
		r1 = rf(ctx, scope, afterID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_Stream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stream'
type Service_Stream_Call struct {
	*mock.Call
}

// Stream is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
//   - afterID int64
func (_e *Service_Expecter) Stream(ctx interface{}, scope interface{}, afterID interface{}) *Service_Stream_Call {
	return &Service_Stream_Call{Call: _e.mock.On("Stream", ctx, scope, afterID)}
}

func (_c *Service_Stream_Call) Run(run func(ctx context.Context, scope domain.Scope, afterID int64)) *Service_Stream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope), args[2].(int64))
	})
	return _c
}

func (_c *Service_Stream_Call) Return(_a0 <-chan domain.Event, _a1 error) *Service_Stream_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_Stream_Call) RunAndReturn(run func(context.Context, domain.Scope, int64) (<-chan domain.Event, error)) *Service_Stream_Call {
	_c.Call.Return(run)
	return _c
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
