// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/robzlabz/employeebot/apps/backend/internal/modules/chat/domain"
	mock "github.com/stretchr/testify/mock"
)

// Responder is an autogenerated mock type for the Responder type
type Responder struct {
	mock.Mock
}

type Responder_Expecter struct {
	mock *mock.Mock
}

func (_m *Responder) EXPECT() *Responder_Expecter {
	return &Responder_Expecter{mock: &_m.Mock}
}

// Reply provides a mock function with given fields: ctx, scope, req
func (_m *Responder) Reply(ctx context.Context, scope domain.Scope, req domain.ReplyRequest) (<-chan domain.StreamChunk, error) {
	ret := _m.Called(ctx, scope, req)

	if len(ret) == 0 {
		panic("no return value specified for Reply")
	}

	var r0 <-chan domain.StreamChunk
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, domain.ReplyRequest) (<-chan domain.StreamChunk, error)); ok {
		return rf(ctx, scope, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, domain.ReplyRequest) <-chan domain.StreamChunk); ok {
		r0 = rf(ctx, scope, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan domain.StreamChunk)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Scope, domain.ReplyRequest) error); ok {
		r1 = rf(ctx, scope, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Responder_Reply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reply'
type Responder_Reply_Call struct {
	*mock.Call
}

// Reply is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
//   - req domain.ReplyRequest
func (_e *Responder_Expecter) Reply(ctx interface{}, scope interface{}, req interface{}) *Responder_Reply_Call {
	return &Responder_Reply_Call{Call: _e.mock.On("Reply", ctx, scope, req)}
}

func (_c *Responder_Reply_Call) Run(run func(ctx context.Context, scope domain.Scope, req domain.ReplyRequest)) *Responder_Reply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope), args[2].(domain.ReplyRequest))
	})
	return _c
}

func (_c *Responder_Reply_Call) Return(_a0 <-chan domain.StreamChunk, _a1 error) *Responder_Reply_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Responder_Reply_Call) RunAndReturn(run func(context.Context, domain.Scope, domain.ReplyRequest) (<-chan domain.StreamChunk, error)) *Responder_Reply_Call {
	_c.Call.Return(run)
	return _c
}

// NewResponder creates a new instance of Responder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewResponder(t interface {
	mock.TestingT
	Cleanup(func())
}) *Responder {
	mock := &Responder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
