// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/robzlabz/employeebot/apps/backend/internal/modules/chat/domain"
	mock "github.com/stretchr/testify/mock"
)

// ObjectStore is an autogenerated mock type for the ObjectStore type
type ObjectStore struct {
	mock.Mock
}

type ObjectStore_Expecter struct {
	mock *mock.Mock
}

func (_m *ObjectStore) EXPECT() *ObjectStore_Expecter {
	return &ObjectStore_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, key
func (_m *ObjectStore) Delete(ctx context.Context, key string) error {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ObjectStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type ObjectStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *ObjectStore_Expecter) Delete(ctx interface{}, key interface{}) *ObjectStore_Delete_Call {
	return &ObjectStore_Delete_Call{Call: _e.mock.On("Delete", ctx, key)}
}

func (_c *ObjectStore_Delete_Call) Run(run func(ctx context.Context, key string)) *ObjectStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ObjectStore_Delete_Call) Return(_a0 error) *ObjectStore_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ObjectStore_Delete_Call) RunAndReturn(run func(context.Context, string) error) *ObjectStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Driver provides a mock function with no fields
func (_m *ObjectStore) Driver() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Driver")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ObjectStore_Driver_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Driver'
type ObjectStore_Driver_Call struct {
	*mock.Call
}

// Driver is a helper method to define mock.On call
func (_e *ObjectStore_Expecter) Driver() *ObjectStore_Driver_Call {
	return &ObjectStore_Driver_Call{Call: _e.mock.On("Driver")}
}

func (_c *ObjectStore_Driver_Call) Run(run func()) *ObjectStore_Driver_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ObjectStore_Driver_Call) Return(_a0 string) *ObjectStore_Driver_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ObjectStore_Driver_Call) RunAndReturn(run func() string) *ObjectStore_Driver_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, key
func (_m *ObjectStore) Get(ctx context.Context, key string) ([]byte, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ObjectStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type ObjectStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *ObjectStore_Expecter) Get(ctx interface{}, key interface{}) *ObjectStore_Get_Call {
	return &ObjectStore_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *ObjectStore_Get_Call) Run(run func(ctx context.Context, key string)) *ObjectStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ObjectStore_Get_Call) Return(_a0 []byte, _a1 error) *ObjectStore_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ObjectStore_Get_Call) RunAndReturn(run func(context.Context, string) ([]byte, error)) *ObjectStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function with given fields: ctx, key, contentType, content
func (_m *ObjectStore) Put(ctx context.Context, key string, contentType string, content []byte) (domain.StoredObject, error) {
	ret := _m.Called(ctx, key, contentType, content)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 domain.StoredObject
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []byte) (domain.StoredObject, error)); ok {
		return rf(ctx, key, contentType, content)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []byte) domain.StoredObject); ok {
		r0 = rf(ctx, key, contentType, content)
	} else {
		r0 = ret.Get(0).(domain.StoredObject)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, []byte) error); ok {
		r1 = rf(ctx, key, contentType, content)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ObjectStore_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type ObjectStore_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - contentType string
//   - content []byte
func (_e *ObjectStore_Expecter) Put(ctx interface{}, key interface{}, contentType interface{}, content interface{}) *ObjectStore_Put_Call {
	return &ObjectStore_Put_Call{Call: _e.mock.On("Put", ctx, key, contentType, content)}
}

func (_c *ObjectStore_Put_Call) Run(run func(ctx context.Context, key string, contentType string, content []byte)) *ObjectStore_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].([]byte))
	})
	return _c
}

func (_c *ObjectStore_Put_Call) Return(_a0 domain.StoredObject, _a1 error) *ObjectStore_Put_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ObjectStore_Put_Call) RunAndReturn(run func(context.Context, string, string, []byte) (domain.StoredObject, error)) *ObjectStore_Put_Call {
	_c.Call.Return(run)
	return _c
}

// NewObjectStore creates a new instance of ObjectStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewObjectStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *ObjectStore {
	mock := &ObjectStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
