// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// PlanLimits is an autogenerated mock type for the PlanLimits type
type PlanLimits struct {
	mock.Mock
}

type PlanLimits_Expecter struct {
	mock *mock.Mock
}

func (_m *PlanLimits) EXPECT() *PlanLimits_Expecter {
	return &PlanLimits_Expecter{mock: &_m.Mock}
}

// MaxAgents provides a mock function with given fields: ctx, workspaceID
func (_m *PlanLimits) MaxAgents(ctx context.Context, workspaceID uuid.UUID) (int, error) {
	ret := _m.Called(ctx, workspaceID)

	if len(ret) == 0 {
		panic("no return value specified for MaxAgents")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int, error)); ok {
		return rf(ctx, workspaceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int); ok {
		r0 = rf(ctx, workspaceID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, workspaceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PlanLimits_MaxAgents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MaxAgents'
type PlanLimits_MaxAgents_Call struct {
	*mock.Call
}

// MaxAgents is a helper method to define mock.On call
//   - ctx context.Context
//   - workspaceID uuid.UUID
func (_e *PlanLimits_Expecter) MaxAgents(ctx interface{}, workspaceID interface{}) *PlanLimits_MaxAgents_Call {
	return &PlanLimits_MaxAgents_Call{Call: _e.mock.On("MaxAgents", ctx, workspaceID)}
}

func (_c *PlanLimits_MaxAgents_Call) Run(run func(ctx context.Context, workspaceID uuid.UUID)) *PlanLimits_MaxAgents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *PlanLimits_MaxAgents_Call) Return(_a0 int, _a1 error) *PlanLimits_MaxAgents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PlanLimits_MaxAgents_Call) RunAndReturn(run func(context.Context, uuid.UUID) (int, error)) *PlanLimits_MaxAgents_Call {
	_c.Call.Return(run)
	return _c
}

// NewPlanLimits creates a new instance of PlanLimits. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPlanLimits(t interface {
	mock.TestingT
	Cleanup(func())
}) *PlanLimits {
	mock := &PlanLimits{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
