// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/robzlabz/employeebot/apps/backend/internal/modules/agent/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// Activity provides a mock function with given fields: ctx, scope
func (_m *Repository) Activity(ctx context.Context, scope domain.Scope) (map[uuid.UUID]domain.Activity, error) {
	ret := _m.Called(ctx, scope)

	if len(ret) == 0 {
		panic("no return value specified for Activity")
	}

	var r0 map[uuid.UUID]domain.Activity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope) (map[uuid.UUID]domain.Activity, error)); ok {
		return rf(ctx, scope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope) map[uuid.UUID]domain.Activity); ok {
		r0 = rf(ctx, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[uuid.UUID]domain.Activity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Scope) error); ok {
		r1 = rf(ctx, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_Activity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Activity'
type Repository_Activity_Call struct {
	*mock.Call
}

// Activity is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
func (_e *Repository_Expecter) Activity(ctx interface{}, scope interface{}) *Repository_Activity_Call {
	return &Repository_Activity_Call{Call: _e.mock.On("Activity", ctx, scope)}
}

func (_c *Repository_Activity_Call) Run(run func(ctx context.Context, scope domain.Scope)) *Repository_Activity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope))
	})
	return _c
}

func (_c *Repository_Activity_Call) Return(_a0 map[uuid.UUID]domain.Activity, _a1 error) *Repository_Activity_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_Activity_Call) RunAndReturn(run func(context.Context, domain.Scope) (map[uuid.UUID]domain.Activity, error)) *Repository_Activity_Call {
	_c.Call.Return(run)
	return _c
}

// ActivityFor provides a mock function with given fields: ctx, scope, id
func (_m *Repository) ActivityFor(ctx context.Context, scope domain.Scope, id uuid.UUID) (domain.Activity, error) {
	ret := _m.Called(ctx, scope, id)

	if len(ret) == 0 {
		panic("no return value specified for ActivityFor")
	}

	var r0 domain.Activity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, uuid.UUID) (domain.Activity, error)); ok {
		return rf(ctx, scope, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, uuid.UUID) domain.Activity); ok {
		r0 = rf(ctx, scope, id)
	} else {
		r0 = ret.Get(0).(domain.Activity)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Scope, uuid.UUID) error); ok {
		r1 = rf(ctx, scope, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_ActivityFor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ActivityFor'
type Repository_ActivityFor_Call struct {
	*mock.Call
}

// ActivityFor is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
//   - id uuid.UUID
func (_e *Repository_Expecter) ActivityFor(ctx interface{}, scope interface{}, id interface{}) *Repository_ActivityFor_Call {
	return &Repository_ActivityFor_Call{Call: _e.mock.On("ActivityFor", ctx, scope, id)}
}

func (_c *Repository_ActivityFor_Call) Run(run func(ctx context.Context, scope domain.Scope, id uuid.UUID)) *Repository_ActivityFor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *Repository_ActivityFor_Call) Return(_a0 domain.Activity, _a1 error) *Repository_ActivityFor_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_ActivityFor_Call) RunAndReturn(run func(context.Context, domain.Scope, uuid.UUID) (domain.Activity, error)) *Repository_ActivityFor_Call {
	_c.Call.Return(run)
	return _c
}

// AgentTemplate provides a mock function with given fields: ctx, key
func (_m *Repository) AgentTemplate(ctx context.Context, key string) (domain.NewAgent, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for AgentTemplate")
	}

	var r0 domain.NewAgent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.NewAgent, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.NewAgent); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Get(0).(domain.NewAgent)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_AgentTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AgentTemplate'
type Repository_AgentTemplate_Call struct {
	*mock.Call
}

// AgentTemplate is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *Repository_Expecter) AgentTemplate(ctx interface{}, key interface{}) *Repository_AgentTemplate_Call {
	return &Repository_AgentTemplate_Call{Call: _e.mock.On("AgentTemplate", ctx, key)}
}

func (_c *Repository_AgentTemplate_Call) Run(run func(ctx context.Context, key string)) *Repository_AgentTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Repository_AgentTemplate_Call) Return(_a0 domain.NewAgent, _a1 error) *Repository_AgentTemplate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_AgentTemplate_Call) RunAndReturn(run func(context.Context, string) (domain.NewAgent, error)) *Repository_AgentTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// AllowedTools provides a mock function with given fields: ctx, scope, agentID
func (_m *Repository) AllowedTools(ctx context.Context, scope domain.Scope, agentID uuid.UUID) ([]domain.Tool, error) {
	ret := _m.Called(ctx, scope, agentID)

	if len(ret) == 0 {
		panic("no return value specified for AllowedTools")
	}

	var r0 []domain.Tool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, uuid.UUID) ([]domain.Tool, error)); ok {
		return rf(ctx, scope, agentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, uuid.UUID) []domain.Tool); ok {
		r0 = rf(ctx, scope, agentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Tool)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Scope, uuid.UUID) error); ok {
		r1 = rf(ctx, scope, agentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_AllowedTools_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AllowedTools'
type Repository_AllowedTools_Call struct {
	*mock.Call
}

// AllowedTools is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
//   - agentID uuid.UUID
func (_e *Repository_Expecter) AllowedTools(ctx interface{}, scope interface{}, agentID interface{}) *Repository_AllowedTools_Call {
	return &Repository_AllowedTools_Call{Call: _e.mock.On("AllowedTools", ctx, scope, agentID)}
}

func (_c *Repository_AllowedTools_Call) Run(run func(ctx context.Context, scope domain.Scope, agentID uuid.UUID)) *Repository_AllowedTools_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *Repository_AllowedTools_Call) Return(_a0 []domain.Tool, _a1 error) *Repository_AllowedTools_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_AllowedTools_Call) RunAndReturn(run func(context.Context, domain.Scope, uuid.UUID) ([]domain.Tool, error)) *Repository_AllowedTools_Call {
	_c.Call.Return(run)
	return _c
}

// CountLive provides a mock function with given fields: ctx, scope
func (_m *Repository) CountLive(ctx context.Context, scope domain.Scope) (int64, error) {
	ret := _m.Called(ctx, scope)

	if len(ret) == 0 {
		panic("no return value specified for CountLive")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope) (int64, error)); ok {
		return rf(ctx, scope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope) int64); ok {
		r0 = rf(ctx, scope)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Scope) error); ok {
		r1 = rf(ctx, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_CountLive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountLive'
type Repository_CountLive_Call struct {
	*mock.Call
}

// CountLive is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
func (_e *Repository_Expecter) CountLive(ctx interface{}, scope interface{}) *Repository_CountLive_Call {
	return &Repository_CountLive_Call{Call: _e.mock.On("CountLive", ctx, scope)}
}

func (_c *Repository_CountLive_Call) Run(run func(ctx context.Context, scope domain.Scope)) *Repository_CountLive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope))
	})
	return _c
}

func (_c *Repository_CountLive_Call) Return(_a0 int64, _a1 error) *Repository_CountLive_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_CountLive_Call) RunAndReturn(run func(context.Context, domain.Scope) (int64, error)) *Repository_CountLive_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, scope, agent
func (_m *Repository) Create(ctx context.Context, scope domain.Scope, agent domain.NewAgent) (domain.Agent, error) {
	ret := _m.Called(ctx, scope, agent)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Agent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, domain.NewAgent) (domain.Agent, error)); ok {
		return rf(ctx, scope, agent)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, domain.NewAgent) domain.Agent); ok {
		r0 = rf(ctx, scope, agent)
	} else {
		r0 = ret.Get(0).(domain.Agent)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Scope, domain.NewAgent) error); ok {
		r1 = rf(ctx, scope, agent)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type Repository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
//   - agent domain.NewAgent
func (_e *Repository_Expecter) Create(ctx interface{}, scope interface{}, agent interface{}) *Repository_Create_Call {
	return &Repository_Create_Call{Call: _e.mock.On("Create", ctx, scope, agent)}
}

func (_c *Repository_Create_Call) Run(run func(ctx context.Context, scope domain.Scope, agent domain.NewAgent)) *Repository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope), args[2].(domain.NewAgent))
	})
	return _c
}

func (_c *Repository_Create_Call) Return(_a0 domain.Agent, _a1 error) *Repository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_Create_Call) RunAndReturn(run func(context.Context, domain.Scope, domain.NewAgent) (domain.Agent, error)) *Repository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, scope, id
func (_m *Repository) Delete(ctx context.Context, scope domain.Scope, id uuid.UUID) error {
	ret := _m.Called(ctx, scope, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, uuid.UUID) error); ok {
		r0 = rf(ctx, scope, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type Repository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
//   - id uuid.UUID
func (_e *Repository_Expecter) Delete(ctx interface{}, scope interface{}, id interface{}) *Repository_Delete_Call {
	return &Repository_Delete_Call{Call: _e.mock.On("Delete", ctx, scope, id)}
}

func (_c *Repository_Delete_Call) Run(run func(ctx context.Context, scope domain.Scope, id uuid.UUID)) *Repository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *Repository_Delete_Call) Return(_a0 error) *Repository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_Delete_Call) RunAndReturn(run func(context.Context, domain.Scope, uuid.UUID) error) *Repository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteGrant provides a mock function with given fields: ctx, scope, agentID, integrationID
func (_m *Repository) DeleteGrant(ctx context.Context, scope domain.Scope, agentID uuid.UUID, integrationID uuid.UUID) error {
	ret := _m.Called(ctx, scope, agentID, integrationID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteGrant")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, scope, agentID, integrationID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_DeleteGrant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteGrant'
type Repository_DeleteGrant_Call struct {
	*mock.Call
}

// DeleteGrant is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
//   - agentID uuid.UUID
//   - integrationID uuid.UUID
func (_e *Repository_Expecter) DeleteGrant(ctx interface{}, scope interface{}, agentID interface{}, integrationID interface{}) *Repository_DeleteGrant_Call {
	return &Repository_DeleteGrant_Call{Call: _e.mock.On("DeleteGrant", ctx, scope, agentID, integrationID)}
}

func (_c *Repository_DeleteGrant_Call) Run(run func(ctx context.Context, scope domain.Scope, agentID uuid.UUID, integrationID uuid.UUID)) *Repository_DeleteGrant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope), args[2].(uuid.UUID), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *Repository_DeleteGrant_Call) Return(_a0 error) *Repository_DeleteGrant_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_DeleteGrant_Call) RunAndReturn(run func(context.Context, domain.Scope, uuid.UUID, uuid.UUID) error) *Repository_DeleteGrant_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, scope, id
func (_m *Repository) Get(ctx context.Context, scope domain.Scope, id uuid.UUID) (domain.Agent, error) {
	ret := _m.Called(ctx, scope, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.Agent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, uuid.UUID) (domain.Agent, error)); ok {
		return rf(ctx, scope, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, uuid.UUID) domain.Agent); ok {
		r0 = rf(ctx, scope, id)
	} else {
		r0 = ret.Get(0).(domain.Agent)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Scope, uuid.UUID) error); ok {
		r1 = rf(ctx, scope, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type Repository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
//   - id uuid.UUID
func (_e *Repository_Expecter) Get(ctx interface{}, scope interface{}, id interface{}) *Repository_Get_Call {
	return &Repository_Get_Call{Call: _e.mock.On("Get", ctx, scope, id)}
}

func (_c *Repository_Get_Call) Run(run func(ctx context.Context, scope domain.Scope, id uuid.UUID)) *Repository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *Repository_Get_Call) Return(_a0 domain.Agent, _a1 error) *Repository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_Get_Call) RunAndReturn(run func(context.Context, domain.Scope, uuid.UUID) (domain.Agent, error)) *Repository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Grants provides a mock function with given fields: ctx, scope, agentID
func (_m *Repository) Grants(ctx context.Context, scope domain.Scope, agentID uuid.UUID) ([]domain.Grant, error) {
	ret := _m.Called(ctx, scope, agentID)

	if len(ret) == 0 {
		panic("no return value specified for Grants")
	}

	var r0 []domain.Grant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, uuid.UUID) ([]domain.Grant, error)); ok {
		return rf(ctx, scope, agentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, uuid.UUID) []domain.Grant); ok {
		r0 = rf(ctx, scope, agentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Grant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Scope, uuid.UUID) error); ok {
		r1 = rf(ctx, scope, agentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_Grants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Grants'
type Repository_Grants_Call struct {
	*mock.Call
}

// Grants is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
//   - agentID uuid.UUID
func (_e *Repository_Expecter) Grants(ctx interface{}, scope interface{}, agentID interface{}) *Repository_Grants_Call {
	return &Repository_Grants_Call{Call: _e.mock.On("Grants", ctx, scope, agentID)}
}

func (_c *Repository_Grants_Call) Run(run func(ctx context.Context, scope domain.Scope, agentID uuid.UUID)) *Repository_Grants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *Repository_Grants_Call) Return(_a0 []domain.Grant, _a1 error) *Repository_Grants_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_Grants_Call) RunAndReturn(run func(context.Context, domain.Scope, uuid.UUID) ([]domain.Grant, error)) *Repository_Grants_Call {
	_c.Call.Return(run)
	return _c
}

// Integrations provides a mock function with given fields: ctx, scope
func (_m *Repository) Integrations(ctx context.Context, scope domain.Scope) ([]domain.Integration, error) {
	ret := _m.Called(ctx, scope)

	if len(ret) == 0 {
		panic("no return value specified for Integrations")
	}

	var r0 []domain.Integration
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope) ([]domain.Integration, error)); ok {
		return rf(ctx, scope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope) []domain.Integration); ok {
		r0 = rf(ctx, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Integration)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Scope) error); ok {
		r1 = rf(ctx, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_Integrations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Integrations'
type Repository_Integrations_Call struct {
	*mock.Call
}

// Integrations is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
func (_e *Repository_Expecter) Integrations(ctx interface{}, scope interface{}) *Repository_Integrations_Call {
	return &Repository_Integrations_Call{Call: _e.mock.On("Integrations", ctx, scope)}
}

func (_c *Repository_Integrations_Call) Run(run func(ctx context.Context, scope domain.Scope)) *Repository_Integrations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope))
	})
	return _c
}

func (_c *Repository_Integrations_Call) Return(_a0 []domain.Integration, _a1 error) *Repository_Integrations_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_Integrations_Call) RunAndReturn(run func(context.Context, domain.Scope) ([]domain.Integration, error)) *Repository_Integrations_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, scope
func (_m *Repository) List(ctx context.Context, scope domain.Scope) ([]domain.Agent, error) {
	ret := _m.Called(ctx, scope)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Agent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope) ([]domain.Agent, error)); ok {
		return rf(ctx, scope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope) []domain.Agent); ok {
		r0 = rf(ctx, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Agent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Scope) error); ok {
		r1 = rf(ctx, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type Repository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
func (_e *Repository_Expecter) List(ctx interface{}, scope interface{}) *Repository_List_Call {
	return &Repository_List_Call{Call: _e.mock.On("List", ctx, scope)}
}

func (_c *Repository_List_Call) Run(run func(ctx context.Context, scope domain.Scope)) *Repository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope))
	})
	return _c
}

func (_c *Repository_List_Call) Return(_a0 []domain.Agent, _a1 error) *Repository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_List_Call) RunAndReturn(run func(context.Context, domain.Scope) ([]domain.Agent, error)) *Repository_List_Call {
	_c.Call.Return(run)
	return _c
}

// ReasonFor provides a mock function with given fields: ctx, scope, id
func (_m *Repository) ReasonFor(ctx context.Context, scope domain.Scope, id uuid.UUID) (*domain.Reason, error) {
	ret := _m.Called(ctx, scope, id)

	if len(ret) == 0 {
		panic("no return value specified for ReasonFor")
	}

	var r0 *domain.Reason
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, uuid.UUID) (*domain.Reason, error)); ok {
		return rf(ctx, scope, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, uuid.UUID) *domain.Reason); ok {
		r0 = rf(ctx, scope, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Reason)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Scope, uuid.UUID) error); ok {
		r1 = rf(ctx, scope, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_ReasonFor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReasonFor'
type Repository_ReasonFor_Call struct {
	*mock.Call
}

// ReasonFor is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
//   - id uuid.UUID
func (_e *Repository_Expecter) ReasonFor(ctx interface{}, scope interface{}, id interface{}) *Repository_ReasonFor_Call {
	return &Repository_ReasonFor_Call{Call: _e.mock.On("ReasonFor", ctx, scope, id)}
}

func (_c *Repository_ReasonFor_Call) Run(run func(ctx context.Context, scope domain.Scope, id uuid.UUID)) *Repository_ReasonFor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *Repository_ReasonFor_Call) Return(_a0 *domain.Reason, _a1 error) *Repository_ReasonFor_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_ReasonFor_Call) RunAndReturn(run func(context.Context, domain.Scope, uuid.UUID) (*domain.Reason, error)) *Repository_ReasonFor_Call {
	_c.Call.Return(run)
	return _c
}

// RunningTasks provides a mock function with given fields: ctx, scope, id
func (_m *Repository) RunningTasks(ctx context.Context, scope domain.Scope, id uuid.UUID) (int64, error) {
	ret := _m.Called(ctx, scope, id)

	if len(ret) == 0 {
		panic("no return value specified for RunningTasks")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, uuid.UUID) (int64, error)); ok {
		return rf(ctx, scope, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, uuid.UUID) int64); ok {
		r0 = rf(ctx, scope, id)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Scope, uuid.UUID) error); ok {
		r1 = rf(ctx, scope, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_RunningTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunningTasks'
type Repository_RunningTasks_Call struct {
	*mock.Call
}

// RunningTasks is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
//   - id uuid.UUID
func (_e *Repository_Expecter) RunningTasks(ctx interface{}, scope interface{}, id interface{}) *Repository_RunningTasks_Call {
	return &Repository_RunningTasks_Call{Call: _e.mock.On("RunningTasks", ctx, scope, id)}
}

func (_c *Repository_RunningTasks_Call) Run(run func(ctx context.Context, scope domain.Scope, id uuid.UUID)) *Repository_RunningTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *Repository_RunningTasks_Call) Return(_a0 int64, _a1 error) *Repository_RunningTasks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_RunningTasks_Call) RunAndReturn(run func(context.Context, domain.Scope, uuid.UUID) (int64, error)) *Repository_RunningTasks_Call {
	_c.Call.Return(run)
	return _c
}

// SetGrant provides a mock function with given fields: ctx, scope, agentID, integrationID, permission
func (_m *Repository) SetGrant(ctx context.Context, scope domain.Scope, agentID uuid.UUID, integrationID uuid.UUID, permission string) (domain.Grant, error) {
	ret := _m.Called(ctx, scope, agentID, integrationID, permission)

	if len(ret) == 0 {
		panic("no return value specified for SetGrant")
	}

	var r0 domain.Grant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, uuid.UUID, uuid.UUID, string) (domain.Grant, error)); ok {
		return rf(ctx, scope, agentID, integrationID, permission)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, uuid.UUID, uuid.UUID, string) domain.Grant); ok {
		r0 = rf(ctx, scope, agentID, integrationID, permission)
	} else {
		r0 = ret.Get(0).(domain.Grant)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Scope, uuid.UUID, uuid.UUID, string) error); ok {
		r1 = rf(ctx, scope, agentID, integrationID, permission)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_SetGrant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetGrant'
type Repository_SetGrant_Call struct {
	*mock.Call
}

// SetGrant is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
//   - agentID uuid.UUID
//   - integrationID uuid.UUID
//   - permission string
func (_e *Repository_Expecter) SetGrant(ctx interface{}, scope interface{}, agentID interface{}, integrationID interface{}, permission interface{}) *Repository_SetGrant_Call {
	return &Repository_SetGrant_Call{Call: _e.mock.On("SetGrant", ctx, scope, agentID, integrationID, permission)}
}

func (_c *Repository_SetGrant_Call) Run(run func(ctx context.Context, scope domain.Scope, agentID uuid.UUID, integrationID uuid.UUID, permission string)) *Repository_SetGrant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope), args[2].(uuid.UUID), args[3].(uuid.UUID), args[4].(string))
	})
	return _c
}

func (_c *Repository_SetGrant_Call) Return(_a0 domain.Grant, _a1 error) *Repository_SetGrant_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_SetGrant_Call) RunAndReturn(run func(context.Context, domain.Scope, uuid.UUID, uuid.UUID, string) (domain.Grant, error)) *Repository_SetGrant_Call {
	_c.Call.Return(run)
	return _c
}

// SetStatus provides a mock function with given fields: ctx, scope, id, status
func (_m *Repository) SetStatus(ctx context.Context, scope domain.Scope, id uuid.UUID, status string) (domain.Agent, error) {
	ret := _m.Called(ctx, scope, id, status)

	if len(ret) == 0 {
		panic("no return value specified for SetStatus")
	}

	var r0 domain.Agent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, uuid.UUID, string) (domain.Agent, error)); ok {
		return rf(ctx, scope, id, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, uuid.UUID, string) domain.Agent); ok {
		r0 = rf(ctx, scope, id, status)
	} else {
		r0 = ret.Get(0).(domain.Agent)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Scope, uuid.UUID, string) error); ok {
		r1 = rf(ctx, scope, id, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_SetStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetStatus'
type Repository_SetStatus_Call struct {
	*mock.Call
}

// SetStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
//   - id uuid.UUID
//   - status string
func (_e *Repository_Expecter) SetStatus(ctx interface{}, scope interface{}, id interface{}, status interface{}) *Repository_SetStatus_Call {
	return &Repository_SetStatus_Call{Call: _e.mock.On("SetStatus", ctx, scope, id, status)}
}

func (_c *Repository_SetStatus_Call) Run(run func(ctx context.Context, scope domain.Scope, id uuid.UUID, status string)) *Repository_SetStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope), args[2].(uuid.UUID), args[3].(string))
	})
	return _c
}

func (_c *Repository_SetStatus_Call) Return(_a0 domain.Agent, _a1 error) *Repository_SetStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_SetStatus_Call) RunAndReturn(run func(context.Context, domain.Scope, uuid.UUID, string) (domain.Agent, error)) *Repository_SetStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Teams provides a mock function with given fields: ctx, scope
func (_m *Repository) Teams(ctx context.Context, scope domain.Scope) ([]domain.Team, error) {
	ret := _m.Called(ctx, scope)

	if len(ret) == 0 {
		panic("no return value specified for Teams")
	}

	var r0 []domain.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope) ([]domain.Team, error)); ok {
		return rf(ctx, scope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope) []domain.Team); ok {
		r0 = rf(ctx, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Scope) error); ok {
		r1 = rf(ctx, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_Teams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Teams'
type Repository_Teams_Call struct {
	*mock.Call
}

// Teams is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
func (_e *Repository_Expecter) Teams(ctx interface{}, scope interface{}) *Repository_Teams_Call {
	return &Repository_Teams_Call{Call: _e.mock.On("Teams", ctx, scope)}
}

func (_c *Repository_Teams_Call) Run(run func(ctx context.Context, scope domain.Scope)) *Repository_Teams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope))
	})
	return _c
}

func (_c *Repository_Teams_Call) Return(_a0 []domain.Team, _a1 error) *Repository_Teams_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_Teams_Call) RunAndReturn(run func(context.Context, domain.Scope) ([]domain.Team, error)) *Repository_Teams_Call {
	_c.Call.Return(run)
	return _c
}

// Template provides a mock function with given fields: ctx, key
func (_m *Repository) Template(ctx context.Context, key string) (domain.Template, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Template")
	}

	var r0 domain.Template
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Template, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Template); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Get(0).(domain.Template)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_Template_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Template'
type Repository_Template_Call struct {
	*mock.Call
}

// Template is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *Repository_Expecter) Template(ctx interface{}, key interface{}) *Repository_Template_Call {
	return &Repository_Template_Call{Call: _e.mock.On("Template", ctx, key)}
}

func (_c *Repository_Template_Call) Run(run func(ctx context.Context, key string)) *Repository_Template_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Repository_Template_Call) Return(_a0 domain.Template, _a1 error) *Repository_Template_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_Template_Call) RunAndReturn(run func(context.Context, string) (domain.Template, error)) *Repository_Template_Call {
	_c.Call.Return(run)
	return _c
}

// Templates provides a mock function with given fields: ctx
func (_m *Repository) Templates(ctx context.Context) ([]domain.Template, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Templates")
	}

	var r0 []domain.Template
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Template, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Template); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Template)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_Templates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Templates'
type Repository_Templates_Call struct {
	*mock.Call
}

// Templates is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Repository_Expecter) Templates(ctx interface{}) *Repository_Templates_Call {
	return &Repository_Templates_Call{Call: _e.mock.On("Templates", ctx)}
}

func (_c *Repository_Templates_Call) Run(run func(ctx context.Context)) *Repository_Templates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Repository_Templates_Call) Return(_a0 []domain.Template, _a1 error) *Repository_Templates_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_Templates_Call) RunAndReturn(run func(context.Context) ([]domain.Template, error)) *Repository_Templates_Call {
	_c.Call.Return(run)
	return _c
}

// ToolCatalog provides a mock function with given fields: ctx
func (_m *Repository) ToolCatalog(ctx context.Context) ([]domain.Tool, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ToolCatalog")
	}

	var r0 []domain.Tool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Tool, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Tool); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Tool)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_ToolCatalog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToolCatalog'
type Repository_ToolCatalog_Call struct {
	*mock.Call
}

// ToolCatalog is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Repository_Expecter) ToolCatalog(ctx interface{}) *Repository_ToolCatalog_Call {
	return &Repository_ToolCatalog_Call{Call: _e.mock.On("ToolCatalog", ctx)}
}

func (_c *Repository_ToolCatalog_Call) Run(run func(ctx context.Context)) *Repository_ToolCatalog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Repository_ToolCatalog_Call) Return(_a0 []domain.Tool, _a1 error) *Repository_ToolCatalog_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_ToolCatalog_Call) RunAndReturn(run func(context.Context) ([]domain.Tool, error)) *Repository_ToolCatalog_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, scope, id, req
func (_m *Repository) Update(ctx context.Context, scope domain.Scope, id uuid.UUID, req domain.UpdateRequest) (domain.Agent, error) {
	ret := _m.Called(ctx, scope, id, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 domain.Agent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, uuid.UUID, domain.UpdateRequest) (domain.Agent, error)); ok {
		return rf(ctx, scope, id, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, uuid.UUID, domain.UpdateRequest) domain.Agent); ok {
		r0 = rf(ctx, scope, id, req)
	} else {
		r0 = ret.Get(0).(domain.Agent)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Scope, uuid.UUID, domain.UpdateRequest) error); ok {
		r1 = rf(ctx, scope, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type Repository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
//   - id uuid.UUID
//   - req domain.UpdateRequest
func (_e *Repository_Expecter) Update(ctx interface{}, scope interface{}, id interface{}, req interface{}) *Repository_Update_Call {
	return &Repository_Update_Call{Call: _e.mock.On("Update", ctx, scope, id, req)}
}

func (_c *Repository_Update_Call) Run(run func(ctx context.Context, scope domain.Scope, id uuid.UUID, req domain.UpdateRequest)) *Repository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope), args[2].(uuid.UUID), args[3].(domain.UpdateRequest))
	})
	return _c
}

func (_c *Repository_Update_Call) Return(_a0 domain.Agent, _a1 error) *Repository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_Update_Call) RunAndReturn(run func(context.Context, domain.Scope, uuid.UUID, domain.UpdateRequest) (domain.Agent, error)) *Repository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
