// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const consumeEmailVerificationToken = `-- name: ConsumeEmailVerificationToken :one
UPDATE email_verification_tokens
SET used_at = now()
WHERE token_hash = $1
  AND used_at IS NULL
  AND expires_at > now()
RETURNING id, user_id, token_hash, expires_at, used_at, created_at
`

// Single use is enforced by the UPDATE: the second call matches no row.
func (q *Queries) ConsumeEmailVerificationToken(ctx context.Context, tokenHash string) (EmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, consumeEmailVerificationToken, tokenHash)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const consumePasswordResetToken = `-- name: ConsumePasswordResetToken :one
UPDATE password_reset_tokens
SET used_at = now()
WHERE token_hash = $1
  AND used_at IS NULL
  AND expires_at > now()
RETURNING id, user_id, token_hash, expires_at, used_at, created_at
`

func (q *Queries) ConsumePasswordResetToken(ctx context.Context, tokenHash string) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, consumePasswordResetToken, tokenHash)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createEmailVerificationToken = `-- name: CreateEmailVerificationToken :one
INSERT INTO email_verification_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, used_at, created_at
`

type CreateEmailVerificationTokenParams struct {
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt time.Time
}

func (q *Queries) CreateEmailVerificationToken(ctx context.Context, arg CreateEmailVerificationTokenParams) (EmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, createEmailVerificationToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createGoogleUser = `-- name: CreateGoogleUser :one
INSERT INTO users (email, google_subject, email_verified_at)
VALUES ($1, $2, now())
RETURNING id, email, password_hash, email_verified_at, google_subject, created_at, updated_at, onboarded_at
`

type CreateGoogleUserParams struct {
	Email         string
	GoogleSubject *string
}

// Google accounts start with an empty password hash and are already verified:
// the provider asserted the address.
func (q *Queries) CreateGoogleUser(ctx context.Context, arg CreateGoogleUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createGoogleUser, arg.Email, arg.GoogleSubject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.GoogleSubject,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OnboardedAt,
	)
	return i, err
}

const createPasswordResetToken = `-- name: CreatePasswordResetToken :one
INSERT INTO password_reset_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, used_at, created_at
`

type CreatePasswordResetTokenParams struct {
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt time.Time
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, createPasswordResetToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, refresh_token_hash, user_agent, ip, expires_at, rotated_from)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, refresh_token_hash, rotated_from, user_agent, ip, expires_at, revoked_at, created_at
`

type CreateSessionParams struct {
	UserID           uuid.UUID
	RefreshTokenHash string
	UserAgent        string
	Ip               string
	ExpiresAt        time.Time
	RotatedFrom      *uuid.UUID
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.RefreshTokenHash,
		arg.UserAgent,
		arg.Ip,
		arg.ExpiresAt,
		arg.RotatedFrom,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.RotatedFrom,
		&i.UserAgent,
		&i.Ip,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash)
VALUES ($1, $2)
RETURNING id, email, password_hash, email_verified_at, google_subject, created_at, updated_at, onboarded_at
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
}

// Password accounts. The caller stores the argon2id hash, never the password.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.GoogleSubject,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OnboardedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_id, refresh_token_hash, rotated_from, user_agent, ip, expires_at, revoked_at, created_at FROM sessions WHERE id = $1
`

// The access token carries the session id; this is how a request proves its
// session is still alive (not revoked, not expired).
func (q *Queries) GetSessionByID(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.RotatedFrom,
		&i.UserAgent,
		&i.Ip,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, user_id, refresh_token_hash, rotated_from, user_agent, ip, expires_at, revoked_at, created_at FROM sessions WHERE refresh_token_hash = $1
`

func (q *Queries) GetSessionByTokenHash(ctx context.Context, refreshTokenHash string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, refreshTokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.RotatedFrom,
		&i.UserAgent,
		&i.Ip,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, email_verified_at, google_subject, created_at, updated_at, onboarded_at FROM users WHERE lower(email) = lower($1)
`

func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.GoogleSubject,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OnboardedAt,
	)
	return i, err
}

const getUserByGoogleSubject = `-- name: GetUserByGoogleSubject :one
SELECT id, email, password_hash, email_verified_at, google_subject, created_at, updated_at, onboarded_at FROM users WHERE google_subject = $1
`

func (q *Queries) GetUserByGoogleSubject(ctx context.Context, googleSubject *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleSubject, googleSubject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.GoogleSubject,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OnboardedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, email_verified_at, google_subject, created_at, updated_at, onboarded_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.GoogleSubject,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OnboardedAt,
	)
	return i, err
}

const invalidateEmailVerificationTokens = `-- name: InvalidateEmailVerificationTokens :execrows
UPDATE email_verification_tokens
SET used_at = now()
WHERE user_id = $1 AND used_at IS NULL
`

func (q *Queries) InvalidateEmailVerificationTokens(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, invalidateEmailVerificationTokens, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const invalidatePasswordResetTokens = `-- name: InvalidatePasswordResetTokens :execrows
UPDATE password_reset_tokens
SET used_at = now()
WHERE user_id = $1 AND used_at IS NULL
`

func (q *Queries) InvalidatePasswordResetTokens(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, invalidatePasswordResetTokens, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const linkGoogleSubject = `-- name: LinkGoogleSubject :one
UPDATE users
SET google_subject = $2,
    email_verified_at = COALESCE(email_verified_at, now()),
    updated_at = now()
WHERE id = $1
RETURNING id, email, password_hash, email_verified_at, google_subject, created_at, updated_at, onboarded_at
`

type LinkGoogleSubjectParams struct {
	ID            uuid.UUID
	GoogleSubject *string
}

// Links a Google identity to an existing account with the same email, so a user
// who signed up with a password is not duplicated.
func (q *Queries) LinkGoogleSubject(ctx context.Context, arg LinkGoogleSubjectParams) (User, error) {
	row := q.db.QueryRow(ctx, linkGoogleSubject, arg.ID, arg.GoogleSubject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.GoogleSubject,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OnboardedAt,
	)
	return i, err
}

const markEmailVerified = `-- name: MarkEmailVerified :one
UPDATE users
SET email_verified_at = COALESCE(email_verified_at, now()),
    updated_at = now()
WHERE id = $1
RETURNING id, email, password_hash, email_verified_at, google_subject, created_at, updated_at, onboarded_at
`

func (q *Queries) MarkEmailVerified(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, markEmailVerified, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.GoogleSubject,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OnboardedAt,
	)
	return i, err
}

const markOnboarded = `-- name: MarkOnboarded :one
UPDATE users
SET onboarded_at = COALESCE(onboarded_at, now()), updated_at = now()
WHERE id = $1
RETURNING id, email, password_hash, email_verified_at, google_subject, created_at, updated_at, onboarded_at
`

func (q *Queries) MarkOnboarded(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, markOnboarded, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.GoogleSubject,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OnboardedAt,
	)
	return i, err
}

const revokeSession = `-- name: RevokeSession :execrows
UPDATE sessions
SET revoked_at = now()
WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSession, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSessionByTokenHash = `-- name: RevokeSessionByTokenHash :execrows
UPDATE sessions
SET revoked_at = now()
WHERE refresh_token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSessionByTokenHash(ctx context.Context, refreshTokenHash string) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSessionByTokenHash, refreshTokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSessionsForUser = `-- name: RevokeSessionsForUser :execrows
UPDATE sessions
SET revoked_at = now()
WHERE user_id = $1 AND revoked_at IS NULL
`

// Used after a password reset: every existing session must be re-established.
func (q *Queries) RevokeSessionsForUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSessionsForUser, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePasswordHash = `-- name: UpdatePasswordHash :one
UPDATE users
SET password_hash = $2, updated_at = now()
WHERE id = $1
RETURNING id, email, password_hash, email_verified_at, google_subject, created_at, updated_at, onboarded_at
`

type UpdatePasswordHashParams struct {
	ID           uuid.UUID
	PasswordHash string
}

func (q *Queries) UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) (User, error) {
	row := q.db.QueryRow(ctx, updatePasswordHash, arg.ID, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.GoogleSubject,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OnboardedAt,
	)
	return i, err
}
