// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// Provisioner is an autogenerated mock type for the Provisioner type
type Provisioner struct {
	mock.Mock
}

type Provisioner_Expecter struct {
	mock *mock.Mock
}

func (_m *Provisioner) EXPECT() *Provisioner_Expecter {
	return &Provisioner_Expecter{mock: &_m.Mock}
}

// Provision provides a mock function with given fields: ctx, workspaceID, teamID
func (_m *Provisioner) Provision(ctx context.Context, workspaceID uuid.UUID, teamID uuid.UUID) error {
	ret := _m.Called(ctx, workspaceID, teamID)

	if len(ret) == 0 {
		panic("no return value specified for Provision")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, workspaceID, teamID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Provisioner_Provision_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Provision'
type Provisioner_Provision_Call struct {
	*mock.Call
}

// Provision is a helper method to define mock.On call
//   - ctx context.Context
//   - workspaceID uuid.UUID
//   - teamID uuid.UUID
func (_e *Provisioner_Expecter) Provision(ctx interface{}, workspaceID interface{}, teamID interface{}) *Provisioner_Provision_Call {
	return &Provisioner_Provision_Call{Call: _e.mock.On("Provision", ctx, workspaceID, teamID)}
}

func (_c *Provisioner_Provision_Call) Run(run func(ctx context.Context, workspaceID uuid.UUID, teamID uuid.UUID)) *Provisioner_Provision_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *Provisioner_Provision_Call) Return(_a0 error) *Provisioner_Provision_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Provisioner_Provision_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *Provisioner_Provision_Call {
	_c.Call.Return(run)
	return _c
}

// NewProvisioner creates a new instance of Provisioner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProvisioner(t interface {
	mock.TestingT
	Cleanup(func())
}) *Provisioner {
	mock := &Provisioner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
