// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/robzlabz/employeebot/apps/backend/internal/modules/workspace/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// AcceptInvitation provides a mock function with given fields: ctx, token, userID, email
func (_m *Service) AcceptInvitation(ctx context.Context, token string, userID uuid.UUID, email string) (domain.Workspace, error) {
	ret := _m.Called(ctx, token, userID, email)

	if len(ret) == 0 {
		panic("no return value specified for AcceptInvitation")
	}

	var r0 domain.Workspace
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID, string) (domain.Workspace, error)); ok {
		return rf(ctx, token, userID, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID, string) domain.Workspace); ok {
		r0 = rf(ctx, token, userID, email)
	} else {
		r0 = ret.Get(0).(domain.Workspace)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, uuid.UUID, string) error); ok {
		r1 = rf(ctx, token, userID, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_AcceptInvitation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AcceptInvitation'
type Service_AcceptInvitation_Call struct {
	*mock.Call
}

// AcceptInvitation is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - userID uuid.UUID
//   - email string
func (_e *Service_Expecter) AcceptInvitation(ctx interface{}, token interface{}, userID interface{}, email interface{}) *Service_AcceptInvitation_Call {
	return &Service_AcceptInvitation_Call{Call: _e.mock.On("AcceptInvitation", ctx, token, userID, email)}
}

func (_c *Service_AcceptInvitation_Call) Run(run func(ctx context.Context, token string, userID uuid.UUID, email string)) *Service_AcceptInvitation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(uuid.UUID), args[3].(string))
	})
	return _c
}

func (_c *Service_AcceptInvitation_Call) Return(_a0 domain.Workspace, _a1 error) *Service_AcceptInvitation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_AcceptInvitation_Call) RunAndReturn(run func(context.Context, string, uuid.UUID, string) (domain.Workspace, error)) *Service_AcceptInvitation_Call {
	_c.Call.Return(run)
	return _c
}

// Current provides a mock function with given fields: ctx, scope
func (_m *Service) Current(ctx context.Context, scope domain.Scope) (domain.Workspace, error) {
	ret := _m.Called(ctx, scope)

	if len(ret) == 0 {
		panic("no return value specified for Current")
	}

	var r0 domain.Workspace
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope) (domain.Workspace, error)); ok {
		return rf(ctx, scope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope) domain.Workspace); ok {
		r0 = rf(ctx, scope)
	} else {
		r0 = ret.Get(0).(domain.Workspace)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Scope) error); ok {
		r1 = rf(ctx, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_Current_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Current'
type Service_Current_Call struct {
	*mock.Call
}

// Current is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
func (_e *Service_Expecter) Current(ctx interface{}, scope interface{}) *Service_Current_Call {
	return &Service_Current_Call{Call: _e.mock.On("Current", ctx, scope)}
}

func (_c *Service_Current_Call) Run(run func(ctx context.Context, scope domain.Scope)) *Service_Current_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope))
	})
	return _c
}

func (_c *Service_Current_Call) Return(_a0 domain.Workspace, _a1 error) *Service_Current_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_Current_Call) RunAndReturn(run func(context.Context, domain.Scope) (domain.Workspace, error)) *Service_Current_Call {
	_c.Call.Return(run)
	return _c
}

// Invitations provides a mock function with given fields: ctx, scope
func (_m *Service) Invitations(ctx context.Context, scope domain.Scope) ([]domain.Invitation, error) {
	ret := _m.Called(ctx, scope)

	if len(ret) == 0 {
		panic("no return value specified for Invitations")
	}

	var r0 []domain.Invitation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope) ([]domain.Invitation, error)); ok {
		return rf(ctx, scope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope) []domain.Invitation); ok {
		r0 = rf(ctx, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Invitation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Scope) error); ok {
		r1 = rf(ctx, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_Invitations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Invitations'
type Service_Invitations_Call struct {
	*mock.Call
}

// Invitations is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
func (_e *Service_Expecter) Invitations(ctx interface{}, scope interface{}) *Service_Invitations_Call {
	return &Service_Invitations_Call{Call: _e.mock.On("Invitations", ctx, scope)}
}

func (_c *Service_Invitations_Call) Run(run func(ctx context.Context, scope domain.Scope)) *Service_Invitations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope))
	})
	return _c
}

func (_c *Service_Invitations_Call) Return(_a0 []domain.Invitation, _a1 error) *Service_Invitations_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_Invitations_Call) RunAndReturn(run func(context.Context, domain.Scope) ([]domain.Invitation, error)) *Service_Invitations_Call {
	_c.Call.Return(run)
	return _c
}

// Invite provides a mock function with given fields: ctx, scope, actorRole, actorID, email, role
func (_m *Service) Invite(ctx context.Context, scope domain.Scope, actorRole string, actorID uuid.UUID, email string, role string) (domain.Invitation, error) {
	ret := _m.Called(ctx, scope, actorRole, actorID, email, role)

	if len(ret) == 0 {
		panic("no return value specified for Invite")
	}

	var r0 domain.Invitation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, string, uuid.UUID, string, string) (domain.Invitation, error)); ok {
		return rf(ctx, scope, actorRole, actorID, email, role)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, string, uuid.UUID, string, string) domain.Invitation); ok {
		r0 = rf(ctx, scope, actorRole, actorID, email, role)
	} else {
		r0 = ret.Get(0).(domain.Invitation)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Scope, string, uuid.UUID, string, string) error); ok {
		r1 = rf(ctx, scope, actorRole, actorID, email, role)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_Invite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Invite'
type Service_Invite_Call struct {
	*mock.Call
}

// Invite is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
//   - actorRole string
//   - actorID uuid.UUID
//   - email string
//   - role string
func (_e *Service_Expecter) Invite(ctx interface{}, scope interface{}, actorRole interface{}, actorID interface{}, email interface{}, role interface{}) *Service_Invite_Call {
	return &Service_Invite_Call{Call: _e.mock.On("Invite", ctx, scope, actorRole, actorID, email, role)}
}

func (_c *Service_Invite_Call) Run(run func(ctx context.Context, scope domain.Scope, actorRole string, actorID uuid.UUID, email string, role string)) *Service_Invite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope), args[2].(string), args[3].(uuid.UUID), args[4].(string), args[5].(string))
	})
	return _c
}

func (_c *Service_Invite_Call) Return(_a0 domain.Invitation, _a1 error) *Service_Invite_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_Invite_Call) RunAndReturn(run func(context.Context, domain.Scope, string, uuid.UUID, string, string) (domain.Invitation, error)) *Service_Invite_Call {
	_c.Call.Return(run)
	return _c
}

// Members provides a mock function with given fields: ctx, scope
func (_m *Service) Members(ctx context.Context, scope domain.Scope) ([]domain.Member, error) {
	ret := _m.Called(ctx, scope)

	if len(ret) == 0 {
		panic("no return value specified for Members")
	}

	var r0 []domain.Member
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope) ([]domain.Member, error)); ok {
		return rf(ctx, scope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope) []domain.Member); ok {
		r0 = rf(ctx, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Member)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Scope) error); ok {
		r1 = rf(ctx, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_Members_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Members'
type Service_Members_Call struct {
	*mock.Call
}

// Members is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
func (_e *Service_Expecter) Members(ctx interface{}, scope interface{}) *Service_Members_Call {
	return &Service_Members_Call{Call: _e.mock.On("Members", ctx, scope)}
}

func (_c *Service_Members_Call) Run(run func(ctx context.Context, scope domain.Scope)) *Service_Members_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope))
	})
	return _c
}

func (_c *Service_Members_Call) Return(_a0 []domain.Member, _a1 error) *Service_Members_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_Members_Call) RunAndReturn(run func(context.Context, domain.Scope) ([]domain.Member, error)) *Service_Members_Call {
	_c.Call.Return(run)
	return _c
}

// Onboard provides a mock function with given fields: ctx, userID, req
func (_m *Service) Onboard(ctx context.Context, userID uuid.UUID, req domain.OnboardRequest) (domain.OnboardResult, error) {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for Onboard")
	}

	var r0 domain.OnboardResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.OnboardRequest) (domain.OnboardResult, error)); ok {
		return rf(ctx, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.OnboardRequest) domain.OnboardResult); ok {
		r0 = rf(ctx, userID, req)
	} else {
		r0 = ret.Get(0).(domain.OnboardResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, domain.OnboardRequest) error); ok {
		r1 = rf(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_Onboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Onboard'
type Service_Onboard_Call struct {
	*mock.Call
}

// Onboard is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - req domain.OnboardRequest
func (_e *Service_Expecter) Onboard(ctx interface{}, userID interface{}, req interface{}) *Service_Onboard_Call {
	return &Service_Onboard_Call{Call: _e.mock.On("Onboard", ctx, userID, req)}
}

func (_c *Service_Onboard_Call) Run(run func(ctx context.Context, userID uuid.UUID, req domain.OnboardRequest)) *Service_Onboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(domain.OnboardRequest))
	})
	return _c
}

func (_c *Service_Onboard_Call) Return(_a0 domain.OnboardResult, _a1 error) *Service_Onboard_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_Onboard_Call) RunAndReturn(run func(context.Context, uuid.UUID, domain.OnboardRequest) (domain.OnboardResult, error)) *Service_Onboard_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveMember provides a mock function with given fields: ctx, scope, actorRole, actorID, userID
func (_m *Service) RemoveMember(ctx context.Context, scope domain.Scope, actorRole string, actorID uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(ctx, scope, actorRole, actorID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, string, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, scope, actorRole, actorID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_RemoveMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveMember'
type Service_RemoveMember_Call struct {
	*mock.Call
}

// RemoveMember is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
//   - actorRole string
//   - actorID uuid.UUID
//   - userID uuid.UUID
func (_e *Service_Expecter) RemoveMember(ctx interface{}, scope interface{}, actorRole interface{}, actorID interface{}, userID interface{}) *Service_RemoveMember_Call {
	return &Service_RemoveMember_Call{Call: _e.mock.On("RemoveMember", ctx, scope, actorRole, actorID, userID)}
}

func (_c *Service_RemoveMember_Call) Run(run func(ctx context.Context, scope domain.Scope, actorRole string, actorID uuid.UUID, userID uuid.UUID)) *Service_RemoveMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope), args[2].(string), args[3].(uuid.UUID), args[4].(uuid.UUID))
	})
	return _c
}

func (_c *Service_RemoveMember_Call) Return(_a0 error) *Service_RemoveMember_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_RemoveMember_Call) RunAndReturn(run func(context.Context, domain.Scope, string, uuid.UUID, uuid.UUID) error) *Service_RemoveMember_Call {
	_c.Call.Return(run)
	return _c
}

// Resolve provides a mock function with given fields: ctx, workspaceID, userID
func (_m *Service) Resolve(ctx context.Context, workspaceID uuid.UUID, userID uuid.UUID) (string, error) {
	ret := _m.Called(ctx, workspaceID, userID)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (string, error)); ok {
		return rf(ctx, workspaceID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) string); ok {
		r0 = rf(ctx, workspaceID, userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, workspaceID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_Resolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolve'
type Service_Resolve_Call struct {
	*mock.Call
}

// Resolve is a helper method to define mock.On call
//   - ctx context.Context
//   - workspaceID uuid.UUID
//   - userID uuid.UUID
func (_e *Service_Expecter) Resolve(ctx interface{}, workspaceID interface{}, userID interface{}) *Service_Resolve_Call {
	return &Service_Resolve_Call{Call: _e.mock.On("Resolve", ctx, workspaceID, userID)}
}

func (_c *Service_Resolve_Call) Run(run func(ctx context.Context, workspaceID uuid.UUID, userID uuid.UUID)) *Service_Resolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *Service_Resolve_Call) Return(_a0 string, _a1 error) *Service_Resolve_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_Resolve_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (string, error)) *Service_Resolve_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeInvitation provides a mock function with given fields: ctx, scope, actorRole, id
func (_m *Service) RevokeInvitation(ctx context.Context, scope domain.Scope, actorRole string, id uuid.UUID) error {
	ret := _m.Called(ctx, scope, actorRole, id)

	if len(ret) == 0 {
		panic("no return value specified for RevokeInvitation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, string, uuid.UUID) error); ok {
		r0 = rf(ctx, scope, actorRole, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_RevokeInvitation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeInvitation'
type Service_RevokeInvitation_Call struct {
	*mock.Call
}

// RevokeInvitation is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
//   - actorRole string
//   - id uuid.UUID
func (_e *Service_Expecter) RevokeInvitation(ctx interface{}, scope interface{}, actorRole interface{}, id interface{}) *Service_RevokeInvitation_Call {
	return &Service_RevokeInvitation_Call{Call: _e.mock.On("RevokeInvitation", ctx, scope, actorRole, id)}
}

func (_c *Service_RevokeInvitation_Call) Run(run func(ctx context.Context, scope domain.Scope, actorRole string, id uuid.UUID)) *Service_RevokeInvitation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope), args[2].(string), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *Service_RevokeInvitation_Call) Return(_a0 error) *Service_RevokeInvitation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_RevokeInvitation_Call) RunAndReturn(run func(context.Context, domain.Scope, string, uuid.UUID) error) *Service_RevokeInvitation_Call {
	_c.Call.Return(run)
	return _c
}

// SetRole provides a mock function with given fields: ctx, scope, actorRole, userID, role
func (_m *Service) SetRole(ctx context.Context, scope domain.Scope, actorRole string, userID uuid.UUID, role string) (domain.Member, error) {
	ret := _m.Called(ctx, scope, actorRole, userID, role)

	if len(ret) == 0 {
		panic("no return value specified for SetRole")
	}

	var r0 domain.Member
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, string, uuid.UUID, string) (domain.Member, error)); ok {
		return rf(ctx, scope, actorRole, userID, role)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, string, uuid.UUID, string) domain.Member); ok {
		r0 = rf(ctx, scope, actorRole, userID, role)
	} else {
		r0 = ret.Get(0).(domain.Member)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Scope, string, uuid.UUID, string) error); ok {
		r1 = rf(ctx, scope, actorRole, userID, role)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_SetRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetRole'
type Service_SetRole_Call struct {
	*mock.Call
}

// SetRole is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
//   - actorRole string
//   - userID uuid.UUID
//   - role string
func (_e *Service_Expecter) SetRole(ctx interface{}, scope interface{}, actorRole interface{}, userID interface{}, role interface{}) *Service_SetRole_Call {
	return &Service_SetRole_Call{Call: _e.mock.On("SetRole", ctx, scope, actorRole, userID, role)}
}

func (_c *Service_SetRole_Call) Run(run func(ctx context.Context, scope domain.Scope, actorRole string, userID uuid.UUID, role string)) *Service_SetRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope), args[2].(string), args[3].(uuid.UUID), args[4].(string))
	})
	return _c
}

func (_c *Service_SetRole_Call) Return(_a0 domain.Member, _a1 error) *Service_SetRole_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_SetRole_Call) RunAndReturn(run func(context.Context, domain.Scope, string, uuid.UUID, string) (domain.Member, error)) *Service_SetRole_Call {
	_c.Call.Return(run)
	return _c
}

// Teams provides a mock function with given fields: ctx, scope
func (_m *Service) Teams(ctx context.Context, scope domain.Scope) ([]domain.Team, error) {
	ret := _m.Called(ctx, scope)

	if len(ret) == 0 {
		panic("no return value specified for Teams")
	}

	var r0 []domain.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope) ([]domain.Team, error)); ok {
		return rf(ctx, scope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope) []domain.Team); ok {
		r0 = rf(ctx, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Scope) error); ok {
		r1 = rf(ctx, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_Teams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Teams'
type Service_Teams_Call struct {
	*mock.Call
}

// Teams is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
func (_e *Service_Expecter) Teams(ctx interface{}, scope interface{}) *Service_Teams_Call {
	return &Service_Teams_Call{Call: _e.mock.On("Teams", ctx, scope)}
}

func (_c *Service_Teams_Call) Run(run func(ctx context.Context, scope domain.Scope)) *Service_Teams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope))
	})
	return _c
}

func (_c *Service_Teams_Call) Return(_a0 []domain.Team, _a1 error) *Service_Teams_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_Teams_Call) RunAndReturn(run func(context.Context, domain.Scope) ([]domain.Team, error)) *Service_Teams_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, scope, actorRole, req
func (_m *Service) Update(ctx context.Context, scope domain.Scope, actorRole string, req domain.UpdateRequest) (domain.Workspace, error) {
	ret := _m.Called(ctx, scope, actorRole, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 domain.Workspace
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, string, domain.UpdateRequest) (domain.Workspace, error)); ok {
		return rf(ctx, scope, actorRole, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Scope, string, domain.UpdateRequest) domain.Workspace); ok {
		r0 = rf(ctx, scope, actorRole, req)
	} else {
		r0 = ret.Get(0).(domain.Workspace)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Scope, string, domain.UpdateRequest) error); ok {
		r1 = rf(ctx, scope, actorRole, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type Service_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - scope domain.Scope
//   - actorRole string
//   - req domain.UpdateRequest
func (_e *Service_Expecter) Update(ctx interface{}, scope interface{}, actorRole interface{}, req interface{}) *Service_Update_Call {
	return &Service_Update_Call{Call: _e.mock.On("Update", ctx, scope, actorRole, req)}
}

func (_c *Service_Update_Call) Run(run func(ctx context.Context, scope domain.Scope, actorRole string, req domain.UpdateRequest)) *Service_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Scope), args[2].(string), args[3].(domain.UpdateRequest))
	})
	return _c
}

func (_c *Service_Update_Call) Return(_a0 domain.Workspace, _a1 error) *Service_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_Update_Call) RunAndReturn(run func(context.Context, domain.Scope, string, domain.UpdateRequest) (domain.Workspace, error)) *Service_Update_Call {
	_c.Call.Return(run)
	return _c
}

// Workspaces provides a mock function with given fields: ctx, userID
func (_m *Service) Workspaces(ctx context.Context, userID uuid.UUID) ([]domain.Workspace, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Workspaces")
	}

	var r0 []domain.Workspace
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]domain.Workspace, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []domain.Workspace); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Workspace)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_Workspaces_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Workspaces'
type Service_Workspaces_Call struct {
	*mock.Call
}

// Workspaces is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *Service_Expecter) Workspaces(ctx interface{}, userID interface{}) *Service_Workspaces_Call {
	return &Service_Workspaces_Call{Call: _e.mock.On("Workspaces", ctx, userID)}
}

func (_c *Service_Workspaces_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *Service_Workspaces_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *Service_Workspaces_Call) Return(_a0 []domain.Workspace, _a1 error) *Service_Workspaces_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_Workspaces_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]domain.Workspace, error)) *Service_Workspaces_Call {
	_c.Call.Return(run)
	return _c
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
