// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Tokens is an autogenerated mock type for the Tokens type
type Tokens struct {
	mock.Mock
}

type Tokens_Expecter struct {
	mock *mock.Mock
}

func (_m *Tokens) EXPECT() *Tokens_Expecter {
	return &Tokens_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function with no fields
func (_m *Tokens) Generate() (string, string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func() (string, string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() string); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func() error); ok {
		r2 = rf()
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Tokens_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type Tokens_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
func (_e *Tokens_Expecter) Generate() *Tokens_Generate_Call {
	return &Tokens_Generate_Call{Call: _e.mock.On("Generate")}
}

func (_c *Tokens_Generate_Call) Run(run func()) *Tokens_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Tokens_Generate_Call) Return(raw string, hash string, err error) *Tokens_Generate_Call {
	_c.Call.Return(raw, hash, err)
	return _c
}

func (_c *Tokens_Generate_Call) RunAndReturn(run func() (string, string, error)) *Tokens_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// NewTokens creates a new instance of Tokens. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokens(t interface {
	mock.TestingT
	Cleanup(func())
}) *Tokens {
	mock := &Tokens{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
