// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Mailer is an autogenerated mock type for the Mailer type
type Mailer struct {
	mock.Mock
}

type Mailer_Expecter struct {
	mock *mock.Mock
}

func (_m *Mailer) EXPECT() *Mailer_Expecter {
	return &Mailer_Expecter{mock: &_m.Mock}
}

// Send provides a mock function with given fields: ctx, to, subject, body
func (_m *Mailer) Send(ctx context.Context, to string, subject string, body string) error {
	ret := _m.Called(ctx, to, subject, body)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, to, subject, body)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Mailer_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type Mailer_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - to string
//   - subject string
//   - body string
func (_e *Mailer_Expecter) Send(ctx interface{}, to interface{}, subject interface{}, body interface{}) *Mailer_Send_Call {
	return &Mailer_Send_Call{Call: _e.mock.On("Send", ctx, to, subject, body)}
}

func (_c *Mailer_Send_Call) Run(run func(ctx context.Context, to string, subject string, body string)) *Mailer_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *Mailer_Send_Call) Return(_a0 error) *Mailer_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Mailer_Send_Call) RunAndReturn(run func(context.Context, string, string, string) error) *Mailer_Send_Call {
	_c.Call.Return(run)
	return _c
}

// NewMailer creates a new instance of Mailer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMailer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mailer {
	mock := &Mailer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
